subscription watchAllPersonTypes(
  $where: [PersonTypesBoolExp!] = {}
  $orderBy: [PersonTypesOrderBy!] = { order: ASC }
  $limit: Int = 25
) {
  personTypes(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
    order
    isFamilyAdmin
    isHidden
  }
}
