include: package:very_good_analysis/analysis_options.yaml
analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**/__generated__/*
  errors:
    duplicate_ignore: false
    invalid_annotation_target: false
    undefined_hidden_name: false
linter:
  rules:
    # Disabled
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
    flutter_style_todos: false
    no_default_cases: false
    omit_local_variable_types: false
    public_member_api_docs: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    prefer_asserts_with_message: false
    # Enabled
    avoid_futureor_void: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    close_sinks: true
    library_names: true
    no_literal_bool_comparisons: true
    package_prefixed_library_names: true
    prefer_mixin: true
    prefer_void_to_null: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unreachable_from_main: true
    unsafe_html: true
    use_decorated_box: true
    use_truncating_division: true
