targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      artemis:
        options:
          ignore_for_file:
            - constant_identifier_names
            - overridden_fields
          schema_mapping:
            - schema: lib/graphql/schema.graphql
              queries_glob: lib/src/repositories/database/**/{subscriptions.graphql,queries.graphql,mutations.graphql}
              output: lib/src/repositories/database/graphql.graphql.dart
          scalar_mapping:
            - graphql_type: name
              dart_type: String

            - graphql_type: _text
              dart_type: List<String>

            - graphql_type: uuid
              dart_type: UuidValue
              custom_parser_import: package:church_admin/graphql/scalars.dart
              use_custom_parser: true

            - graphql_type: geography
              dart_type: Json

            - graphql_type: geometry
              dart_type: Json

            - graphql_type: jsonb
              dart_type: Json

            - graphql_type: smallint
              dart_type: int

            - graphql_type: bigint
              dart_type: int

            - graphql_type: timestamptz
              dart_type: DateTime
              use_custom_parser: true

            - graphql_type: timestamp
              dart_type: DateTime
              use_custom_parser: true

            - graphql_type: date
              dart_type: DateTime
              use_custom_parser: true

            - graphql_type: time
              dart_type: DateTime
              use_custom_parser: true

            - graphql_type: daterange
              dart_type: String
              use_custom_parser: true
