mutation deleteClass($classId: Uuid!) {
  deleteClassesByPk(id: $classId) {
    ...Class
  }
}

mutation insertClass($newClass: ClassesInsertInput!) {
  insertClassesOne(object: $newClass) {
    ...Class
  }
}

mutation updateClass($classId: Uuid!, $newClass: ClassesSetInput!) {
  updateClassesByPk(pkColumns: { id: $classId }, _set: $newClass) {
    ...Class
  }
}
