// Mocks generated by Mockito 5.4.2 from annotations
// in church_admin/test/src/services/notifications/notifications_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:church_admin/church_admin.dart' as _i4;
import 'package:church_admin/src/services/notifications/notifications_storage.dart'
    as _i21;
import 'package:cloud_functions/cloud_functions.dart' as _i7;
import 'package:dio/dio.dart' as _i8;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_messaging/firebase_messaging.dart' as _i12;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i3;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i13;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i14;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i16;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i19;
import 'package:flutter_local_notifications/src/platform_specifics/ios/enums.dart'
    as _i18;
import 'package:flutter_local_notifications/src/types.dart' as _i20;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i15;
import 'package:hive_flutter/hive_flutter.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i11;
import 'package:permission_handler_platform_interface/permission_handler_platform_interface.dart'
    as _i9;
import 'package:rxdart_ext/rxdart_ext.dart' as _i5;
import 'package:timezone/timezone.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationSettings_1 extends _i1.SmartFake
    implements _i3.NotificationSettings {
  _FakeNotificationSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactorManager_2 extends _i1.SmartFake
    implements _i4.MultiFactorManager {
  _FakeMultiFactorManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_3<T> extends _i1.SmartFake
    implements _i5.ValueStream<T> {
  _FakeValueStream_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_4<E> extends _i1.SmartFake implements _i6.Box<E> {
  _FakeBox_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpsCallable_5 extends _i1.SmartFake implements _i7.HttpsCallable {
  _FakeHttpsCallable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpsCallableResult_6<T> extends _i1.SmartFake
    implements _i7.HttpsCallableResult<T> {
  _FakeHttpsCallableResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_7<T> extends _i1.SmartFake implements _i8.Response<T> {
  _FakeResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationSetting_8 extends _i1.SmartFake
    implements _i4.NotificationSetting {
  _FakeNotificationSetting_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PermissionHandlerPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class PermissionHandlerPlatform_ extends _i1.Mock
    implements _i9.PermissionHandlerPlatform {
  @override
  _i10.Future<_i11.PermissionStatus> checkPermissionStatus(
          _i11.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissionStatus,
          [permission],
        ),
        returnValue: _i10.Future<_i11.PermissionStatus>.value(
            _i11.PermissionStatus.denied),
        returnValueForMissingStub: _i10.Future<_i11.PermissionStatus>.value(
            _i11.PermissionStatus.denied),
      ) as _i10.Future<_i11.PermissionStatus>);
  @override
  _i10.Future<_i11.ServiceStatus> checkServiceStatus(
          _i11.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkServiceStatus,
          [permission],
        ),
        returnValue:
            _i10.Future<_i11.ServiceStatus>.value(_i11.ServiceStatus.disabled),
        returnValueForMissingStub:
            _i10.Future<_i11.ServiceStatus>.value(_i11.ServiceStatus.disabled),
      ) as _i10.Future<_i11.ServiceStatus>);
  @override
  _i10.Future<bool> openAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAppSettings,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<Map<_i11.Permission, _i11.PermissionStatus>> requestPermissions(
          List<_i11.Permission>? permissions) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [permissions],
        ),
        returnValue:
            _i10.Future<Map<_i11.Permission, _i11.PermissionStatus>>.value(
                <_i11.Permission, _i11.PermissionStatus>{}),
        returnValueForMissingStub:
            _i10.Future<Map<_i11.Permission, _i11.PermissionStatus>>.value(
                <_i11.Permission, _i11.PermissionStatus>{}),
      ) as _i10.Future<Map<_i11.Permission, _i11.PermissionStatus>>);
  @override
  _i10.Future<bool> shouldShowRequestPermissionRationale(
          _i11.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldShowRequestPermissionRationale,
          [permission],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i12.FirebaseMessaging {
  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
        returnValueForMissingStub: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);
  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isAutoInitEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoInitEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Stream<String> get onTokenRefresh => (super.noSuchMethod(
        Invocation.getter(#onTokenRefresh),
        returnValue: _i10.Stream<String>.empty(),
        returnValueForMissingStub: _i10.Stream<String>.empty(),
      ) as _i10.Stream<String>);
  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  _i10.Future<_i3.RemoteMessage?> getInitialMessage() => (super.noSuchMethod(
        Invocation.method(
          #getInitialMessage,
          [],
        ),
        returnValue: _i10.Future<_i3.RemoteMessage?>.value(),
        returnValueForMissingStub: _i10.Future<_i3.RemoteMessage?>.value(),
      ) as _i10.Future<_i3.RemoteMessage?>);
  @override
  _i10.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<String?> getAPNSToken() => (super.noSuchMethod(
        Invocation.method(
          #getAPNSToken,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
  @override
  _i10.Future<String?> getToken({String? vapidKey}) => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
          {#vapidKey: vapidKey},
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
  @override
  _i10.Future<bool> isSupported() => (super.noSuchMethod(
        Invocation.method(
          #isSupported,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<_i3.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationSettings,
          [],
        ),
        returnValue: _i10.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #getNotificationSettings,
            [],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #getNotificationSettings,
            [],
          ),
        )),
      ) as _i10.Future<_i3.NotificationSettings>);
  @override
  _i10.Future<_i3.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
          {
            #alert: alert,
            #announcement: announcement,
            #badge: badge,
            #carPlay: carPlay,
            #criticalAlert: criticalAlert,
            #provisional: provisional,
            #sound: sound,
          },
        ),
        returnValue: _i10.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #requestPermission,
            [],
            {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
            },
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #requestPermission,
            [],
            {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
            },
          ),
        )),
      ) as _i10.Future<_i3.NotificationSettings>);
  @override
  _i10.Future<void> sendMessage({
    String? to,
    Map<String, String>? data,
    String? collapseKey,
    String? messageId,
    String? messageType,
    int? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #to: to,
            #data: data,
            #collapseKey: collapseKey,
            #messageId: messageId,
            #messageType: messageType,
            #ttl: ttl,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setAutoInitEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAutoInitEnabled,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDeliveryMetricsExportToBigQuery,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setForegroundNotificationPresentationOptions,
          [],
          {
            #alert: alert,
            #badge: badge,
            #sound: sound,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> subscribeToTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToTopic,
          [topic],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> unsubscribeFromTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromTopic,
          [topic],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [NotificationSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationSettings extends _i1.Mock
    implements _i3.NotificationSettings {
  @override
  _i3.AppleNotificationSetting get alert => (super.noSuchMethod(
        Invocation.getter(#alert),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get announcement => (super.noSuchMethod(
        Invocation.getter(#announcement),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AuthorizationStatus get authorizationStatus => (super.noSuchMethod(
        Invocation.getter(#authorizationStatus),
        returnValue: _i3.AuthorizationStatus.authorized,
        returnValueForMissingStub: _i3.AuthorizationStatus.authorized,
      ) as _i3.AuthorizationStatus);
  @override
  _i3.AppleNotificationSetting get timeSensitive => (super.noSuchMethod(
        Invocation.getter(#timeSensitive),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get criticalAlert => (super.noSuchMethod(
        Invocation.getter(#criticalAlert),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get badge => (super.noSuchMethod(
        Invocation.getter(#badge),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get carPlay => (super.noSuchMethod(
        Invocation.getter(#carPlay),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get lockScreen => (super.noSuchMethod(
        Invocation.getter(#lockScreen),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get notificationCenter => (super.noSuchMethod(
        Invocation.getter(#notificationCenter),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleShowPreviewSetting get showPreviews => (super.noSuchMethod(
        Invocation.getter(#showPreviews),
        returnValue: _i3.AppleShowPreviewSetting.always,
        returnValueForMissingStub: _i3.AppleShowPreviewSetting.always,
      ) as _i3.AppleShowPreviewSetting);
  @override
  _i3.AppleNotificationSetting get sound => (super.noSuchMethod(
        Invocation.getter(#sound),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i13.FlutterLocalNotificationsPlugin {
  @override
  _i10.Future<bool?> initialize(
    _i14.InitializationSettings? initializationSettings, {
    _i15.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i15.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i10.Future<bool?>.value(),
        returnValueForMissingStub: _i10.Future<bool?>.value(),
      ) as _i10.Future<bool?>);
  @override
  _i10.Future<_i15.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue:
                _i10.Future<_i15.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i15.NotificationAppLaunchDetails?>.value(),
          ) as _i10.Future<_i15.NotificationAppLaunchDetails?>);
  @override
  _i10.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i16.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i17.TZDateTime? scheduledDate,
    _i16.NotificationDetails? notificationDetails, {
    required _i18.UILocalNotificationDateInterpretation?
        uiLocalNotificationDateInterpretation,
    bool? androidAllowWhileIdle = false,
    _i19.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i20.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #uiLocalNotificationDateInterpretation:
                uiLocalNotificationDateInterpretation,
            #androidAllowWhileIdle: androidAllowWhileIdle,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i15.RepeatInterval? repeatInterval,
    _i16.NotificationDetails? notificationDetails, {
    String? payload,
    bool? androidAllowWhileIdle = false,
    _i19.AndroidScheduleMode? androidScheduleMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #payload: payload,
            #androidAllowWhileIdle: androidAllowWhileIdle,
            #androidScheduleMode: androidScheduleMode,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<List<_i15.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i10.Future<List<_i15.PendingNotificationRequest>>.value(
                    <_i15.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i10.Future<List<_i15.PendingNotificationRequest>>.value(
                    <_i15.PendingNotificationRequest>[]),
          ) as _i10.Future<List<_i15.PendingNotificationRequest>>);
  @override
  _i10.Future<List<_i15.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i10.Future<List<_i15.ActiveNotification>>.value(
            <_i15.ActiveNotification>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i15.ActiveNotification>>.value(
                <_i15.ActiveNotification>[]),
      ) as _i10.Future<List<_i15.ActiveNotification>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  _i4.MultiFactorManager get multiFactorManager => (super.noSuchMethod(
        Invocation.getter(#multiFactorManager),
        returnValue: _FakeMultiFactorManager_2(
          this,
          Invocation.getter(#multiFactorManager),
        ),
        returnValueForMissingStub: _FakeMultiFactorManager_2(
          this,
          Invocation.getter(#multiFactorManager),
        ),
      ) as _i4.MultiFactorManager);
  @override
  set multiFactorManager(_i4.MultiFactorManager? _multiFactorManager) =>
      super.noSuchMethod(
        Invocation.setter(
          #multiFactorManager,
          _multiFactorManager,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i5.ValueStream<_i4.User?> get userStream => (super.noSuchMethod(
        Invocation.getter(#userStream),
        returnValue: _FakeValueStream_3<_i4.User?>(
          this,
          Invocation.getter(#userStream),
        ),
        returnValueForMissingStub: _FakeValueStream_3<_i4.User?>(
          this,
          Invocation.getter(#userStream),
        ),
      ) as _i5.ValueStream<_i4.User?>);
  @override
  _i5.ValueStream<String?> get idTokenStream => (super.noSuchMethod(
        Invocation.getter(#idTokenStream),
        returnValue: _FakeValueStream_3<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
        returnValueForMissingStub: _FakeValueStream_3<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
      ) as _i5.ValueStream<String?>);
  @override
  _i10.Future<bool> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<bool> reauthWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<bool> signUpWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<String?> getStoredPasswordHash() => (super.noSuchMethod(
        Invocation.method(
          #getStoredPasswordHash,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
  @override
  _i10.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [UserSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsService extends _i1.Mock
    implements _i4.UserSettingsService {
  @override
  _i6.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_4<dynamic>(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeBox_4<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i6.Box<dynamic>);
  @override
  bool get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get greatFeastTheme => (super.noSuchMethod(
        Invocation.getter(#greatFeastTheme),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Future<void> setDarkTheme(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDarkTheme,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setRegisteredFCMToken(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setRegisteredFCMToken,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setGreatFeastTheme(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setGreatFeastTheme,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  String? getSecondLineFor(Type? t) => (super.noSuchMethod(
        Invocation.method(
          #getSecondLineFor,
          [t],
        ),
        returnValueForMissingStub: null,
      ) as String?);
  @override
  _i10.Future<void> setSecondLineFor(
    Type? t,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSecondLineFor,
          [
            t,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setupDefaults() => (super.noSuchMethod(
        Invocation.method(
          #setupDefaults,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [FunctionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctionsService extends _i1.Mock implements _i4.FunctionsService {
  @override
  _i7.HttpsCallable httpsCallable(
    String? functionName, {
    _i7.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #httpsCallable,
          [functionName],
          {#options: options},
        ),
        returnValue: _FakeHttpsCallable_5(
          this,
          Invocation.method(
            #httpsCallable,
            [functionName],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeHttpsCallable_5(
          this,
          Invocation.method(
            #httpsCallable,
            [functionName],
            {#options: options},
          ),
        ),
      ) as _i7.HttpsCallable);
  @override
  _i10.Future<_i7.HttpsCallableResult<dynamic>> registerFCMToken(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerFCMToken,
          [token],
        ),
        returnValue: _i10.Future<_i7.HttpsCallableResult<dynamic>>.value(
            _FakeHttpsCallableResult_6<dynamic>(
          this,
          Invocation.method(
            #registerFCMToken,
            [token],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i7.HttpsCallableResult<dynamic>>.value(
                _FakeHttpsCallableResult_6<dynamic>(
          this,
          Invocation.method(
            #registerFCMToken,
            [token],
          ),
        )),
      ) as _i10.Future<_i7.HttpsCallableResult<dynamic>>);
  @override
  _i10.Future<String> getDownloadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadUrl,
          [
            table,
            id,
          ],
          {#contentType: contentType},
        ),
        returnValue: _i10.Future<String>.value(''),
        returnValueForMissingStub: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<String> getUploadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadUrl,
          [
            table,
            id,
          ],
          {#contentType: contentType},
        ),
        returnValue: _i10.Future<String>.value(''),
        returnValueForMissingStub: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<void> deletePhoto(
    String? table,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [
            table,
            id,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<String?> getAddressFromLocation(_i4.Point? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressFromLocation,
          [location],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
  @override
  _i10.Future<_i8.Response<dynamic>> uploadPhoto({
    required String? url,
    required _i10.Stream<List<int>>? fileStream,
    String? contentType,
    int? fileLength,
    void Function(
      int,
      int,
    )? onSendProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [],
          {
            #url: url,
            #fileStream: fileStream,
            #contentType: contentType,
            #fileLength: fileLength,
            #onSendProgress: onSendProgress,
          },
        ),
        returnValue:
            _i10.Future<_i8.Response<dynamic>>.value(_FakeResponse_7<dynamic>(
          this,
          Invocation.method(
            #uploadPhoto,
            [],
            {
              #url: url,
              #fileStream: fileStream,
              #contentType: contentType,
              #fileLength: fileLength,
              #onSendProgress: onSendProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i8.Response<dynamic>>.value(_FakeResponse_7<dynamic>(
          this,
          Invocation.method(
            #uploadPhoto,
            [],
            {
              #url: url,
              #fileStream: fileStream,
              #contentType: contentType,
              #fileLength: fileLength,
              #onSendProgress: onSendProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<dynamic>>);
  @override
  _i10.Future<bool> checkHasuraHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHasuraHealth,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<void> registerUserWithCode(String? registerCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUserWithCode,
          [registerCode],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [InitializationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitializationService extends _i1.Mock
    implements _i4.InitializationService {
  @override
  Set<_i4.Initializer> get steps => (super.noSuchMethod(
        Invocation.getter(#steps),
        returnValue: <_i4.Initializer>{},
        returnValueForMissingStub: <_i4.Initializer>{},
      ) as Set<_i4.Initializer>);
  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [NotificationsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsStorage extends _i1.Mock
    implements _i21.NotificationsStorage {
  @override
  _i10.Future<void> writeNotification(_i4.Notification? notification) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeNotification,
          [notification],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<_i4.Notification?> readNotification(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #readNotification,
          [notificationId],
        ),
        returnValue: _i10.Future<_i4.Notification?>.value(),
        returnValueForMissingStub: _i10.Future<_i4.Notification?>.value(),
      ) as _i10.Future<_i4.Notification?>);
}

/// A class which mocks [NotificationsSettingsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsSettingsStorage extends _i1.Mock
    implements _i4.NotificationsSettingsStorage {
  @override
  _i4.NotificationSetting get birthDayTimeSetting => (super.noSuchMethod(
        Invocation.getter(#birthDayTimeSetting),
        returnValue: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#birthDayTimeSetting),
        ),
        returnValueForMissingStub: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#birthDayTimeSetting),
        ),
      ) as _i4.NotificationSetting);
  @override
  _i4.NotificationSetting get kodasTimeSetting => (super.noSuchMethod(
        Invocation.getter(#kodasTimeSetting),
        returnValue: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#kodasTimeSetting),
        ),
        returnValueForMissingStub: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#kodasTimeSetting),
        ),
      ) as _i4.NotificationSetting);
  @override
  _i4.NotificationSetting get meetingTimeSetting => (super.noSuchMethod(
        Invocation.getter(#meetingTimeSetting),
        returnValue: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#meetingTimeSetting),
        ),
        returnValueForMissingStub: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#meetingTimeSetting),
        ),
      ) as _i4.NotificationSetting);
  @override
  _i4.NotificationSetting get confessionTimeSetting => (super.noSuchMethod(
        Invocation.getter(#confessionTimeSetting),
        returnValue: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#confessionTimeSetting),
        ),
        returnValueForMissingStub: _FakeNotificationSetting_8(
          this,
          Invocation.getter(#confessionTimeSetting),
        ),
      ) as _i4.NotificationSetting);
  @override
  _i10.Future<void> setBirthDayTime(_i4.NotificationSetting? setting) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBirthDayTime,
          [setting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setKodasTime(_i4.NotificationSetting? setting) =>
      (super.noSuchMethod(
        Invocation.method(
          #setKodasTime,
          [setting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setMeetingTime(_i4.NotificationSetting? setting) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMeetingTime,
          [setting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setConfessionTime(_i4.NotificationSetting? setting) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfessionTime,
          [setting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [NotificationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsService extends _i1.Mock
    implements _i4.NotificationsService {
  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i10.Stream<_i4.Notification> get onNotificationTapStream =>
      (super.noSuchMethod(
        Invocation.getter(#onNotificationTapStream),
        returnValue: _i10.Stream<_i4.Notification>.empty(),
        returnValueForMissingStub: _i10.Stream<_i4.Notification>.empty(),
      ) as _i10.Stream<_i4.Notification>);
  @override
  void addForegroundNotificationTap(_i4.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #addForegroundNotificationTap,
          [notification],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void pauseListeners() => super.noSuchMethod(
        Invocation.method(
          #pauseListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void resumeListeners() => super.noSuchMethod(
        Invocation.method(
          #resumeListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<_i4.Notification?> getInitialNotification() =>
      (super.noSuchMethod(
        Invocation.method(
          #getInitialNotification,
          [],
        ),
        returnValue: _i10.Future<_i4.Notification?>.value(),
        returnValueForMissingStub: _i10.Future<_i4.Notification?>.value(),
      ) as _i10.Future<_i4.Notification?>);
  @override
  _i10.Future<void> scheduleBirthDayNotification(
          [_i4.NotificationSetting? notificationSetting =
              const _i4.NotificationSetting(
            11,
            0,
            1,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleBirthDayNotification,
          [notificationSetting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> scheduleMeetingNotification(
          [_i4.NotificationSetting? notificationSetting =
              const _i4.NotificationSetting(
            11,
            0,
            7,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleMeetingNotification,
          [notificationSetting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> scheduleKodasNotification(
          [_i4.NotificationSetting? notificationSetting =
              const _i4.NotificationSetting(
            11,
            0,
            7,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleKodasNotification,
          [notificationSetting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> scheduleConfessionNotification(
          [_i4.NotificationSetting? notificationSetting =
              const _i4.NotificationSetting(
            11,
            0,
            7,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleConfessionNotification,
          [notificationSetting],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> scheduleDefaultNotifications() => (super.noSuchMethod(
        Invocation.method(
          #scheduleDefaultNotifications,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> notify(
    _i4.Notification? notification, {
    int? id,
    _i16.NotificationDetails? notificationDetails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notify,
          [notification],
          {
            #id: id,
            #notificationDetails: notificationDetails,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<bool> registerFCMTokenAndListenForChanges(
          {String? cachedToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerFCMTokenAndListenForChanges,
          [],
          {#cachedToken: cachedToken},
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<bool> requestNotificationsPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestNotificationsPermission,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
