// Mocks generated by Mockito 5.4.0 from annotations
// in church_admin/test/src/services/notifications/notifications_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:church_admin/church_admin.dart' as _i18;
import 'package:church_admin/src/services/notifications/notifications_storage.dart'
    as _i20;
import 'package:cloud_firestore/cloud_firestore.dart' as _i19;
import 'package:cloud_functions/cloud_functions.dart' as _i6;
import 'package:dio/dio.dart' as _i7;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_messaging/firebase_messaging.dart' as _i10;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i3;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i11;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i12;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i14;
import 'package:flutter_local_notifications/src/platform_specifics/ios/enums.dart'
    as _i16;
import 'package:flutter_local_notifications/src/types.dart' as _i17;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i13;
import 'package:hive_flutter/hive_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler_platform_interface/permission_handler_platform_interface.dart'
    as _i8;
import 'package:rxdart_ext/rxdart_ext.dart' as _i4;
import 'package:timezone/timezone.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationSettings_1 extends _i1.SmartFake
    implements _i3.NotificationSettings {
  _FakeNotificationSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_2<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_3<E> extends _i1.SmartFake implements _i5.Box<E> {
  _FakeBox_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpsCallable_4 extends _i1.SmartFake implements _i6.HttpsCallable {
  _FakeHttpsCallable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpsCallableResult_5<T> extends _i1.SmartFake
    implements _i6.HttpsCallableResult<T> {
  _FakeHttpsCallableResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6<T> extends _i1.SmartFake implements _i7.Response<T> {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PermissionHandlerPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class PermissionHandlerPlatform_ extends _i1.Mock
    implements _i8.PermissionHandlerPlatform {
  @override
  _i9.Future<_i8.PermissionStatus> checkPermissionStatus(
          _i8.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissionStatus,
          [permission],
        ),
        returnValue:
            _i9.Future<_i8.PermissionStatus>.value(_i8.PermissionStatus.denied),
        returnValueForMissingStub:
            _i9.Future<_i8.PermissionStatus>.value(_i8.PermissionStatus.denied),
      ) as _i9.Future<_i8.PermissionStatus>);
  @override
  _i9.Future<_i8.ServiceStatus> checkServiceStatus(
          _i8.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkServiceStatus,
          [permission],
        ),
        returnValue:
            _i9.Future<_i8.ServiceStatus>.value(_i8.ServiceStatus.disabled),
        returnValueForMissingStub:
            _i9.Future<_i8.ServiceStatus>.value(_i8.ServiceStatus.disabled),
      ) as _i9.Future<_i8.ServiceStatus>);
  @override
  _i9.Future<bool> openAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAppSettings,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
  @override
  _i9.Future<Map<_i8.Permission, _i8.PermissionStatus>> requestPermissions(
          List<_i8.Permission>? permissions) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [permissions],
        ),
        returnValue:
            _i9.Future<Map<_i8.Permission, _i8.PermissionStatus>>.value(
                <_i8.Permission, _i8.PermissionStatus>{}),
        returnValueForMissingStub:
            _i9.Future<Map<_i8.Permission, _i8.PermissionStatus>>.value(
                <_i8.Permission, _i8.PermissionStatus>{}),
      ) as _i9.Future<Map<_i8.Permission, _i8.PermissionStatus>>);
  @override
  _i9.Future<bool> shouldShowRequestPermissionRationale(
          _i8.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldShowRequestPermissionRationale,
          [permission],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i10.FirebaseMessaging {
  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
        returnValueForMissingStub: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);
  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isAutoInitEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoInitEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i9.Stream<String> get onTokenRefresh => (super.noSuchMethod(
        Invocation.getter(#onTokenRefresh),
        returnValue: _i9.Stream<String>.empty(),
        returnValueForMissingStub: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);
  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  _i9.Future<_i3.RemoteMessage?> getInitialMessage() => (super.noSuchMethod(
        Invocation.method(
          #getInitialMessage,
          [],
        ),
        returnValue: _i9.Future<_i3.RemoteMessage?>.value(),
        returnValueForMissingStub: _i9.Future<_i3.RemoteMessage?>.value(),
      ) as _i9.Future<_i3.RemoteMessage?>);
  @override
  _i9.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<String?> getAPNSToken() => (super.noSuchMethod(
        Invocation.method(
          #getAPNSToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
        returnValueForMissingStub: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);
  @override
  _i9.Future<String?> getToken({String? vapidKey}) => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
          {#vapidKey: vapidKey},
        ),
        returnValue: _i9.Future<String?>.value(),
        returnValueForMissingStub: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);
  @override
  _i9.Future<bool> isSupported() => (super.noSuchMethod(
        Invocation.method(
          #isSupported,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
  @override
  _i9.Future<_i3.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationSettings,
          [],
        ),
        returnValue: _i9.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #getNotificationSettings,
            [],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #getNotificationSettings,
            [],
          ),
        )),
      ) as _i9.Future<_i3.NotificationSettings>);
  @override
  _i9.Future<_i3.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
          {
            #alert: alert,
            #announcement: announcement,
            #badge: badge,
            #carPlay: carPlay,
            #criticalAlert: criticalAlert,
            #provisional: provisional,
            #sound: sound,
          },
        ),
        returnValue: _i9.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #requestPermission,
            [],
            {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
            },
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i3.NotificationSettings>.value(
            _FakeNotificationSettings_1(
          this,
          Invocation.method(
            #requestPermission,
            [],
            {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
            },
          ),
        )),
      ) as _i9.Future<_i3.NotificationSettings>);
  @override
  _i9.Future<void> sendMessage({
    String? to,
    Map<String, String>? data,
    String? collapseKey,
    String? messageId,
    String? messageType,
    int? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #to: to,
            #data: data,
            #collapseKey: collapseKey,
            #messageId: messageId,
            #messageType: messageType,
            #ttl: ttl,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> setAutoInitEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAutoInitEnabled,
          [enabled],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDeliveryMetricsExportToBigQuery,
          [enabled],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setForegroundNotificationPresentationOptions,
          [],
          {
            #alert: alert,
            #badge: badge,
            #sound: sound,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> subscribeToTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToTopic,
          [topic],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> unsubscribeFromTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromTopic,
          [topic],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [NotificationSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationSettings extends _i1.Mock
    implements _i3.NotificationSettings {
  @override
  _i3.AppleNotificationSetting get alert => (super.noSuchMethod(
        Invocation.getter(#alert),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get announcement => (super.noSuchMethod(
        Invocation.getter(#announcement),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AuthorizationStatus get authorizationStatus => (super.noSuchMethod(
        Invocation.getter(#authorizationStatus),
        returnValue: _i3.AuthorizationStatus.authorized,
        returnValueForMissingStub: _i3.AuthorizationStatus.authorized,
      ) as _i3.AuthorizationStatus);
  @override
  _i3.AppleNotificationSetting get timeSensitive => (super.noSuchMethod(
        Invocation.getter(#timeSensitive),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get criticalAlert => (super.noSuchMethod(
        Invocation.getter(#criticalAlert),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get badge => (super.noSuchMethod(
        Invocation.getter(#badge),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get carPlay => (super.noSuchMethod(
        Invocation.getter(#carPlay),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get lockScreen => (super.noSuchMethod(
        Invocation.getter(#lockScreen),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleNotificationSetting get notificationCenter => (super.noSuchMethod(
        Invocation.getter(#notificationCenter),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
  @override
  _i3.AppleShowPreviewSetting get showPreviews => (super.noSuchMethod(
        Invocation.getter(#showPreviews),
        returnValue: _i3.AppleShowPreviewSetting.always,
        returnValueForMissingStub: _i3.AppleShowPreviewSetting.always,
      ) as _i3.AppleShowPreviewSetting);
  @override
  _i3.AppleNotificationSetting get sound => (super.noSuchMethod(
        Invocation.getter(#sound),
        returnValue: _i3.AppleNotificationSetting.disabled,
        returnValueForMissingStub: _i3.AppleNotificationSetting.disabled,
      ) as _i3.AppleNotificationSetting);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i11.FlutterLocalNotificationsPlugin {
  @override
  _i9.Future<bool?> initialize(
    _i12.InitializationSettings? initializationSettings, {
    _i13.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i13.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i9.Future<bool?>.value(),
        returnValueForMissingStub: _i9.Future<bool?>.value(),
      ) as _i9.Future<bool?>);
  @override
  _i9.Future<_i13.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i9.Future<_i13.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i9.Future<_i13.NotificationAppLaunchDetails?>.value(),
          ) as _i9.Future<_i13.NotificationAppLaunchDetails?>);
  @override
  _i9.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i14.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> schedule(
    int? id,
    String? title,
    String? body,
    DateTime? scheduledDate,
    _i14.NotificationDetails? notificationDetails, {
    String? payload,
    bool? androidAllowWhileIdle = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #schedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #payload: payload,
            #androidAllowWhileIdle: androidAllowWhileIdle,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i15.TZDateTime? scheduledDate,
    _i14.NotificationDetails? notificationDetails, {
    required _i16.UILocalNotificationDateInterpretation?
        uiLocalNotificationDateInterpretation,
    required bool? androidAllowWhileIdle,
    String? payload,
    _i17.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #uiLocalNotificationDateInterpretation:
                uiLocalNotificationDateInterpretation,
            #androidAllowWhileIdle: androidAllowWhileIdle,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i13.RepeatInterval? repeatInterval,
    _i14.NotificationDetails? notificationDetails, {
    String? payload,
    bool? androidAllowWhileIdle = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #payload: payload,
            #androidAllowWhileIdle: androidAllowWhileIdle,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> showDailyAtTime(
    int? id,
    String? title,
    String? body,
    _i17.Time? notificationTime,
    _i14.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDailyAtTime,
          [
            id,
            title,
            body,
            notificationTime,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> showWeeklyAtDayAndTime(
    int? id,
    String? title,
    String? body,
    _i17.Day? day,
    _i17.Time? notificationTime,
    _i14.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showWeeklyAtDayAndTime,
          [
            id,
            title,
            body,
            day,
            notificationTime,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<List<_i13.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i9.Future<List<_i13.PendingNotificationRequest>>.value(
                    <_i13.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i9.Future<List<_i13.PendingNotificationRequest>>.value(
                    <_i13.PendingNotificationRequest>[]),
          ) as _i9.Future<List<_i13.PendingNotificationRequest>>);
  @override
  _i9.Future<List<_i13.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i9.Future<List<_i13.ActiveNotification>>.value(
            <_i13.ActiveNotification>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i13.ActiveNotification>>.value(
                <_i13.ActiveNotification>[]),
      ) as _i9.Future<List<_i13.ActiveNotification>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i18.AuthService {
  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i4.ValueStream<_i18.User?> get userStream => (super.noSuchMethod(
        Invocation.getter(#userStream),
        returnValue: _FakeValueStream_2<_i18.User?>(
          this,
          Invocation.getter(#userStream),
        ),
        returnValueForMissingStub: _FakeValueStream_2<_i18.User?>(
          this,
          Invocation.getter(#userStream),
        ),
      ) as _i4.ValueStream<_i18.User?>);
  @override
  _i4.ValueStream<String?> get idTokenStream => (super.noSuchMethod(
        Invocation.getter(#idTokenStream),
        returnValue: _FakeValueStream_2<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
        returnValueForMissingStub: _FakeValueStream_2<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
      ) as _i4.ValueStream<String?>);
  @override
  _i9.Future<_i18.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i9.Future<_i18.User?>.value(),
        returnValueForMissingStub: _i9.Future<_i18.User?>.value(),
      ) as _i9.Future<_i18.User?>);
  @override
  _i9.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [UserSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsService extends _i1.Mock
    implements _i18.UserSettingsService {
  @override
  _i5.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_3<dynamic>(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeBox_3<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i5.Box<dynamic>);
  @override
  bool get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get greatFeastTheme => (super.noSuchMethod(
        Invocation.getter(#greatFeastTheme),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i9.Future<void> setDarkTheme(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDarkTheme,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> setRegisteredFCMToken(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setRegisteredFCMToken,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> setGreatFeastTheme(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setGreatFeastTheme,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  String? getSecondLineFor(Type? t) => (super.noSuchMethod(
        Invocation.method(
          #getSecondLineFor,
          [t],
        ),
        returnValueForMissingStub: null,
      ) as String?);
  @override
  _i9.Future<void> setSecondLineFor(
    Type? t,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSecondLineFor,
          [
            t,
            value,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [CAFunctionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCAFunctionsService extends _i1.Mock
    implements _i18.CAFunctionsService {
  @override
  _i6.HttpsCallable httpsCallable(
    String? functionName, {
    _i6.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #httpsCallable,
          [functionName],
          {#options: options},
        ),
        returnValue: _FakeHttpsCallable_4(
          this,
          Invocation.method(
            #httpsCallable,
            [functionName],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeHttpsCallable_4(
          this,
          Invocation.method(
            #httpsCallable,
            [functionName],
            {#options: options},
          ),
        ),
      ) as _i6.HttpsCallable);
  @override
  _i9.Future<String> getDownloadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadUrl,
          [
            table,
            id,
          ],
          {#contentType: contentType},
        ),
        returnValue: _i9.Future<String>.value(''),
        returnValueForMissingStub: _i9.Future<String>.value(''),
      ) as _i9.Future<String>);
  @override
  _i9.Future<String> getUploadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadUrl,
          [
            table,
            id,
          ],
          {#contentType: contentType},
        ),
        returnValue: _i9.Future<String>.value(''),
        returnValueForMissingStub: _i9.Future<String>.value(''),
      ) as _i9.Future<String>);
  @override
  _i9.Future<_i6.HttpsCallableResult<dynamic>> recoverDocument(
    _i19.DocumentReference<Map<String, dynamic>>? deletedDoc, {
    bool? keepBackup = true,
    bool? nested = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverDocument,
          [deletedDoc],
          {
            #keepBackup: keepBackup,
            #nested: nested,
          },
        ),
        returnValue: _i9.Future<_i6.HttpsCallableResult<dynamic>>.value(
            _FakeHttpsCallableResult_5<dynamic>(
          this,
          Invocation.method(
            #recoverDocument,
            [deletedDoc],
            {
              #keepBackup: keepBackup,
              #nested: nested,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.HttpsCallableResult<dynamic>>.value(
                _FakeHttpsCallableResult_5<dynamic>(
          this,
          Invocation.method(
            #recoverDocument,
            [deletedDoc],
            {
              #keepBackup: keepBackup,
              #nested: nested,
            },
          ),
        )),
      ) as _i9.Future<_i6.HttpsCallableResult<dynamic>>);
  @override
  _i9.Future<String?> getAddressFromLocation(_i18.Point? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressFromLocation,
          [location],
        ),
        returnValue: _i9.Future<String?>.value(),
        returnValueForMissingStub: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);
  @override
  _i9.Future<_i7.Response<dynamic>> uploadPhoto({
    required String? url,
    required _i9.Stream<List<int>>? fileStream,
    String? contentType,
    int? fileLength,
    void Function(
      int,
      int,
    )? onSendProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [],
          {
            #url: url,
            #fileStream: fileStream,
            #contentType: contentType,
            #fileLength: fileLength,
            #onSendProgress: onSendProgress,
          },
        ),
        returnValue:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_6<dynamic>(
          this,
          Invocation.method(
            #uploadPhoto,
            [],
            {
              #url: url,
              #fileStream: fileStream,
              #contentType: contentType,
              #fileLength: fileLength,
              #onSendProgress: onSendProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_6<dynamic>(
          this,
          Invocation.method(
            #uploadPhoto,
            [],
            {
              #url: url,
              #fileStream: fileStream,
              #contentType: contentType,
              #fileLength: fileLength,
              #onSendProgress: onSendProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<dynamic>>);
  @override
  _i9.Future<bool> checkHasuraHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHasuraHealth,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
  @override
  _i9.Future<_i6.HttpsCallableResult<dynamic>> registerFCMToken(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerFCMToken,
          [token],
        ),
        returnValue: _i9.Future<_i6.HttpsCallableResult<dynamic>>.value(
            _FakeHttpsCallableResult_5<dynamic>(
          this,
          Invocation.method(
            #registerFCMToken,
            [token],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.HttpsCallableResult<dynamic>>.value(
                _FakeHttpsCallableResult_5<dynamic>(
          this,
          Invocation.method(
            #registerFCMToken,
            [token],
          ),
        )),
      ) as _i9.Future<_i6.HttpsCallableResult<dynamic>>);
}

/// A class which mocks [NotificationsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsStorage extends _i1.Mock
    implements _i20.NotificationsStorage {
  @override
  _i9.Future<void> writeNotification(_i18.Notification? notification) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeNotification,
          [notification],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<_i18.Notification?> readNotification(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #readNotification,
          [notificationId],
        ),
        returnValue: _i9.Future<_i18.Notification?>.value(),
        returnValueForMissingStub: _i9.Future<_i18.Notification?>.value(),
      ) as _i9.Future<_i18.Notification?>);
}
