query analyzeUserAttendance(
  $dateFrom: date!
  $dateTo: date!
  $personId: uuid!
  $userId: uuid!
  $groupsIds: [uuid!]
  $classesIds: [uuid!]
  $servicesIds: [uuid!]
) {
  authUsersDataByPk(uid: $userId) {
    uid
    name
    servicesHistory: adminOn(
      where: { service: { id: { _in: $servicesIds } } }
      distinctOn: adminOnService
    ) {
      permissionId
      service {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: true }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
    classesHistory: adminOn(
      where: { classes: { id: { _in: $classesIds } } }
      distinctOn: adminOnService
    ) {
      permissionId
      classes(where: { id: { _in: $classesIds } }, distinctOn: id) {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: true }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
    groupsHistory: adminOn(
      where: { group: { id: { _in: $groupsIds } } }
      distinctOn: adminOnGroup
    ) {
      permissionId
      group {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: true }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
  }
}
