subscription getUserInfoStream($uid: uuid!) {
  authUsersDataByPk(uid: $uid) {
    uid
    name
    photoUpdatedAt
    email
    permissions {
      permission
    }
    person {
      id
      name
      address
      geolocation
      mainPhone
      otherPhones
      birthdate
      gender
      isShammas
      shammasLevel {
        id
        name
        order
      }
      schoolId
      collegeId
      churchId
      fatherId
      isStudent
      jobId
      jobDescription
      qualificationId
      personTypeId
      stateId
      isServant
      notes
      familyId
      storeId
      studyYearId
      color
      photoUpdatedAt
      lastKodas
      lastConfession
    }
  }
}

subscription watchUser($uid: uuid!) {
  authUsersDataByPk(uid: $uid) {
    uid
    name
    email
    photoUpdatedAt
    lastEdit
    permissions {
      permission
    }
    person {
      id
      name
      color
      photoUpdatedAt
    }
    adminOn(
      orderBy: [
        { area: { name: ASC_NULLS_LAST } }
        { service: { studyYearFrom: ASC, studyYearTo: ASC } }
        { serviceStudyYear: ASC }
        { serviceGender: DESC_NULLS_FIRST }
        { service: { name: ASC_NULLS_LAST } }
        { group: { name: ASC_NULLS_LAST } }
      ]
    ) {
      permissionId
      area {
        id
        name
        color
        photoUpdatedAt
      }
      areaAllowEdit
      areaAdminOnUsers
      service {
        id
        name
        color
        photoUpdatedAt
      }
      serviceStudyYearData {
        name
        order
      }
      serviceGender
      serviceAllowEdit
      serviceAdminOnUsers
      classes(orderBy: { name: ASC }) {
        id
        name
        color
        photoUpdatedAt
      }
      group {
        id
        name
        color
        photoUpdatedAt
      }
      groupAllowEdit
      groupAdminOnUsers
    }
  }
}

subscription userEditHistory(
  $userId: uuid!
  $where: [HistoryEditHistoryBoolExp!] = {}
  $limit: Int = 200
) {
  historyEditHistory(
    where: {
      _and: [
        { table: { _eq: "users" } }
        { recordId: { _eq: $userId } }
        { _and: $where }
      ]
    }
    limit: $limit
    orderBy: { time: DESC }
  ) {
    time
    user {
      uid
      name
      photoUpdatedAt
    }
  }
}
