mutation insertPersonLastConfession($personId: uuid!, $lastConfession: date!) {
  insertHistoryConfessionHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastConfession }
        onConflict: { constraint: attendance_days_pkey, update_columns: day }
      }
    }
    onConflict: { constraint: confession_history_dayID_personID_key }
  ) {
    person {
      id
      name
      color
      photoUpdatedAt
    }
  }
}

mutation insertPersonLastKodas($personId: uuid!, $lastKodas: date!) {
  insertHistoryKodasHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastKodas }
        onConflict: { constraint: attendance_days_pkey, update_columns: day }
      }
    }
    onConflict: { constraint: kodas_history_dayID_personID_key }
  ) {
    person {
      id
      name
      color
      photoUpdatedAt
    }
  }
}

mutation insertPersonLastCall($personId: uuid!, $lastCall: timestamptz!) {
  insertHistoryCallHistoryOne(
    object: { personId: $personId, time: $lastCall }
  ) {
    person {
      id
      name
      color
      photoUpdatedAt
    }
  }
}

mutation insertPersonLastVisit($personId: uuid!, $lastVisit: timestamptz!) {
  insertHistoryVisitHistoryOne(
    object: { personId: $personId, time: $lastVisit }
  ) {
    person {
      id
      name
      color
      photoUpdatedAt
    }
  }
}

mutation updatePersonSpiritData(
  $personId: uuid!
  $lastConfession: date!
  $lastKodas: date!
) {
  insertHistoryConfessionHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastConfession }
        onConflict: { constraint: attendance_days_pkey, update_columns: day }
      }
    }
    onConflict: { constraint: confession_history_dayID_personID_key }
  ) {
    person {
      id
      name
      color
      photoUpdatedAt
    }
  }
  insertHistoryKodasHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastKodas }
        onConflict: { constraint: attendance_days_pkey, update_columns: day }
      }
    }
    onConflict: { constraint: kodas_history_dayID_personID_key }
  ) {
    person {
      id
      name
      color
      photoUpdatedAt
    }
  }
}
