query getPersonsAttendanceWarning($dateFilter: date!) {
  persons(
    where: { attendanceHistory: { _not: { dayId: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsKodasWarning($dateFilter: date!) {
  persons(
    where: { kodasHistory: { _not: { dayId: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsConfessionWarning($dateFilter: date!) {
  persons(
    where: { confessionHistory: { _not: { dayId: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsVisitWarning($dateFilter: timestamptz!) {
  persons(
    where: { visitHistory: { _not: { time: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsBirthday($dateFilter: String!) {
  persons(where: { birthday: { _eq: $dateFilter } }, limit: 25) {
    name
  }
}

query getMorePersonData(
  $id: uuid!
  $areasAfter: String = ""
  $classesAfter: String = ""
  $groupsAfter: String = ""
  $servicesAfter: String = ""
) {
  personsByPk(id: $id) {
    id
    name
    areas(orderBy: { name: ASC }, where: { name: { _gt: $areasAfter } }) {
      id
      name
      color
      photoUpdatedAt
    }
    classes(orderBy: { name: ASC }, where: { name: { _gt: $classesAfter } }) {
      id
      name
      color
      photoUpdatedAt

      attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
        aggregate {
          max {
            dayId
          }
        }
      }
    }
    groups(
      orderBy: { group: { name: ASC } }
      where: { group: { name: { _gt: $groupsAfter } } }
    ) {
      group {
        id
        name
        color
        photoUpdatedAt

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              dayId
            }
          }
        }
      }
    }
    services(
      orderBy: { service: { name: ASC } }
      where: { service: { name: { _gt: $servicesAfter } } }
    ) {
      service {
        id
        name
        color
        photoUpdatedAt

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              dayId
            }
          }
        }
      }
    }
  }
}

query personsGeolocations($conditions: PersonsBoolExp) {
  persons(where: $conditions) {
    id
    name

    geolocation
    areas {
      id
      name
      color

      bounds
    }
    streets {
      id
      name
      color

      line
    }
    family {
      id
      name
      color

      geolocation
    }
  }
}

query analyzePerson(
  $dateFrom: date!
  $dateTo: date!
  $timeFrom: timestamptz!
  $timeTo: timestamptz!
  $personId: uuid!
  $groupsIds: [uuid!] = []
  $classesIds: [uuid!] = []
  $servicesIds: [uuid!] = []
  $callHistory: Boolean! = false
  $visitHistory: Boolean! = false
  $editHistory: Boolean! = false
  $confessionHistory: Boolean! = false
  $kodasHistory: Boolean! = false
) {
  personsByPk(id: $personId) {
    id
    name
    callHistoryAggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } })
      @include(if: $callHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    visitHistoryAggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } })
      @include(if: $visitHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    editHistoryAggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } })
      @include(if: $editHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    kodasHistoryAggregate(where: { dayId: { _gte: $dateFrom, _lte: $dateTo } })
      @include(if: $kodasHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    confessionHistoryAggregate(
      where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
    ) @include(if: $confessionHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    services(where: { serviceId: { _in: $servicesIds } }) {
      service {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: false }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
    classes(where: { id: { _in: $classesIds } }) {
      id
      name
      color
      attendanceHistoryAggregate(
        where: {
          dayId: { _gte: $dateFrom, _lte: $dateTo }
          personId: { _eq: $personId }
          asAdmin: { _eq: false }
        }
      ) {
        aggregate {
          count
          max {
            dayId
          }
        }
        nodes {
          dayId
        }
      }
      attendanceDaysConstraintsAggregate(
        where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
      ) {
        aggregate {
          count
        }
        nodes {
          dayId
        }
      }
    }
    groups(where: { groupId: { _in: $groupsIds } }) {
      group {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: false }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
  }
}

query getPersonClassesAndGroups($id: uuid!) {
  personsByPk(id: $id) {
    id
    name
    classes(orderBy: { name: ASC }) {
      id
      name
      color
      photoUpdatedAt
      service {
        id
        name
        color
        photoUpdatedAt
      }
    }
    groups(orderBy: { group: { name: ASC } }) {
      group {
        id
        name
        color
        photoUpdatedAt
        service {
          id
          name
          color
          photoUpdatedAt
        }
      }
    }
  }
}
