query getPersonsAttendanceWarning($dateFilter: date!) {
  persons(
    where: { attendanceHistory: { _not: { dayId: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsKodasWarning($dateFilter: date!) {
  persons(
    where: { kodasHistory: { _not: { dayId: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsConfessionWarning($dateFilter: date!) {
  persons(
    where: { confessionHistory: { _not: { dayId: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsVisitWarning($dateFilter: timestamptz!) {
  persons(
    where: { visitHistory: { _not: { time: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsBirthday($dateFilter: String!) {
  persons(where: { birthday: { _eq: $dateFilter } }, limit: 25) {
    name
  }
}

query getMorePersonData(
  $id: uuid!
  $areasAfter: String = ""
  $classesAfter: String = ""
  $groupsAfter: String = ""
  $servicesAfter: String = ""
) {
  persons_by_pk(id: $id) {
    id
    name
    areas(order_by: { name: asc }, where: { name: { _gt: $areasAfter } }) {
      id
      name
      color
      photoUpdatedAt
    }
    classes(order_by: { name: asc }, where: { name: { _gt: $classesAfter } }) {
      id
      name
      color
      photoUpdatedAt

      attendanceHistory_aggregate(where: { personId: { _eq: $personId } }) {
        aggregate {
          max {
            dayId
          }
        }
      }
    }
    groups(
      order_by: { group: { name: asc } }
      where: { group: { name: { _gt: $groupsAfter } } }
    ) {
      group {
        id
        name
        color
        photoUpdatedAt

        attendanceHistory_aggregate(where: { personId: { _eq: $personId } }) {
          aggregate {
            max {
              dayId
            }
          }
        }
      }
    }
    services(
      order_by: { service: { name: asc } }
      where: { service: { name: { _gt: $servicesAfter } } }
    ) {
      service {
        id
        name
        color
        photoUpdatedAt

        attendanceHistory_aggregate(where: { personId: { _eq: $personId } }) {
          aggregate {
            max {
              dayId
            }
          }
        }
      }
    }
  }
}

query personsGeolocations($conditions: persons_bool_exp) {
  persons(where: $conditions) {
    id
    name

    geolocation
    areas {
      id
      name
      color

      bounds
    }
    streets {
      id
      name
      color

      line
    }
    family {
      id
      name
      color

      geolocation
    }
  }
}

query analyzePersonAttendance(
  $dateFrom: date!
  $dateTo: date!
  $personId: uuid!
  $groupsIds: [uuid!]
  $classesIds: [uuid!]
  $servicesIds: [uuid!]
) {
  persons_by_pk(id: $personId) {
    id
    name
    kodasHistory_aggregate(
      where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
    ) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    confessionHistory_aggregate(
      where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
    ) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    services(where: { serviceId: { _in: $servicesIds } }) {
      service {
        id
        name
        color
        attendanceHistory_aggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraints_aggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
    classes(where: { id: { _in: $classesIds } }) {
      id
      name
      color
      attendanceHistory_aggregate(
        where: {
          dayId: { _gte: $dateFrom, _lte: $dateTo }
          personId: { _eq: $personId }
        }
      ) {
        aggregate {
          count
          max {
            dayId
          }
        }
        nodes {
          dayId
        }
      }
      attendanceDaysConstraints_aggregate(
        where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
      ) {
        aggregate {
          count
        }
        nodes {
          dayId
        }
      }
    }
    groups(where: { groupId: { _in: $groupsIds } }) {
      group {
        id
        name
        color
        attendanceHistory_aggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraints_aggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
  }
}

query analyzePersonServicing(
  $timeFrom: timestamptz!
  $timeTo: timestamptz!
  $personId: uuid!
) {
  persons_by_pk(id: $personId) {
    id
    name
    callHistory_aggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } }) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    visitHistory_aggregate(
      where: { time: { _gte: $timeFrom, _lte: $timeTo } }
    ) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
  }
}

query getPersonClassesAndGroups($id: uuid!) {
  persons_by_pk(id: $id) {
    id
    name
    classes(order_by: { name: asc }) {
      id
      name
      color
      photoUpdatedAt
      service {
        id
        name
        color
        photoUpdatedAt
      }
    }
    groups(order_by: { group: { name: asc } }) {
      group {
        id
        name
        color
        photoUpdatedAt
        service {
          id
          name
          color
          photoUpdatedAt
        }
      }
    }
  }
}
