subscription getPersonsStream(
  $addWhere: [persons_bool_exp!] = {}
  $limit: Int = 200
) {
  persons(where: { _and: $addWhere }, order_by: { name: asc }, limit: $limit) {
    id
    name
    color
    photoUpdatedAt
  }
}

subscription watchPerson($id: uuid!) {
  persons_by_pk(id: $id) {
    id
    name
    color
    photoUpdatedAt
    address
    birthdate
    areas(limit: 6, order_by: { name: asc }) {
      id
      name
      color
      photoUpdatedAt
    }
    classes(limit: 6, order_by: { name: asc }) {
      id
      name
      color
      photoUpdatedAt

      attendanceHistory_aggregate(where: { personId: { _eq: $id } }) {
        aggregate {
          max {
            time
          }
        }
      }
    }
    church {
      id
      name
    }
    college {
      id
      name
    }
    family {
      id
      name
      color
      photoUpdatedAt
    }
    father {
      id
      name
      church {
        id
        name
      }
    }
    gender
    geolocation
    groups(limit: 6, order_by: { group: { name: asc } }) {
      group {
        id
        name
        color
        photoUpdatedAt

        attendanceHistory_aggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    isServant
    isShammas
    isStudent
    job {
      id
      name
    }
    jobDescription
    lastCall
    lastConfession
    lastEdit
    lastKodas
    lastVisit
    mainPhone
    notes
    otherPhones
    personType {
      id
      name
    }
    qualification {
      id
      name
    }
    school {
      id
      name
    }
    services(limit: 6, order_by: { service: { name: asc } }) {
      service {
        id
        name
        color
        photoUpdatedAt

        attendanceHistory_aggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    shammasLevel {
      id
      name
      order
    }
    state {
      id
      color
      name
    }
    streets {
      id
      name
      color
      photoUpdatedAt
    }
    studyYear {
      name
      order
    }
    tags(order_by: { tag: { name: asc } }) {
      tag {
        id
        name
        color
      }
    }
    uid
  }
}

subscription callHistory(
  $personId: uuid!
  $addWhere: [history_call_history_bool_exp!] = {}
  $limit: Int = 200
) {
  history_call_history(
    where: { _and: [{ personId: { _eq: $personId } }, { _and: $addWhere }] }
    limit: $limit
    order_by: { time: desc }
  ) {
    time
    user {
      uid
      name
      photoUpdatedAt
    }
  }
}

subscription visitHistory(
  $personId: uuid!
  $addWhere: [history_visit_history_bool_exp!] = {}
  $limit: Int = 200
) {
  history_visit_history(
    where: { _and: [{ personId: { _eq: $personId } }, { _and: $addWhere }] }
    limit: $limit
    order_by: { time: desc }
  ) {
    time
    user {
      uid
      name
      photoUpdatedAt
    }
  }
}

subscription confessionHistory(
  $personId: uuid!
  $addWhere: [history_confession_history_bool_exp!] = {}
  $limit: Int = 200
) {
  history_confession_history(
    where: { _and: [{ personId: { _eq: $personId } }, { _and: $addWhere }] }
    limit: $limit
    order_by: { time: desc }
  ) {
    time
    user {
      uid
      name
      photoUpdatedAt
    }
  }
}

subscription kodasHistory(
  $personId: uuid!
  $addWhere: [history_kodas_history_bool_exp!] = {}
  $limit: Int = 200
) {
  history_kodas_history(
    where: { _and: [{ personId: { _eq: $personId } }, { _and: $addWhere }] }
    limit: $limit
    order_by: { time: desc }
  ) {
    time
    user {
      uid
      name
      photoUpdatedAt
    }
  }
}

subscription editHistory(
  $personId: uuid!
  $addWhere: [history_edit_history_bool_exp!] = {}
  $limit: Int = 200
) {
  history_edit_history(
    where: {
      _and: [
        { table: { _eq: "persons" } }
        { recordId: { _eq: $personId } }
        { _and: $addWhere }
      ]
    }
    limit: $limit
    order_by: { time: desc }
  ) {
    time
    user {
      uid
      name
      photoUpdatedAt
    }
  }
}
