#!/usr/bin/env bash
# Compiles the suite once instead of once per file (flutter/flutter#90225).
# Writes test/test_bundle.dart and prints the files it could not bundle,
# so CI can run: flutter test test/test_bundle.dart $(scripts/generate_test_bundle.sh)
# An async main cannot run inside group(), so those files stay separate.
set -euo pipefail

cd "$(dirname "$0")/.."

out=test/test_bundle.dart
bundled=()
unbundled=()
while IFS= read -r f; do
  if grep -q 'Future<void> main() async' "$f"; then
    unbundled+=("$f")
  else
    bundled+=("$f")
  fi
done < <(find test -name '*_test.dart' | LC_ALL=C sort)

{
  echo '// GENERATED by scripts/generate_test_bundle.sh. Do not edit.'
  echo '// ignore_for_file: type=lint'
  echo
  echo "import 'package:flutter_test/flutter_test.dart';"
  echo
  for i in "${!bundled[@]}"; do
    echo "import '${bundled[$i]#test/}' as t$i;"
  done
  echo
  echo 'void main() {'
  for i in "${!bundled[@]}"; do
    f=${bundled[$i]}
    echo "  group('${f#test/}', t$i.main);"
  done
  echo '}'
} > "$out"

echo "$out: ${#bundled[@]} bundled, ${#unbundled[@]} unbundled" >&2
((${#unbundled[@]} == 0)) || printf '%s\n' "${unbundled[@]}"
