fragment Person on Persons {
  ...PersonNoPhoto
  photoUpdatedAt
  blurhash
}

fragment PersonNoPhoto on Persons {
  id
  name
  color
  userCanEdit
}

fragment FullPersonData on Persons {
  ...Person
  birthdate
  address {
    ...Address
  }
  classes(limit: 6, orderBy: { class: { name: ASC } }) {
    class {
      ...Class
    }
  }
  church {
    id
    name
  }
  college {
    id
    name
  }
  family {
    ...Family
  }
  father {
    id
    name
    church {
      id
      name
    }
  }
  gender
  groups(limit: 6, orderBy: { group: { name: ASC } }) {
    group {
      ...Group
    }
  }
  isServant
  isShammas
  isStudent
  job {
    id
    name
  }
  jobDescription
  lastCall {
    ...LatestCallHistory
  }
  lastConfession {
    ...LatestConfessionHistory
  }
  lastEdit {
    ...LatestEditHistory
  }
  lastKodas {
    ...LatestKodasHistory
  }
  lastVisit {
    ...LatestVisitHistory
  }
  mainPhone
  notes
  otherPhones
  personType {
    id
    name
  }
  qualification {
    id
    name
  }
  school {
    id
    name
  }
  services(limit: 6, orderBy: { service: { name: ASC } }) {
    service {
      ...ServiceWithStudyYears
    }
  }
  shammasLevel {
    id
    name
    order
  }
  state {
    id
    color
    name
  }
  studyYear {
    name
    order
  }
  hobbies(orderBy: { hobby: { name: ASC } }) {
    hobby {
      id
      name
      color
    }
  }
  tags(orderBy: { tag: { name: ASC } }) {
    tag {
      id
      name
      color
    }
  }
  uid
  user {
    uid
    name
    email
  }
}

fragment FullPersonDataWithAttendance on Persons {
  ...FullPersonData
  classes(limit: 6, orderBy: { class: { name: ASC } }) {
    class {
      ...Class

      attendanceHistoryAggregate(where: { personId: { _eq: $personId } }) {
        aggregate {
          max {
            time
          }
        }
      }
    }
  }
  groups(limit: 6, orderBy: { group: { name: ASC } }) {
    group {
      ...Group

      attendanceHistoryAggregate(where: { personId: { _eq: $personId } }) {
        aggregate {
          max {
            time
          }
        }
      }
    }
  }
  services(limit: 6, orderBy: { service: { name: ASC } }) {
    service {
      ...ServiceWithStudyYears

      attendanceHistoryAggregate(where: { personId: { _eq: $personId } }) {
        aggregate {
          max {
            time
          }
        }
      }
    }
  }
}
