subscription watchAllPersons(
  $where: [PersonsBoolExp!] = {}
  $orderBy: [PersonsOrderBy!] = { name: ASC }
  $limit: Int = 200
) {
  persons(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    ...Person
  }
}

subscription watchPersonsCount($where: [PersonsBoolExp!] = {}, $limit: Int) {
  personsAggregate(where: { _and: $where }, limit: $limit) {
    aggregate {
      count
    }
  }
}

subscription watchPerson(
  $id: uuid!
  $classesLimit: Int
  $groupsLimit: Int
  $servicesLimit: Int
) {
  personsByPk(id: $id) {
    ...Person
    nationalId
    address {
      ...Address
    }
    birthdate
    classes(limit: $classesLimit, orderBy: { class: { name: ASC } }) {
      class {
        ...Class

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    church {
      id
      name
    }
    college {
      id
      name
    }
    family {
      ...Family
    }
    father {
      id
      name
      church {
        id
        name
      }
    }
    gender
    groups(limit: $groupsLimit, orderBy: { group: { name: ASC } }) {
      group {
        ...Group

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    isServant
    servingChurch {
      id
      name
    }
    serviceType
    isShammas
    workStatus
    job {
      id
      name
    }
    jobDescription
    lastCall {
      ...LatestCallHistory
    }
    lastConfession {
      ...LatestConfessionHistory
    }
    lastEdit {
      ...LatestEditHistory
    }
    lastKodas {
      ...LatestKodasHistory
    }
    lastVisit {
      ...LatestVisitHistory
    }
    mainPhone
    notes
    otherPhones
    martialStatus
    personType {
      id
      name
    }
    qualification {
      id
      name
    }
    school {
      id
      name
    }
    services(limit: $servicesLimit, orderBy: { service: { name: ASC } }) {
      service {
        ...ServiceWithStudyYears

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    shammasLevel {
      id
      name
      order
    }
    state {
      id
      color
      name
    }
    studyYear {
      name
      order
    }
    hobbies(orderBy: { hobby: { name: ASC } }) {
      hobby {
        id
        name
        color
      }
    }
    tags(orderBy: { tag: { name: ASC } }) {
      tag {
        id
        name
        color
      }
    }
    uid
    user {
      uid
      name
      email
    }
  }
}

subscription personAttendance(
  $where: [HistoryAttendanceHistoryBoolExp!] = {}
  $orderBy: [HistoryAttendanceHistoryOrderBy!] = { time: DESC }
  $limit: Int! = 200
) {
  historyAttendanceHistory(
    where: { _and: $where }
    orderBy: $orderBy
    limit: $limit
  ) {
    ...AttendanceHistory
  }
}
