subscription watchAllChurches(
  $where: [ChurchesBoolExp!] = {}
  $orderBy: [ChurchesOrderBy!] = { name: ASC }
  $limit: Int = 25
) {
  churches(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
  }
}
