mutation deletePerson($personId: Uuid!) {
  deletePersonsByPk(id: $personId) {
    ...Person
  }
}

mutation updatePerson(
  $personId: Uuid!
  $newPerson: PersonsSetInput!
  $newGroups: [PersonsGroupsInsertInput!]! = []
  $deleteGroups: [Uuid!]
  $newServices: [PersonsServicesInsertInput!]! = []
  $deleteServices: [Uuid!]
  $newHobbies: [PersonsHobbiesInsertInput!]! = []
  $deleteHobbies: [Uuid!]
  $newTags: [PersonsTagsInsertInput!]! = []
  $deleteTags: [Uuid!]
  $lastConfession: Date
  $lastKodas: Date
  $lastCall: Timestamptz
  $lastVisit: Timestamptz
  $updatePersonsByPk: Boolean! = true
  $insertPersonsServices: Boolean! = true
  $insertPersonsGroups: Boolean! = true
  $insertPersonsHobbies: Boolean! = true
  $insertPersonsTags: Boolean! = true
  $deletePersonsTags: Boolean! = true
  $deletePersonsHobbies: Boolean! = true
  $deletePersonsGroups: Boolean! = true
  $deletePersonsServices: Boolean! = true
  $insertHistoryConfessionHistoryOne: Boolean! = true
  $insertHistoryKodasHistoryOne: Boolean! = true
  $insertHistoryCallHistoryOne: Boolean! = true
  $insertHistoryVisitHistoryOne: Boolean! = true
) {
  updatePersonsByPk(pkColumns: { id: $personId }, _set: $newPerson)
    @include(if: $updatePersonsByPk) {
    ...Person
  }

  insertPersonsServices(objects: $newServices)
    @include(if: $insertPersonsServices) {
    affectedRows
  }
  insertPersonsGroups(objects: $newGroups) @include(if: $insertPersonsGroups) {
    affectedRows
  }
  insertPersonsHobbies(objects: $newHobbies)
    @include(if: $insertPersonsHobbies) {
    affectedRows
  }
  insertPersonsTags(objects: $newTags) @include(if: $insertPersonsTags) {
    affectedRows
  }

  deletePersonsTags(
    where: { personId: { _eq: $personId }, tagId: { _in: $deleteTags } }
  ) @include(if: $deletePersonsTags) {
    affectedRows
  }
  deletePersonsHobbies(
    where: { personId: { _eq: $personId }, hobbyId: { _in: $deleteHobbies } }
  ) @include(if: $deletePersonsHobbies) {
    affectedRows
  }
  deletePersonsGroups(
    where: { personId: { _eq: $personId }, groupId: { _in: $deleteGroups } }
  ) @include(if: $deletePersonsGroups) {
    affectedRows
  }
  deletePersonsServices(
    where: { personId: { _eq: $personId }, serviceId: { _in: $deleteServices } }
  ) @include(if: $deletePersonsServices) {
    affectedRows
  }

  insertHistoryConfessionHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastConfession }
        onConflict: { constraint: attendanceDaysPkey, updateColumns: day }
      }
    }
    onConflict: { constraint: confessionHistoryDayIdPersonIdKey }
  ) @include(if: $insertHistoryConfessionHistoryOne) {
    person {
      id
      name
    }
  }

  insertHistoryKodasHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastKodas }
        onConflict: { constraint: attendanceDaysPkey, updateColumns: day }
      }
    }
    onConflict: { constraint: kodasHistoryDayIdPersonIdKey }
  ) @include(if: $insertHistoryKodasHistoryOne) {
    person {
      id
      name
    }
  }

  insertHistoryCallHistoryOne(object: { personId: $personId, time: $lastCall })
    @include(if: $insertHistoryCallHistoryOne) {
    person {
      id
      name
    }
  }

  insertHistoryVisitHistoryOne(
    object: { table: "persons", recordId: $personId, time: $lastVisit }
  ) @include(if: $insertHistoryVisitHistoryOne) {
    visitId
  }
}

mutation insertPerson($newPerson: PersonsInsertInput!) {
  insertPersonsOne(object: $newPerson) {
    ...Person
  }
}

mutation updatePersonSpiritData(
  $personId: Uuid!
  $lastConfession: Date!
  $lastKodas: Date!
) {
  insertHistoryConfessionHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastConfession }
        onConflict: { constraint: attendanceDaysPkey, updateColumns: day }
      }
    }
    onConflict: { constraint: confessionHistoryDayIdPersonIdKey }
  ) {
    person {
      ...Person
    }
  }
  insertHistoryKodasHistoryOne(
    object: {
      personId: $personId
      day: {
        data: { day: $lastKodas }
        onConflict: { constraint: attendanceDaysPkey, updateColumns: day }
      }
    }
    onConflict: { constraint: kodasHistoryDayIdPersonIdKey }
  ) {
    person {
      ...Person
    }
  }
}
