subscription watchAllShammasLevels(
  $where: [ShammasLevelsBoolExp!] = {}
  $orderBy: [ShammasLevelsOrderBy!] = { order: ASC }
  $limit: Int = 25
) {
  shammasLevels(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    order
    name
  }
}
