mutation updateUserPermissions(
  $uid: uuid!
  $permissionsToDelete: [String!]!
  $permissionsToInsert: [AuthUsersPermissionsInsertInput!]!
  $deletePermissionIds: [uuid!]!
  $newAdminOn: [AuthUsersAdminOnInsertInput!]!
  $deletePermissions: Boolean! = false
  $insertPermissions: Boolean! = false
  $deleteAdminOn: Boolean! = false
  $insertAdminOn: Boolean! = false
) {
  deleteAuthUsersPermissions(
    where: {
      _and: [
        { uid: { _eq: $uid } }
        { permission: { _in: $permissionsToDelete } }
      ]
    }
  ) @include(if: $deletePermissions) {
    affectedRows
  }

  insertAuthUsersPermissions(objects: $permissionsToInsert)
    @include(if: $insertPermissions) {
    affectedRows
  }
  deleteAuthUsersAdminOn(
    where: { permissionId: { _in: $deletePermissionIds } }
  ) @include(if: $deleteAdminOn) {
    affectedRows
  }
  insertAuthUsersAdminOn(objects: $newAdminOn) @include(if: $insertAdminOn) {
    affectedRows
  }
}
