fragment PhoneContact on Contacts {
  id
  label
  phone
  isMainPhone
}

fragment FamilyPhoneContact on ResolvedContacts {
  id
  personId
  label
  phone
  isMainPhone
  personType {
    id
    name
    order
    isFamilyAdmin
    isHidden
  }
}
