subscription watchOwnPhoneContacts($personId: uuid!) {
  contacts(
    where: { personId: { _eq: $personId } }
    orderBy: [{ isMainPhone: DESC }, { createdAt: ASC }]
  ) {
    ...PhoneContact
  }
}

subscription watchFamilyPhoneContacts($familyId: uuid!) {
  resolvedContacts(
    where: {
      effectiveFamilyId: { _eq: $familyId }
      personType: { isFamilyAdmin: { _eq: true } }
    }
    orderBy: [
      { personType: { order: ASC } }
      { isMainPhone: DESC }
      { createdAt: ASC }
    ]
  ) {
    ...FamilyPhoneContact
  }
}
