mutation deleteArea($areaId: uuid!) {
  deleteAreas(where: { id: { _eq: $areaId } }) {
    returning {
      ...Area
    }
  }
}

mutation insertArea($newArea: AreasInsertInput!) {
  insertAreasOne(object: $newArea) {
    ...Area
  }
}

mutation updateArea($areaId: uuid!, $newArea: AreasSetInput!) {
  updateAreasByPk(pkColumns: { id: $areaId }, _set: $newArea) {
    ...Area
  }
}
