mutation deleteArea($areaId: Uuid!) {
  deleteAreasByPk(id: $areaId) {
    ...Area
  }
}

mutation insertArea($newArea: AreasInsertInput!) {
  insertAreasOne(object: $newArea) {
    ...Area
  }
}

mutation updateArea($areaId: Uuid!, $newArea: AreasSetInput!) {
  updateAreasByPk(pkColumns: { id: $areaId }, _set: $newArea) {
    ...Area
  }
}
