mutation deleteStore($storeId: uuid!) {
  deleteStoresByPk(id: $storeId) {
    ...Store
  }
}

mutation insertStore($newStore: StoresInsertInput!) {
  insertStoresOne(object: $newStore) {
    ...Store
  }
}

mutation updateStore(
  $storeId: uuid!
  $newStore: StoresSetInput!
  $addressId: uuid!
  $newAddress: AddressesSetInput
  $updateAddress: Boolean!
  $updateStore: Boolean!
) {
  updateStoresByPk(pkColumns: { id: $storeId }, _set: $newStore)
    @include(if: $updateStore) {
    ...Store
  }

  updateAddressesByPk(pkColumns: { id: $addressId }, _set: $newAddress)
    @include(if: $updateAddress) {
    ...Address
  }
}
