subscription watchAllStores(
  $limit: Int = 200
  $orderBy: [StoresOrderBy!] = { name: ASC }
  $where: [StoresBoolExp!] = {}
) {
  stores(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Store
  }
}

subscription watchStoresCount($where: [StoresBoolExp!] = {}) {
  storesAggregate(where: { _and: $where }) {
    aggregate {
      count
    }
  }
}

subscription watchStore($id: uuid!) {
  storesByPk(id: $id) {
    ...Store
    address {
      ...Address
    }
    lastEdit {
      ...LatestEditHistory
    }
    family {
      ...Family
    }
  }
}
