subscription watchAllGroups(
  $limit: Int = 200
  $orderBy: [GroupsOrderBy!] = { name: ASC }
  $where: [GroupsBoolExp!] = {}
) {
  groups(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Group
  }
}

subscription watchGroup($id: Uuid!) {
  groupsByPk(id: $id) {
    ...Group
    service {
      ...ServiceWithStudyYears
    }
    lastEdit
    validity
    adminUsers(distinctOn: uid) {
      user {
        ...User
      }
    }
  }
}
