subscription watchAllAreas(
  $limit: Int = 200
  $orderBy: [AreasOrderBy!] = { name: ASC }
  $where: [AreasBoolExp!] = {}
) {
  areas(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Area
    bounds
  }
}

subscription watchAreasCount($where: [AreasBoolExp!] = {}, $limit: Int) {
  areasAggregate(where: { _and: $where }, limit: $limit) {
    aggregate {
      count
    }
  }
}

subscription watchArea($id: uuid!) {
  areasByPk(id: $id) {
    ...Area
    bounds
    lastEdit {
      ...LatestEditHistory
    }
    adminUsers(distinctOn: uid) {
      user {
        ...User
      }
    }
  }
}
