subscription getAreasStream(
  $addWhere: [areas_bool_exp!] = {}
  $limit: Int = 200
) {
  areas(where: { _and: $addWhere }, order_by: { name: asc }, limit: $limit) {
    id
    name
    color
    bounds
  }
}
subscription getServicesStream(
  $addWhere: [services_bool_exp!] = {}
  $limit: Int = 200
) {
  services(
    where: { _and: $addWhere }
    order_by: { studyYearFrom: asc, studyYearTo: asc }
    limit: $limit
  ) {
    id
    name
    color
    fromStudyYear {
      name
      order
    }
    toStudyYear {
      name
      order
    }
    groups(order_by: { service: { studyYearFrom: asc, studyYearTo: asc } }) {
      id
      name
      color
    }
  }
}

query getStudyYearName($order: smallint!) {
  studyYears_by_pk(order: $order) {
    order
    name
  }
}

subscription getPersonsStream(
  $addWhere: [persons_bool_exp!] = {}
  $limit: Int = 200
) {
  persons(where: { _and: $addWhere }, order_by: { name: asc }, limit: $limit) {
    id
    name
    color
    photo_updated_at
  }
}

subscription getUserInfoStream($uid: uuid!) {
  users_by_pk(uid: $uid) {
    uid
    firebase_auth_uid
    email
    permissions
    person {
      id
      name
      address
      geolocation
      mainPhone
      otherPhones
      birthdate
      gender
      isShammas
      shammasLevel
      schoolID
      collegeID
      churchID
      fatherID
      isStudent
      jobID
      jobDescription
      qualificationID
      personTypeID
      stateID
      isServant
      notes
      familyID
      storeID
      studyYearID
      color
      photo_updated_at
      lastKodas
      lastConfession
    }
  }
}

query getPersonsAttendanceWarning($dateFilter: date!) {
  persons(
    where: { attendance_history: { _not: { dayID: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsKodasWarning($dateFilter: date!) {
  persons(
    where: { kodas_history: { _not: { dayID: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsConfessionWarning($dateFilter: date!) {
  persons(
    where: { confession_history: { _not: { dayID: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsVisitWarning($dateFilter: timestamptz!) {
  persons(
    where: { visit_history: { _not: { time: { _gte: $dateFilter } } } }
    limit: 25
  ) {
    name
  }
}

query getPersonsBirthday($dateFilter: String!) {
  persons(where: { birthday: { _eq: $dateFilter } }, limit: 25) {
    name
  }
}
