query getPersonsNames(
  $where: [PersonsBoolExp!] = {}
  $orderBy: [PersonsOrderBy!] = { name: ASC }
  $limit: Int = 25
) {
  persons(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    name
  }
}

query getMorePersonData(
  $id: uuid!
  $areasAfter: String = ""
  $classesAfter: String = ""
  $groupsAfter: String = ""
  $servicesAfter: String = ""
) {
  personsByPk(id: $id) {
    id
    name
    areas(orderBy: { name: ASC }, where: { name: { _gt: $areasAfter } }) {
      id
      name
      color
      photoUpdatedAt
    }
    classes(orderBy: { name: ASC }, where: { name: { _gt: $classesAfter } }) {
      id
      name
      color
      photoUpdatedAt

      attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
        aggregate {
          max {
            dayId
          }
        }
      }
    }
    groups(
      orderBy: { group: { name: ASC } }
      where: { group: { name: { _gt: $groupsAfter } } }
    ) {
      group {
        id
        name
        color
        photoUpdatedAt

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              dayId
            }
          }
        }
      }
    }
    services(
      orderBy: { service: { name: ASC } }
      where: { service: { name: { _gt: $servicesAfter } } }
    ) {
      service {
        id
        name
        color
        photoUpdatedAt

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              dayId
            }
          }
        }
      }
    }
  }
}

query personsGeolocations(
  $areasIds: [uuid!]
  $streetsIds: [uuid!]
  $familiesIds: [uuid!]
  $personsConditions: [PersonsBoolExp!] = {}
) {
  areas(
    where: {
      _or: [
        { id: { _in: $areasIds } }
        { streets: { id: { _in: $streetsIds } } }
        { families: { id: { _in: $familiesIds } } }
        { persons: { _and: $personsConditions } }
      ]
      bounds: { _isNull: false }
    }
  ) {
    id
    name
    color

    bounds
  }
  streets(
    where: {
      _or: [
        { id: { _in: $streetsIds } }
        { families: { id: { _in: $familiesIds } } }
        { persons: { _and: $personsConditions } }
      ]
      line: { _isNull: false }
    }
  ) {
    id
    name
    color

    line
  }
  families(
    where: {
      _or: [
        { id: { _in: $familiesIds } }
        { persons: { _and: $personsConditions } }
      ]
      geolocation: { _isNull: false }
    }
  ) {
    id
    name
    color

    geolocation
  }
  persons(
    where: { _and: $personsConditions, geolocation: { _isNull: false } }
  ) {
    id
    name
    color

    geolocation
  }
}

query analyzePerson(
  $dateFrom: date!
  $dateTo: date!
  $timeFrom: timestamptz!
  $timeTo: timestamptz!
  $personId: uuid!
  $groupsIds: [uuid!] = []
  $classesIds: [uuid!] = []
  $servicesIds: [uuid!] = []
  $callHistory: Boolean! = false
  $visitHistory: Boolean! = false
  $editHistory: Boolean! = false
  $confessionHistory: Boolean! = false
  $kodasHistory: Boolean! = false
) {
  personsByPk(id: $personId) {
    id
    name
    callHistoryAggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } })
      @include(if: $callHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    visitHistoryAggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } })
      @include(if: $visitHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    editHistoryAggregate(where: { time: { _gte: $timeFrom, _lte: $timeTo } })
      @include(if: $editHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    kodasHistoryAggregate(where: { dayId: { _gte: $dateFrom, _lte: $dateTo } })
      @include(if: $kodasHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    confessionHistoryAggregate(
      where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
    ) @include(if: $confessionHistory) {
      aggregate {
        count
        max {
          time
        }
      }
      nodes {
        time
      }
    }
    services(where: { serviceId: { _in: $servicesIds } }) {
      service {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: false }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
    classes(where: { id: { _in: $classesIds } }) {
      id
      name
      color
      attendanceHistoryAggregate(
        where: {
          dayId: { _gte: $dateFrom, _lte: $dateTo }
          personId: { _eq: $personId }
          asAdmin: { _eq: false }
        }
      ) {
        aggregate {
          count
          max {
            dayId
          }
        }
        nodes {
          dayId
        }
      }
      attendanceDaysConstraintsAggregate(
        where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
      ) {
        aggregate {
          count
        }
        nodes {
          dayId
        }
      }
    }
    groups(where: { groupId: { _in: $groupsIds } }) {
      group {
        id
        name
        color
        attendanceHistoryAggregate(
          where: {
            dayId: { _gte: $dateFrom, _lte: $dateTo }
            personId: { _eq: $personId }
            asAdmin: { _eq: false }
          }
        ) {
          aggregate {
            count
            max {
              dayId
            }
          }
          nodes {
            dayId
          }
        }
        attendanceDaysConstraintsAggregate(
          where: { dayId: { _gte: $dateFrom, _lte: $dateTo } }
        ) {
          aggregate {
            count
          }
          nodes {
            dayId
          }
        }
      }
    }
  }
}

query getPersonClassesAndGroups($id: uuid!) {
  personsByPk(id: $id) {
    id
    name
    classes(orderBy: { name: ASC }) {
      id
      name
      color
      photoUpdatedAt
      service {
        id
        name
        color
        photoUpdatedAt
      }
    }
    groups(orderBy: { group: { name: ASC } }) {
      group {
        id
        name
        color
        photoUpdatedAt
        service {
          id
          name
          color
          photoUpdatedAt
        }
      }
    }
  }
}

query getFullPersonData($id: uuid!) {
  personsByPk(id: $id) {
    id
    name
    color
    photoUpdatedAt
    address
    birthdate
    church {
      id
      name
    }
    college {
      id
      name
    }
    family {
      id
      name
      color
      photoUpdatedAt
    }
    father {
      id
      name
      church {
        id
        name
      }
    }
    gender
    geolocation
    groups {
      group {
        id
        name
        color
        photoUpdatedAt
        service {
          id
          name
          color
          photoUpdatedAt
        }

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    isServant
    isShammas
    isStudent
    job {
      id
      name
    }
    jobDescription
    mainPhone
    notes
    otherPhones
    personType {
      id
      name
    }
    qualification {
      id
      name
    }
    school {
      id
      name
    }
    services {
      service {
        id
        name
        color
        photoUpdatedAt
        fromStudyYear {
          name
          order
        }
        toStudyYear {
          name
          order
        }

        attendanceHistoryAggregate(where: { personId: { _eq: $id } }) {
          aggregate {
            max {
              time
            }
          }
        }
      }
    }
    shammasLevel {
      id
      name
      order
    }
    state {
      id
      color
      name
    }
    studyYear {
      name
      order
    }
    tags(orderBy: { tag: { name: ASC } }) {
      tag {
        id
        name
        color
      }
    }
  }
}
