name: church-admin-e2e

services:
  postgres:
    healthcheck:
      start_period: 2m

  hasura:
    volumes:
      - ./hasura/migrations:/hasura-migrations:ro
      - ./hasura/metadata:/hasura-metadata:ro
    environment:
      STUDY_YEAR_ROLL_NOTIFY_URL: http://firebase-emulators:5001/demo-church-admin/europe-west6/notifyStudyYearRollFailure

  firebase-emulators:
    environment:
      FIREBASE_PROJECT_ID: demo-church-admin
      FIREBASE_EMULATORS_DATA_DIR: ""
    healthcheck:
      start_period: 5m
