// Mocks generated by Mockito 5.4.6 from annotations
// in church_admin/test/src/features/home/presentation/widgets/home_search_delegate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i6;

import 'package:church_admin/church_admin.dart' as _i2;
import 'package:flutter/material.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i5;
import 'package:go_router/go_router.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeSearchResults_1 extends _i1.SmartFake
    implements _i2.HomeSearchResults {
  _FakeHomeSearchResults_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouter_2 extends _i1.SmartFake implements _i3.GoRouter {
  _FakeGoRouter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigatorState_3 extends _i1.SmartFake
    implements _i4.NavigatorState {
  _FakeNavigatorState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeGlobalKey_4<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake
    implements _i4.GlobalKey<T> {
  _FakeGlobalKey_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconData_5 extends _i1.SmartFake implements _i4.IconData {
  _FakeIconData_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncKVStore_6<T> extends _i1.SmartFake
    implements _i2.SyncKVStore<T> {
  _FakeSyncKVStore_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseCacheManager_7 extends _i1.SmartFake
    implements _i5.BaseCacheManager {
  _FakeBaseCacheManager_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_8 extends _i1.SmartFake implements _i6.File {
  _FakeFile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDAO extends _i1.Mock implements _i2.HomeDAO {
  @override
  _i2.DatabaseService get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabaseService_0(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeDatabaseService_0(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i7.Future<_i2.HomeSearchResults> searchAll(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchAll, [query]),
            returnValue: _i7.Future<_i2.HomeSearchResults>.value(
              _FakeHomeSearchResults_1(
                this,
                Invocation.method(#searchAll, [query]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.HomeSearchResults>.value(
              _FakeHomeSearchResults_1(
                this,
                Invocation.method(#searchAll, [query]),
              ),
            ),
          )
          as _i7.Future<_i2.HomeSearchResults>);
}

/// A class which mocks [ViewableObjectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewableObjectService extends _i1.Mock
    implements _i2.ViewableObjectService {
  @override
  _i3.GoRouter get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeGoRouter_2(this, Invocation.getter(#router)),
            returnValueForMissingStub: _FakeGoRouter_2(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i3.GoRouter);

  @override
  _i4.NavigatorState get navigator =>
      (super.noSuchMethod(
            Invocation.getter(#navigator),
            returnValue: _FakeNavigatorState_3(
              this,
              Invocation.getter(#navigator),
            ),
            returnValueForMissingStub: _FakeNavigatorState_3(
              this,
              Invocation.getter(#navigator),
            ),
          )
          as _i4.NavigatorState);

  @override
  _i4.GlobalKey<_i4.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_4<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_4<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i4.GlobalKey<_i4.NavigatorState>);

  @override
  void onTap(_i2.Viewable? object) => super.noSuchMethod(
    Invocation.method(#onTap, [object]),
    returnValueForMissingStub: null,
  );

  @override
  String? getFormattedValue(
    _i2.Viewable? object,
    _i2.FieldMetadata<Object>? field,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFormattedValue, [object, field]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i4.IconData getDefaultIconFor<T extends _i2.IImage>([T? imageObject]) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultIconFor, [imageObject]),
            returnValue: _FakeIconData_5(
              this,
              Invocation.method(#getDefaultIconFor, [imageObject]),
            ),
            returnValueForMissingStub: _FakeIconData_5(
              this,
              Invocation.method(#getDefaultIconFor, [imageObject]),
            ),
          )
          as _i4.IconData);
}

/// A class which mocks [ImageUrlCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageUrlCacheService extends _i1.Mock
    implements _i2.ImageUrlCacheService {
  @override
  _i2.SyncKVStore<String> get box =>
      (super.noSuchMethod(
            Invocation.getter(#box),
            returnValue: _FakeSyncKVStore_6<String>(
              this,
              Invocation.getter(#box),
            ),
            returnValueForMissingStub: _FakeSyncKVStore_6<String>(
              this,
              Invocation.getter(#box),
            ),
          )
          as _i2.SyncKVStore<String>);

  @override
  _i5.BaseCacheManager get cacheManager =>
      (super.noSuchMethod(
            Invocation.getter(#cacheManager),
            returnValue: _FakeBaseCacheManager_7(
              this,
              Invocation.getter(#cacheManager),
            ),
            returnValueForMissingStub: _FakeBaseCacheManager_7(
              this,
              Invocation.getter(#cacheManager),
            ),
          )
          as _i5.BaseCacheManager);

  @override
  _i7.Future<_i6.File> getImageFile(_i2.ObjectImageInfo? imageInfo) =>
      (super.noSuchMethod(
            Invocation.method(#getImageFile, [imageInfo]),
            returnValue: _i7.Future<_i6.File>.value(
              _FakeFile_8(this, Invocation.method(#getImageFile, [imageInfo])),
            ),
            returnValueForMissingStub: _i7.Future<_i6.File>.value(
              _FakeFile_8(this, Invocation.method(#getImageFile, [imageInfo])),
            ),
          )
          as _i7.Future<_i6.File>);

  @override
  _i7.Future<String> getImageUrl(_i2.ObjectImageInfo? imageObject) =>
      (super.noSuchMethod(
            Invocation.method(#getImageUrl, [imageObject]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getImageUrl, [imageObject]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getImageUrl, [imageObject]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  String? getNonExpiredCachedImageUrl(_i2.ObjectImageInfo? imageObject) =>
      (super.noSuchMethod(
            Invocation.method(#getNonExpiredCachedImageUrl, [imageObject]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String? getCachedImageUrl(_i2.ObjectImageInfo? imageInfo) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImageUrl, [imageInfo]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i7.Future<bool> isUrlFileCachedAndValid(String? cacheKey) =>
      (super.noSuchMethod(
            Invocation.method(#isUrlFileCachedAndValid, [cacheKey]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  bool isUrlExpired(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#isUrlExpired, [url]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [UserSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsService extends _i1.Mock
    implements _i2.UserSettingsService {
  @override
  _i2.SyncKVStore<dynamic> get box =>
      (super.noSuchMethod(
            Invocation.getter(#box),
            returnValue: _FakeSyncKVStore_6<dynamic>(
              this,
              Invocation.getter(#box),
            ),
            returnValueForMissingStub: _FakeSyncKVStore_6<dynamic>(
              this,
              Invocation.getter(#box),
            ),
          )
          as _i2.SyncKVStore<dynamic>);

  @override
  bool get greatFeastTheme =>
      (super.noSuchMethod(
            Invocation.getter(#greatFeastTheme),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> setDarkTheme(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDarkTheme, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setRegisteredFCMToken(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRegisteredFCMToken, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setGreatFeastTheme(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGreatFeastTheme, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setupDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#setupDefaults, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onTransition(
    _i9.Bloc<dynamic, dynamic>? bloc,
    _i9.Transition<dynamic, dynamic>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [bloc, transition]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void onCreate(_i9.BlocBase<dynamic>? bloc) => super.noSuchMethod(
    Invocation.method(#onCreate, [bloc]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.Bloc<dynamic, dynamic>? bloc, Object? event) =>
      super.noSuchMethod(
        Invocation.method(#onEvent, [bloc, event]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.BlocBase<dynamic>? bloc, _i9.Change<dynamic>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [bloc, change]),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    _i9.BlocBase<dynamic>? bloc,
    Object? error,
    StackTrace? stackTrace,
  ) => super.noSuchMethod(
    Invocation.method(#onError, [bloc, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i9.Bloc<dynamic, dynamic>? bloc,
    Object? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [bloc, event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onClose(_i9.BlocBase<dynamic>? bloc) => super.noSuchMethod(
    Invocation.method(#onClose, [bloc]),
    returnValueForMissingStub: null,
  );
}
