subscription watchAllStores(
  $limit: Int = 200
  $orderBy: [StoresOrderBy!] = { name: ASC }
  $where: [StoresBoolExp!] = {}
) {
  stores(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Store
  }
}

subscription watchStore($id: Uuid!) {
  storesByPk(id: $id) {
    ...Store
    areas(orderBy: { name: ASC }) {
      ...Area
    }
    streets(orderBy: { name: ASC }) {
      ...Street
    }
    lastEdit {
      ...EditHistory
    }
    address
    geolocation
    family {
      ...Family
    }
  }
}
