subscription watchAllColleges(
  $where: [CollegesBoolExp!] = {}
  $orderBy: [CollegesOrderBy!] = { name: ASC }
  $limit: Int = 25
) {
  colleges(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
  }
}
