fragment User on AuthUsersData {
  ...UserNoPhoto
  photoUpdatedAt
  blurhash
}

fragment UserNoPhoto on AuthUsersData {
  uid
  name
  email
}

fragment UserOverview on AuthUsersData {
  ...User
  currentUserCanManageThisUser
  email
  authId
  invitation {
    ...Invitation
  }
  ...UserPermissions
  person {
    ...Person
    lastKodas {
      ...LatestKodasHistory
    }
    lastConfession {
      ...LatestConfessionHistory
    }
  }
}

fragment UserDetails on AuthUsersData {
  ...UserOverview
  lastEdit {
    ...LatestEditHistory
  }
  ...UserAdminOn
  preferences {
    ...UserPreferences
  }
  fcmTokens {
    ...FcmToken
  }
}

fragment UserPermissions on AuthUsersData {
  permissions {
    permission
  }
}

fragment UserAdminScopes on AuthUsersData {
  adminOn {
    permissionId
    area {
      ...Area
    }
    service {
      ...Service
    }
    serviceStudyYearData {
      ...StudyYear
    }
  }
}

fragment UserAdminOn on AuthUsersData {
  adminOn(
    orderBy: [
      { area: { name: ASC_NULLS_LAST } }
      { service: { studyYearFromId: ASC, studyYearToId: ASC } }
      { serviceStudyYear: ASC }
      { serviceGender: DESC_NULLS_FIRST }
      { service: { name: ASC_NULLS_LAST } }
      { group: { name: ASC_NULLS_LAST } }
    ]
  ) {
    permissionId
    area {
      ...Area
    }
    areaAllowExport
    areaAllowEdit
    areaAdminOnUsers
    service {
      ...Service
      studyYearFrom {
        ...StudyYear
      }
      studyYearTo {
        ...StudyYear
      }
    }
    serviceStudyYearData {
      ...StudyYear
    }
    serviceGender
    serviceAllowExport
    serviceAllowEdit
    serviceAllowRecordAttendance
    serviceAllowRecordServantsAttendance
    serviceAdminOnUsers
    serviceWriteRelatedFamilies
    classes(orderBy: { name: ASC }) {
      ...Class
    }
    group {
      ...Group
    }
    groupAllowExport
    groupAllowEdit
    groupAllowRecordAttendance
    groupAllowRecordServantsAttendance
    groupAdminOnUsers
    groupWriteRelatedFamilies
  }
}
