query analyzeUserAttendance(
  $dateFrom: Date!
  $dateTo: Date!
  $personId: Uuid!
  $userId: Uuid!
  $groupsIds: [Uuid!]
  $classesIds: [Uuid!]
  $servicesIds: [Uuid!]
) {
  authUsersDataByPk(uid: $userId) {
    ...User
    ...AttendanceFields
  }
}
