subscription watchUser($uid: uuid!, $fullData: Boolean = false) {
  authUsersDataByPk(uid: $uid) {
    ...UserOverview @skip(if: $fullData)
    ...UserDetails @include(if: $fullData)
  }
}

subscription watchAllUsers(
  $where: [AuthUsersDataBoolExp!] = {}
  $orderBy: [AuthUsersDataOrderBy!] = { name: ASC }
  $limit: Int = 200
) {
  authUsersData(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    ...UserOverview
  }
}
