subscription getServicesStream(
  $addWhere: [ServicesBoolExp!] = {}
  $groupsAddWhere: [GroupsBoolExp!] = {}
  $classesAddWhere: [ClassesBoolExp!] = {}
  $limit: Int = 200
) {
  services(
    where: { _and: $addWhere }
    orderBy: { studyYearFrom: ASC, studyYearTo: ASC }
    limit: $limit
  ) {
    id
    name
    color
    photoUpdatedAt
    fromStudyYear {
      name
      order
    }
    toStudyYear {
      name
      order
    }
    classes(
      where: { _and: $classesAddWhere }
      orderBy: { studyYear: { order: ASC }, serviceGender: DESC_NULLS_LAST }
    ) {
      id
      name
      color
      photoUpdatedAt

      studyYear {
        name
        order
      }
    }
    groups(
      where: { _and: $groupsAddWhere }
      orderBy: { service: { studyYearFrom: ASC, studyYearTo: ASC } }
    ) {
      id
      name
      color
      photoUpdatedAt
    }
  }
}
