fragment Meeting on HistoryMeetings {
  id
  name
  audience
  color
  isArchived
  showKodasCheckbox
  serviceId
  serviceGender
  serviceStudyYear
  groupId
  service {
    ...ServiceNoPhoto
  }
  studyYear {
    ...StudyYear
  }
  group {
    ...GroupNoPhoto
  }
}
