mutation insertMeeting($object: HistoryMeetingsInsertInput!) {
  insertHistoryMeetingsOne(object: $object) {
    ...Meeting
  }
}

mutation updateMeeting($id: uuid!, $set: HistoryMeetingsSetInput!) {
  updateHistoryMeetingsByPk(pkColumns: { id: $id }, _set: $set) {
    ...Meeting
  }
}

mutation markAttendance($object: HistoryAttendanceHistoryInsertInput!) {
  insertHistoryAttendanceHistoryOne(object: $object) {
    id
    meetingId
    personId
    datetime
    asServant
    recordedBy
    recordedByUser {
      ...User
    }
  }
}

mutation updateAttendanceTime($id: uuid!, $datetime: timestamptz!) {
  updateHistoryAttendanceHistoryByPk(
    pkColumns: { id: $id }
    _set: { datetime: $datetime }
  ) {
    id
    meetingId
    personId
    datetime
    asServant
    recordedBy
    recordedByUser {
      ...User
    }
  }
}

mutation unmarkAttendance($id: uuid!) {
  deleteHistoryAttendanceHistoryByPk(id: $id) {
    id
    meetingId
    personId
    datetime
    asServant
    recordedBy
  }
}
