subscription watchAllMeetings(
  $where: [HistoryMeetingsBoolExp!] = {}
  $orderBy: [HistoryMeetingsOrderBy!] = { name: ASC }
  $limit: Int = 200
) {
  historyMeetings(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    ...Meeting
  }
}

subscription watchMeeting($id: uuid!) {
  historyMeetingsByPk(id: $id) {
    ...Meeting
  }
}

subscription watchAttendanceHistory(
  $meetingId: uuid!
  $fromDate: timestamptz!
  $toDate: timestamptz!
) {
  historyAttendanceHistory(
    where: {
      meetingId: { _eq: $meetingId }
      datetime: { _gte: $fromDate, _lt: $toDate }
    }
  ) {
    id
    meetingId
    personId
    datetime
    asServant
  }
}
