abstract final class DefaultFieldLabels {
  // TODO: to defer to localization
  static const byName = <String, String>{
    'id': '=',
    'name': 'الاسم',
    'bounds': 'الموقع',
    'color': 'اللون',
    'photoUpdatedAt': 'أخر تحديث للصورة',
    'adminUsers': 'الخدام المسؤلين',
    'families': 'العائلات',
    'stores': 'المتاجر',
    'streets': 'الشوارع',
    'persons': 'المخدومين',
    'line': 'الموقع',
    'areas': 'المناطق',
    'address': 'تفاصيل العنوان',
    'fullAddressText': 'العنوان الكامل',
    'geolocation': 'الموقع',
    'notes': 'ملاحظات',
    'children': 'العائلات الأبناء',
    'parents': 'العائلات الأباء',
    'adminFamily': 'العائلة المسؤولة',
    'studyYearFrom': 'السنة الدراسية: من',
    'studyYearTo': 'السنة الدراسية: إلى',
    'nextService': 'الخدمة التالية',
    'class': 'الفصل',
    'classes': 'الفصول',
    'group': 'المجموعة',
    'groups': 'المجموعات',
    'service': 'الخدمة',
    'studyYear': 'السنة الدراسية',
    'serviceGender': 'نوع المخدومين المسؤول عنهم',
    'adminOn': 'مسؤول عن',
    'permission': 'الصلاحية',
    'permissions': 'الصلاحيات',
    'person': 'بيانات المخدوم',
    'mainPhone': 'رقم الهاتف',
    'birthdate': 'تاريخ الميلاد',
    'birthday': 'يوم وشهر الميلاد',
    'isStudent': 'طالب؟',
    'college': 'الكلية',
    'school': 'المدرسة',
    'qualification': 'المؤهل',
    'job': 'الوظيفة',
    'jobDescription': 'تفاصيل الوظيفة',
    'gender': 'النوع',
    'personType': 'نوع الفرد في العائلة',
    'isShammas': 'شماس؟',
    'shammasLevel': 'رتبة الشموسية',
    'church': 'الكنيسة',
    'father': 'اب الاعتراف',
    'isServant': 'خادم؟',
    'state': 'الحالة الروحية',
    'hobby': 'الهواية',
    'hobbies': 'الهوايات',
    'tag': 'الشارة',
    'tags': 'الشارات',
    'district': 'الحي',
    'districts': 'الأحياء السكنية',
    'substreetName': 'الشارع الفرعي',
    'storeyNumber': 'رقم الدور',
    'apartmentNumber': 'رقم الشقة',
    'houseCode': 'رقم العمارة',
    'specialLandmark': 'علامة مميزة',
    'area': 'المنطقة',
    'street': 'الشارع',
    'family': 'العائلة',
    'store': 'المتجر',
    'services': 'الخدمات',
    'recordedByUser': 'الخادم الذي سجل',
    'user': 'بيانات الخادم',
    'order': 'الترتيب',
    'time': 'الوقت',
    'lastAttendance': 'أخر حضور',
    'lastEdit': 'أخر تحديث البيانات',
    'lastKodas': 'أخر تناول',
    'lastConfession': 'أخر اعتراف',
    'lastVisit': 'أخر افتقاد',
    'lastCall': 'أخر مكالمات',
    'attendanceHistory': 'سجل الحضور',
    'editHistory': 'سجل تحديث البيانات',
    'kodasHistory': 'سجل التناول',
    'confessionHistory': 'سجل الاعتراف',
    'visitHistory': 'سجل الافتقاد',
    'callHistory': 'سجل المكالمات',
    'max': 'أقصى',
    'min': 'أدنى',
    'count': 'العدد',
    'areaAllowEdit': 'يمكنه تعديل المنطقة',
    'areaAdminOnUsers': 'مسؤول عن خدام المنطقة',
    'serviceStudyYearData': 'السنة الدراسية',
    'serviceAllowEdit': 'يمكنه تعديل الخدمة',
    'serviceAdminOnUsers': 'مسؤول عن خدام الخدمة',
    'groupAllowEdit': 'يمكنه تعديل المجموعة',
    'groupAdminOnUsers': 'مسؤول عن خدام المجموعة',
  };
}
