query getFamilyRelatedFamilies($familyId: Uuid!) {
  familiesByPk(id: $familyId) {
    ...Family
    children(orderBy: { child: { name: ASC } }) {
      child {
        ...Family
      }
    }
    parents(orderBy: { parent: { name: ASC } }) {
      parent {
        ...Family
      }
    }
  }
}
