subscription watchAllFamilies(
  $limit: Int = 200
  $orderBy: [FamiliesOrderBy!] = { name: ASC }
  $where: [FamiliesBoolExp!] = {}
) {
  families(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Family
  }
}

subscription watchFamily($id: Uuid!) {
  familiesByPk(id: $id) {
    ...Family
    areas(orderBy: { name: ASC }) {
      ...Area
    }
    streets(orderBy: { name: ASC }) {
      ...Street
    }
    geolocation
    address
    notes
    lastEdit {
      ...EditHistory
    }
  }
}
