// Mocks generated by Mockito 5.4.4 from annotations
// in church_admin/test/src/features/advanced_search/application/advanced_query_parser_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:church_admin/church_admin.dart' as _i2;
import 'package:church_admin/src/core/services/database/gql_definintions/persons/__generated__/subscriptions.gql.dart'
    as _i6;
import 'package:church_admin/src/core/services/database/gql_definintions/persons/persons_notifications_queries.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:rxdart/rxdart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDBGraphQLClient_0 extends _i1.SmartFake
    implements _i2.DBGraphQLClient {
  _FakeDBGraphQLClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGQLParser_1 extends _i1.SmartFake implements _i2.GQLParser {
  _FakeGQLParser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDBVarsTransformer_2 extends _i1.SmartFake
    implements _i2.DBVarsTransformer {
  _FakeDBVarsTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdvancedQueryParser_3 extends _i1.SmartFake
    implements _i2.AdvancedQueryParser {
  _FakeAdvancedQueryParser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAreasDAO_4 extends _i1.SmartFake implements _i2.AreasDAO {
  _FakeAreasDAO_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreetsDAO_5 extends _i1.SmartFake implements _i2.StreetsDAO {
  _FakeStreetsDAO_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFamiliesDAO_6 extends _i1.SmartFake implements _i2.FamiliesDAO {
  _FakeFamiliesDAO_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoresDAO_7 extends _i1.SmartFake implements _i2.StoresDAO {
  _FakeStoresDAO_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonsDAO_8 extends _i1.SmartFake implements _i2.PersonsDAO {
  _FakePersonsDAO_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServicesDAO_9 extends _i1.SmartFake implements _i2.ServicesDAO {
  _FakeServicesDAO_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassesDAO_10 extends _i1.SmartFake implements _i2.ClassesDAO {
  _FakeClassesDAO_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupsDAO_11 extends _i1.SmartFake implements _i2.GroupsDAO {
  _FakeGroupsDAO_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsersDAO_12 extends _i1.SmartFake implements _i2.UsersDAO {
  _FakeUsersDAO_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetadataDAO_13 extends _i1.SmartFake implements _i2.MetadataDAO {
  _FakeMetadataDAO_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHistoryDAO_14 extends _i1.SmartFake implements _i2.HistoryDAO {
  _FakeHistoryDAO_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonsNotificationsQueries_15 extends _i1.SmartFake
    implements _i3.PersonsNotificationsQueries {
  _FakePersonsNotificationsQueries_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamAllConfig_16<T, TBoolExp, TOrderByExp> extends _i1.SmartFake
    implements _i2.StreamAllConfig<T, TBoolExp, TOrderByExp> {
  _FakeStreamAllConfig_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSingleByIdConfig_17<T> extends _i1.SmartFake
    implements _i2.StreamSingleByIdConfig<T> {
  _FakeStreamSingleByIdConfig_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteSingleByIdConfig_18<T> extends _i1.SmartFake
    implements _i2.DeleteSingleByIdConfig<T> {
  _FakeDeleteSingleByIdConfig_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateObjectConfig_19<T> extends _i1.SmartFake
    implements _i2.UpdateObjectConfig<T> {
  _FakeUpdateObjectConfig_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateObjectConfig_20<T> extends _i1.SmartFake
    implements _i2.CreateObjectConfig<T> {
  _FakeCreateObjectConfig_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseService_21 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerson_22 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamableDAOProxy_23<T extends _i2.ViewableWithID, TBoolExp,
        TOrderByExp> extends _i1.SmartFake
    implements _i2.StreamableDAOProxy<T, TBoolExp, TOrderByExp> {
  _FakeStreamableDAOProxy_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreatableDAOProxy_24<T extends _i2.ViewableWithID>
    extends _i1.SmartFake implements _i2.CreatableDAOProxy<T> {
  _FakeCreatableDAOProxy_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdatableDAOProxy_25<T extends _i2.ViewableWithID>
    extends _i1.SmartFake implements _i2.UpdatableDAOProxy<T> {
  _FakeUpdatableDAOProxy_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeletableDAOProxy_26<T extends _i2.ViewableWithID>
    extends _i1.SmartFake implements _i2.DeletableDAOProxy<T> {
  _FakeDeletableDAOProxy_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGQLPaginatableStream_27<T> extends _i1.SmartFake
    implements _i2.GQLPaginatableStream<T> {
  _FakeGQLPaginatableStream_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_28<T1> extends _i1.SmartFake
    implements _i4.ValueStream<T1> {
  _FakeValueStream_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_29<T1> extends _i1.SmartFake
    implements _i5.StreamSubscription<T1> {
  _FakeStreamSubscription_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_30<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  @override
  _i2.DBGraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeDBGraphQLClient_0(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeDBGraphQLClient_0(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i2.DBGraphQLClient);

  @override
  _i2.GQLParser get parser => (super.noSuchMethod(
        Invocation.getter(#parser),
        returnValue: _FakeGQLParser_1(
          this,
          Invocation.getter(#parser),
        ),
        returnValueForMissingStub: _FakeGQLParser_1(
          this,
          Invocation.getter(#parser),
        ),
      ) as _i2.GQLParser);

  @override
  _i2.DBVarsTransformer get varsTransformer => (super.noSuchMethod(
        Invocation.getter(#varsTransformer),
        returnValue: _FakeDBVarsTransformer_2(
          this,
          Invocation.getter(#varsTransformer),
        ),
        returnValueForMissingStub: _FakeDBVarsTransformer_2(
          this,
          Invocation.getter(#varsTransformer),
        ),
      ) as _i2.DBVarsTransformer);

  @override
  _i2.AdvancedQueryParser get advancedQueryParser => (super.noSuchMethod(
        Invocation.getter(#advancedQueryParser),
        returnValue: _FakeAdvancedQueryParser_3(
          this,
          Invocation.getter(#advancedQueryParser),
        ),
        returnValueForMissingStub: _FakeAdvancedQueryParser_3(
          this,
          Invocation.getter(#advancedQueryParser),
        ),
      ) as _i2.AdvancedQueryParser);

  @override
  _i2.AreasDAO get areas => (super.noSuchMethod(
        Invocation.getter(#areas),
        returnValue: _FakeAreasDAO_4(
          this,
          Invocation.getter(#areas),
        ),
        returnValueForMissingStub: _FakeAreasDAO_4(
          this,
          Invocation.getter(#areas),
        ),
      ) as _i2.AreasDAO);

  @override
  _i2.StreetsDAO get streets => (super.noSuchMethod(
        Invocation.getter(#streets),
        returnValue: _FakeStreetsDAO_5(
          this,
          Invocation.getter(#streets),
        ),
        returnValueForMissingStub: _FakeStreetsDAO_5(
          this,
          Invocation.getter(#streets),
        ),
      ) as _i2.StreetsDAO);

  @override
  _i2.FamiliesDAO get families => (super.noSuchMethod(
        Invocation.getter(#families),
        returnValue: _FakeFamiliesDAO_6(
          this,
          Invocation.getter(#families),
        ),
        returnValueForMissingStub: _FakeFamiliesDAO_6(
          this,
          Invocation.getter(#families),
        ),
      ) as _i2.FamiliesDAO);

  @override
  _i2.StoresDAO get stores => (super.noSuchMethod(
        Invocation.getter(#stores),
        returnValue: _FakeStoresDAO_7(
          this,
          Invocation.getter(#stores),
        ),
        returnValueForMissingStub: _FakeStoresDAO_7(
          this,
          Invocation.getter(#stores),
        ),
      ) as _i2.StoresDAO);

  @override
  _i2.PersonsDAO get persons => (super.noSuchMethod(
        Invocation.getter(#persons),
        returnValue: _FakePersonsDAO_8(
          this,
          Invocation.getter(#persons),
        ),
        returnValueForMissingStub: _FakePersonsDAO_8(
          this,
          Invocation.getter(#persons),
        ),
      ) as _i2.PersonsDAO);

  @override
  _i2.ServicesDAO get services => (super.noSuchMethod(
        Invocation.getter(#services),
        returnValue: _FakeServicesDAO_9(
          this,
          Invocation.getter(#services),
        ),
        returnValueForMissingStub: _FakeServicesDAO_9(
          this,
          Invocation.getter(#services),
        ),
      ) as _i2.ServicesDAO);

  @override
  _i2.ClassesDAO get classes => (super.noSuchMethod(
        Invocation.getter(#classes),
        returnValue: _FakeClassesDAO_10(
          this,
          Invocation.getter(#classes),
        ),
        returnValueForMissingStub: _FakeClassesDAO_10(
          this,
          Invocation.getter(#classes),
        ),
      ) as _i2.ClassesDAO);

  @override
  _i2.GroupsDAO get groups => (super.noSuchMethod(
        Invocation.getter(#groups),
        returnValue: _FakeGroupsDAO_11(
          this,
          Invocation.getter(#groups),
        ),
        returnValueForMissingStub: _FakeGroupsDAO_11(
          this,
          Invocation.getter(#groups),
        ),
      ) as _i2.GroupsDAO);

  @override
  _i2.UsersDAO get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: _FakeUsersDAO_12(
          this,
          Invocation.getter(#users),
        ),
        returnValueForMissingStub: _FakeUsersDAO_12(
          this,
          Invocation.getter(#users),
        ),
      ) as _i2.UsersDAO);

  @override
  _i2.MetadataDAO get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeMetadataDAO_13(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakeMetadataDAO_13(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.MetadataDAO);

  @override
  _i2.HistoryDAO get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: _FakeHistoryDAO_14(
          this,
          Invocation.getter(#history),
        ),
        returnValueForMissingStub: _FakeHistoryDAO_14(
          this,
          Invocation.getter(#history),
        ),
      ) as _i2.HistoryDAO);

  @override
  Map<Type, _i2.DAOBase<_i2.ViewableWithID>> get daosByType =>
      (super.noSuchMethod(
        Invocation.getter(#daosByType),
        returnValue: <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
        returnValueForMissingStub: <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
      ) as Map<Type, _i2.DAOBase<_i2.ViewableWithID>>);
}

/// A class which mocks [PersonsDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonsDAO extends _i1.Mock implements _i2.PersonsDAO {
  @override
  _i3.PersonsNotificationsQueries get notificationsQueries =>
      (super.noSuchMethod(
        Invocation.getter(#notificationsQueries),
        returnValue: _FakePersonsNotificationsQueries_15(
          this,
          Invocation.getter(#notificationsQueries),
        ),
        returnValueForMissingStub: _FakePersonsNotificationsQueries_15(
          this,
          Invocation.getter(#notificationsQueries),
        ),
      ) as _i3.PersonsNotificationsQueries);

  @override
  _i2.StreamAllConfig<_i2.Person,
          _i2.Input_PersonsBoolExp, _i2.Input_PersonsOrderBy>
      get baseStreamAllConfig => (super.noSuchMethod(
            Invocation.getter(#baseStreamAllConfig),
            returnValue: _FakeStreamAllConfig_16<_i2.Person,
                _i2.Input_PersonsBoolExp, _i2.Input_PersonsOrderBy>(
              this,
              Invocation.getter(#baseStreamAllConfig),
            ),
            returnValueForMissingStub: _FakeStreamAllConfig_16<_i2.Person,
                _i2.Input_PersonsBoolExp, _i2.Input_PersonsOrderBy>(
              this,
              Invocation.getter(#baseStreamAllConfig),
            ),
          ) as _i2.StreamAllConfig<_i2.Person, _i2.Input_PersonsBoolExp,
              _i2.Input_PersonsOrderBy>);

  @override
  _i2.StreamSingleByIdConfig<_i2.Person> get baseStreamSingleByIdConfig =>
      (super.noSuchMethod(
        Invocation.getter(#baseStreamSingleByIdConfig),
        returnValue: _FakeStreamSingleByIdConfig_17<_i2.Person>(
          this,
          Invocation.getter(#baseStreamSingleByIdConfig),
        ),
        returnValueForMissingStub: _FakeStreamSingleByIdConfig_17<_i2.Person>(
          this,
          Invocation.getter(#baseStreamSingleByIdConfig),
        ),
      ) as _i2.StreamSingleByIdConfig<_i2.Person>);

  @override
  _i2.DeleteSingleByIdConfig<_i2.Person> get baseDeleteSingleByIdConfig =>
      (super.noSuchMethod(
        Invocation.getter(#baseDeleteSingleByIdConfig),
        returnValue: _FakeDeleteSingleByIdConfig_18<_i2.Person>(
          this,
          Invocation.getter(#baseDeleteSingleByIdConfig),
        ),
        returnValueForMissingStub: _FakeDeleteSingleByIdConfig_18<_i2.Person>(
          this,
          Invocation.getter(#baseDeleteSingleByIdConfig),
        ),
      ) as _i2.DeleteSingleByIdConfig<_i2.Person>);

  @override
  _i2.UpdateObjectConfig<_i2.Person> get baseUpdateObjectConfig =>
      (super.noSuchMethod(
        Invocation.getter(#baseUpdateObjectConfig),
        returnValue: _FakeUpdateObjectConfig_19<_i2.Person>(
          this,
          Invocation.getter(#baseUpdateObjectConfig),
        ),
        returnValueForMissingStub: _FakeUpdateObjectConfig_19<_i2.Person>(
          this,
          Invocation.getter(#baseUpdateObjectConfig),
        ),
      ) as _i2.UpdateObjectConfig<_i2.Person>);

  @override
  _i2.CreateObjectConfig<_i2.Person> get baseCreateObjectConfig =>
      (super.noSuchMethod(
        Invocation.getter(#baseCreateObjectConfig),
        returnValue: _FakeCreateObjectConfig_20<_i2.Person>(
          this,
          Invocation.getter(#baseCreateObjectConfig),
        ),
        returnValueForMissingStub: _FakeCreateObjectConfig_20<_i2.Person>(
          this,
          Invocation.getter(#baseCreateObjectConfig),
        ),
      ) as _i2.CreateObjectConfig<_i2.Person>);

  @override
  _i2.DatabaseService get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseService_21(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabaseService_21(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.DatabaseService);

  @override
  _i2.Person Function(Map<String, dynamic>) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (Map<String, dynamic> json) => _FakePerson_22(
          this,
          Invocation.getter(#fromJson),
        ),
        returnValueForMissingStub: (Map<String, dynamic> json) =>
            _FakePerson_22(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as _i2.Person Function(Map<String, dynamic>));

  @override
  _i2.DBGraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeDBGraphQLClient_0(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeDBGraphQLClient_0(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i2.DBGraphQLClient);

  @override
  _i2.StreamableDAOProxy<_i2.Person,
          _i2.Input_PersonsBoolExp, _i2.Input_PersonsOrderBy>
      get streamingProxy => (super.noSuchMethod(
            Invocation.getter(#streamingProxy),
            returnValue: _FakeStreamableDAOProxy_23<_i2.Person,
                _i2.Input_PersonsBoolExp, _i2.Input_PersonsOrderBy>(
              this,
              Invocation.getter(#streamingProxy),
            ),
            returnValueForMissingStub: _FakeStreamableDAOProxy_23<_i2.Person,
                _i2.Input_PersonsBoolExp, _i2.Input_PersonsOrderBy>(
              this,
              Invocation.getter(#streamingProxy),
            ),
          ) as _i2.StreamableDAOProxy<_i2.Person, _i2.Input_PersonsBoolExp,
              _i2.Input_PersonsOrderBy>);

  @override
  _i2.CreatableDAOProxy<_i2.Person> get createObjectProxy =>
      (super.noSuchMethod(
        Invocation.getter(#createObjectProxy),
        returnValue: _FakeCreatableDAOProxy_24<_i2.Person>(
          this,
          Invocation.getter(#createObjectProxy),
        ),
        returnValueForMissingStub: _FakeCreatableDAOProxy_24<_i2.Person>(
          this,
          Invocation.getter(#createObjectProxy),
        ),
      ) as _i2.CreatableDAOProxy<_i2.Person>);

  @override
  _i2.UpdatableDAOProxy<_i2.Person> get updateObjectProxy =>
      (super.noSuchMethod(
        Invocation.getter(#updateObjectProxy),
        returnValue: _FakeUpdatableDAOProxy_25<_i2.Person>(
          this,
          Invocation.getter(#updateObjectProxy),
        ),
        returnValueForMissingStub: _FakeUpdatableDAOProxy_25<_i2.Person>(
          this,
          Invocation.getter(#updateObjectProxy),
        ),
      ) as _i2.UpdatableDAOProxy<_i2.Person>);

  @override
  _i2.DeletableDAOProxy<_i2.Person> get deleteSingleByIdProxy =>
      (super.noSuchMethod(
        Invocation.getter(#deleteSingleByIdProxy),
        returnValue: _FakeDeletableDAOProxy_26<_i2.Person>(
          this,
          Invocation.getter(#deleteSingleByIdProxy),
        ),
        returnValueForMissingStub: _FakeDeletableDAOProxy_26<_i2.Person>(
          this,
          Invocation.getter(#deleteSingleByIdProxy),
        ),
      ) as _i2.DeletableDAOProxy<_i2.Person>);

  @override
  _i5.Stream<_i2.Person?> streamSingleById({
    required String? id,
    int? servicesLimit = 6,
    int? classesLimit = 6,
    int? groupsLimit = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamSingleById,
          [],
          {
            #id: id,
            #servicesLimit: servicesLimit,
            #classesLimit: classesLimit,
            #groupsLimit: groupsLimit,
          },
        ),
        returnValue: _i5.Stream<_i2.Person?>.empty(),
        returnValueForMissingStub: _i5.Stream<_i2.Person?>.empty(),
      ) as _i5.Stream<_i2.Person?>);

  @override
  _i5.Future<_i2.Person?> personServicesClassesGroups(
          {required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #personServicesClassesGroups,
          [],
          {#personId: personId},
        ),
        returnValue: _i5.Future<_i2.Person?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Person?>.value(),
      ) as _i5.Future<_i2.Person?>);

  @override
  _i5.Future<_i2.PersonsGeolocationsResponse?> personsGeolocations({
    String? personId,
    List<_i2.UuidValue>? areasIds = const [],
    List<_i2.UuidValue>? streetsIds = const [],
    List<_i2.UuidValue>? familiesIds = const [],
    List<_i2.UuidValue>? storesIds = const [],
    List<_i2.UuidValue>? servicesIds = const [],
    List<_i2.UuidValue>? classesIds = const [],
    List<_i2.UuidValue>? groupsIds = const [],
    bool? getAreas = false,
    bool? getStreets = false,
    bool? getFamilies = false,
    bool? getStores = false,
    bool? getPersons = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #personsGeolocations,
          [],
          {
            #personId: personId,
            #areasIds: areasIds,
            #streetsIds: streetsIds,
            #familiesIds: familiesIds,
            #storesIds: storesIds,
            #servicesIds: servicesIds,
            #classesIds: classesIds,
            #groupsIds: groupsIds,
            #getAreas: getAreas,
            #getStreets: getStreets,
            #getFamilies: getFamilies,
            #getStores: getStores,
            #getPersons: getPersons,
          },
        ),
        returnValue: _i5.Future<_i2.PersonsGeolocationsResponse?>.value(),
        returnValueForMissingStub:
            _i5.Future<_i2.PersonsGeolocationsResponse?>.value(),
      ) as _i5.Future<_i2.PersonsGeolocationsResponse?>);

  @override
  _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>
      paginatePersonClassAttendance({
    required String? personId,
    required String? classId,
    bool? asAdmin = false,
    List<_i2.Input_HistoryAttendanceHistoryBoolExp>? where,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonClassAttendance,
              [],
              {
                #personId: personId,
                #classId: classId,
                #asAdmin: asAdmin,
                #where: where,
              },
            ),
            returnValue: _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonClassAttendance,
                [],
                {
                  #personId: personId,
                  #classId: classId,
                  #asAdmin: asAdmin,
                  #where: where,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonClassAttendance,
                [],
                {
                  #personId: personId,
                  #classId: classId,
                  #asAdmin: asAdmin,
                  #where: where,
                },
              ),
            ),
          ) as _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>);

  @override
  _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>
      paginatePersonGroupAttendance({
    required String? personId,
    required String? groupId,
    bool? asAdmin = false,
    List<_i2.Input_HistoryAttendanceHistoryBoolExp>? where,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonGroupAttendance,
              [],
              {
                #personId: personId,
                #groupId: groupId,
                #asAdmin: asAdmin,
                #where: where,
              },
            ),
            returnValue: _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonGroupAttendance,
                [],
                {
                  #personId: personId,
                  #groupId: groupId,
                  #asAdmin: asAdmin,
                  #where: where,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonGroupAttendance,
                [],
                {
                  #personId: personId,
                  #groupId: groupId,
                  #asAdmin: asAdmin,
                  #where: where,
                },
              ),
            ),
          ) as _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>);

  @override
  _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>
      paginatePersonServiceAttendance({
    required String? personId,
    required String? serviceId,
    bool? asAdmin = false,
    List<_i2.Input_HistoryAttendanceHistoryBoolExp>? where,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonServiceAttendance,
              [],
              {
                #personId: personId,
                #serviceId: serviceId,
                #asAdmin: asAdmin,
                #where: where,
              },
            ),
            returnValue: _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonServiceAttendance,
                [],
                {
                  #personId: personId,
                  #serviceId: serviceId,
                  #asAdmin: asAdmin,
                  #where: where,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonServiceAttendance,
                [],
                {
                  #personId: personId,
                  #serviceId: serviceId,
                  #asAdmin: asAdmin,
                  #where: where,
                },
              ),
            ),
          ) as _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>);

  @override
  _i2.GQLPaginatableStream<_i2.LastRecordedByInfo> paginatePersonAttendance({
    required _i6.Variables_Subscription_personAttendance Function(
      int,
      _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>,
    )? vars,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersonAttendance,
          [],
          {
            #vars: vars,
            #limit: limit,
          },
        ),
        returnValue: _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonAttendance,
            [],
            {
              #vars: vars,
              #limit: limit,
            },
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_27<_i2.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonAttendance,
            [],
            {
              #vars: vars,
              #limit: limit,
            },
          ),
        ),
      ) as _i2.GQLPaginatableStream<_i2.LastRecordedByInfo>);

  @override
  _i5.Future<_i2.Person?> getPersonAnalysis({
    required String? personId,
    required _i2.PersonAnalysisOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonAnalysis,
          [],
          {
            #personId: personId,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i2.Person?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Person?>.value(),
      ) as _i5.Future<_i2.Person?>);

  @override
  _i5.Future<_i2.Person?> updatePersonSpiritData({
    required String? personId,
    required DateTime? lastConfession,
    required DateTime? lastKodas,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonSpiritData,
          [],
          {
            #personId: personId,
            #lastConfession: lastConfession,
            #lastKodas: lastKodas,
          },
        ),
        returnValue: _i5.Future<_i2.Person?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Person?>.value(),
      ) as _i5.Future<_i2.Person?>);

  @override
  _i2.GQLPaginatableStream<_i2.Person> streamAll({
    _i5.Stream<String?>? searchQuery,
    List<_i2.Input_PersonsBoolExp>? where,
    List<_i2.Input_PersonsOrderBy>? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamAll,
          [],
          {
            #searchQuery: searchQuery,
            #where: where,
            #orderBy: orderBy,
          },
        ),
        returnValue: _FakeGQLPaginatableStream_27<_i2.Person>(
          this,
          Invocation.method(
            #streamAll,
            [],
            {
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
            },
          ),
        ),
        returnValueForMissingStub: _FakeGQLPaginatableStream_27<_i2.Person>(
          this,
          Invocation.method(
            #streamAll,
            [],
            {
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
            },
          ),
        ),
      ) as _i2.GQLPaginatableStream<_i2.Person>);

  @override
  _i5.Future<_i2.Person> createObject({required _i2.Person? newObject}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createObject,
          [],
          {#newObject: newObject},
        ),
        returnValue: _i5.Future<_i2.Person>.value(_FakePerson_22(
          this,
          Invocation.method(
            #createObject,
            [],
            {#newObject: newObject},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Person>.value(_FakePerson_22(
          this,
          Invocation.method(
            #createObject,
            [],
            {#newObject: newObject},
          ),
        )),
      ) as _i5.Future<_i2.Person>);

  @override
  _i5.Future<_i2.Person?> updateObject({
    required _i2.Person? newObject,
    required _i2.Person? oldObject,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateObject,
          [],
          {
            #newObject: newObject,
            #oldObject: oldObject,
          },
        ),
        returnValue: _i5.Future<_i2.Person?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Person?>.value(),
      ) as _i5.Future<_i2.Person?>);

  @override
  _i5.Future<_i2.Person?> deleteById({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [],
          {#id: id},
        ),
        returnValue: _i5.Future<_i2.Person?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Person?>.value(),
      ) as _i5.Future<_i2.Person?>);
}

/// A class which mocks [StreamableDAOProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamableDAOProxy<T extends _i2.ViewableWithID, TBoolExp,
        TOrderByExp> extends _i1.Mock
    implements _i2.StreamableDAOProxy<T, TBoolExp, TOrderByExp> {
  @override
  _i2.DatabaseService get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseService_21(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabaseService_21(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.DatabaseService);

  @override
  T Function(Map<String, dynamic>) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (Map<String, dynamic> json) => _i7.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
        returnValueForMissingStub: (Map<String, dynamic> json) =>
            _i7.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as T Function(Map<String, dynamic>));

  @override
  _i2.DBGraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeDBGraphQLClient_0(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeDBGraphQLClient_0(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i2.DBGraphQLClient);

  @override
  _i2.GQLPaginatableStream<T> streamAll({
    required _i2.StreamAllConfig<T, TBoolExp, TOrderByExp>? streamAllConfig,
    _i5.Stream<String?>? searchQuery,
    List<TBoolExp>? where,
    List<TOrderByExp>? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamAll,
          [],
          {
            #streamAllConfig: streamAllConfig,
            #searchQuery: searchQuery,
            #where: where,
            #orderBy: orderBy,
          },
        ),
        returnValue: _FakeGQLPaginatableStream_27<T>(
          this,
          Invocation.method(
            #streamAll,
            [],
            {
              #streamAllConfig: streamAllConfig,
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
            },
          ),
        ),
        returnValueForMissingStub: _FakeGQLPaginatableStream_27<T>(
          this,
          Invocation.method(
            #streamAll,
            [],
            {
              #streamAllConfig: streamAllConfig,
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
            },
          ),
        ),
      ) as _i2.GQLPaginatableStream<T>);

  @override
  _i5.Stream<T?> streamSingleById({
    required String? id,
    required _i2.StreamSingleByIdConfig<T>? streamSingleByIdConfig,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamSingleById,
          [],
          {
            #id: id,
            #streamSingleByIdConfig: streamSingleByIdConfig,
          },
        ),
        returnValue: _i5.Stream<T?>.empty(),
        returnValueForMissingStub: _i5.Stream<T?>.empty(),
      ) as _i5.Stream<T?>);
}

/// A class which mocks [GQLPaginatableStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockGQLPaginatableStream<T> extends _i1.Mock
    implements _i2.GQLPaginatableStream<T> {
  @override
  _i5.Stream<Iterable<T>> Function(
      _i2
          .GQLPaginatableStreamEvent<T>) get subscriptionStreamCallback =>
      (super.noSuchMethod(
        Invocation.getter(#subscriptionStreamCallback),
        returnValue: (_i2.GQLPaginatableStreamEvent<T> __p0) =>
            _i5.Stream<Iterable<T>>.empty(),
        returnValueForMissingStub: (_i2.GQLPaginatableStreamEvent<T> __p0) =>
            _i5.Stream<Iterable<T>>.empty(),
      ) as _i5.Stream<Iterable<T>> Function(_i2.GQLPaginatableStreamEvent<T>));

  @override
  set lastSearch(String? _lastSearch) => super.noSuchMethod(
        Invocation.setter(
          #lastSearch,
          _lastSearch,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.OnQuery<T> get streamDelegate => (super.noSuchMethod(
        Invocation.getter(#streamDelegate),
        returnValue: (
          _i2.DelegatingPaginatableStream<T> instance,
          _i5.Stream<int> offset,
        ) =>
            _i5.Stream<_i2.DelegatingStreamResult<T>>.empty(),
        returnValueForMissingStub: (
          _i2.DelegatingPaginatableStream<T> instance,
          _i5.Stream<int> offset,
        ) =>
            _i5.Stream<_i2.DelegatingStreamResult<T>>.empty(),
      ) as _i2.OnQuery<T>);

  @override
  _i4.ValueStream<bool> get onLoadingChanged => (super.noSuchMethod(
        Invocation.getter(#onLoadingChanged),
        returnValue: _FakeValueStream_28<bool>(
          this,
          Invocation.getter(#onLoadingChanged),
        ),
        returnValueForMissingStub: _FakeValueStream_28<bool>(
          this,
          Invocation.getter(#onLoadingChanged),
        ),
      ) as _i4.ValueStream<bool>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canPaginateBackward => (super.noSuchMethod(
        Invocation.getter(#canPaginateBackward),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canPaginateForward => (super.noSuchMethod(
        Invocation.getter(#canPaginateForward),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get currentOffset => (super.noSuchMethod(
        Invocation.getter(#currentOffset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.ValueStream<List<T>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _FakeValueStream_28<List<T>>(
          this,
          Invocation.getter(#stream),
        ),
        returnValueForMissingStub: _FakeValueStream_28<List<T>>(
          this,
          Invocation.getter(#stream),
        ),
      ) as _i4.ValueStream<List<T>>);

  @override
  List<T> get currentValue => (super.noSuchMethod(
        Invocation.getter(#currentValue),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as List<T>);

  @override
  int get limit => (super.noSuchMethod(
        Invocation.getter(#limit),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isBroadcast => (super.noSuchMethod(
        Invocation.getter(#isBroadcast),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<int> get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<T>> get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<void> loadPage(int? offset) => (super.noSuchMethod(
        Invocation.method(
          #loadPage,
          [offset],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadNextPage() => (super.noSuchMethod(
        Invocation.method(
          #loadNextPage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadPreviousPage() => (super.noSuchMethod(
        Invocation.method(
          #loadPreviousPage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  T? getCursorForOffset(int? offset) => (super.noSuchMethod(
        Invocation.method(
          #getCursorForOffset,
          [offset],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.StreamSubscription<List<T>> listen(
    void Function(List<T>)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_29<List<T>>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
        returnValueForMissingStub: _FakeStreamSubscription_29<List<T>>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i5.StreamSubscription<List<T>>);

  @override
  _i5.Stream<List<T>> asBroadcastStream({
    void Function(_i5.StreamSubscription<List<T>>)? onListen,
    void Function(_i5.StreamSubscription<List<T>>)? onCancel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #asBroadcastStream,
          [],
          {
            #onListen: onListen,
            #onCancel: onCancel,
          },
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<List<T>> where(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<S> map<S>(S Function(List<T>)? convert) => (super.noSuchMethod(
        Invocation.method(
          #map,
          [convert],
        ),
        returnValue: _i5.Stream<S>.empty(),
        returnValueForMissingStub: _i5.Stream<S>.empty(),
      ) as _i5.Stream<S>);

  @override
  _i5.Stream<E> asyncMap<E>(_i5.FutureOr<E> Function(List<T>)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncMap,
          [convert],
        ),
        returnValue: _i5.Stream<E>.empty(),
        returnValueForMissingStub: _i5.Stream<E>.empty(),
      ) as _i5.Stream<E>);

  @override
  _i5.Stream<E> asyncExpand<E>(_i5.Stream<E>? Function(List<T>)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncExpand,
          [convert],
        ),
        returnValue: _i5.Stream<E>.empty(),
        returnValueForMissingStub: _i5.Stream<E>.empty(),
      ) as _i5.Stream<E>);

  @override
  _i5.Stream<List<T>> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [onError],
          {#test: test},
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<S> expand<S>(Iterable<S> Function(List<T>)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [convert],
        ),
        returnValue: _i5.Stream<S>.empty(),
        returnValueForMissingStub: _i5.Stream<S>.empty(),
      ) as _i5.Stream<S>);

  @override
  _i5.Future<dynamic> pipe(_i5.StreamConsumer<List<T>>? streamConsumer) =>
      (super.noSuchMethod(
        Invocation.method(
          #pipe,
          [streamConsumer],
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Stream<S> transform<S>(
          _i5.StreamTransformer<List<T>, S>? streamTransformer) =>
      (super.noSuchMethod(
        Invocation.method(
          #transform,
          [streamTransformer],
        ),
        returnValue: _i5.Stream<S>.empty(),
        returnValueForMissingStub: _i5.Stream<S>.empty(),
      ) as _i5.Stream<S>);

  @override
  _i5.Future<List<T>> reduce(
          List<T> Function(
            List<T>,
            List<T>,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<S> fold<S>(
    S? initialValue,
    S Function(
      S,
      List<T>,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<S>(
                this,
                Invocation.method(
                  #fold,
                  [
                    initialValue,
                    combine,
                  ],
                ),
              ),
              (S v) => _i5.Future<S>.value(v),
            ) ??
            _FakeFuture_30<S>(
              this,
              Invocation.method(
                #fold,
                [
                  initialValue,
                  combine,
                ],
              ),
            ),
        returnValueForMissingStub: _i7.ifNotNull(
              _i7.dummyValueOrNull<S>(
                this,
                Invocation.method(
                  #fold,
                  [
                    initialValue,
                    combine,
                  ],
                ),
              ),
              (S v) => _i5.Future<S>.value(v),
            ) ??
            _FakeFuture_30<S>(
              this,
              Invocation.method(
                #fold,
                [
                  initialValue,
                  combine,
                ],
              ),
            ),
      ) as _i5.Future<S>);

  @override
  _i5.Future<String> join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> contains(Object? needle) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [needle],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> forEach(void Function(List<T>)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> every(bool Function(List<T>)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> any(bool Function(List<T>)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Stream<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: _i5.Stream<R>.empty(),
        returnValueForMissingStub: _i5.Stream<R>.empty(),
      ) as _i5.Stream<R>);

  @override
  _i5.Future<List<List<T>>> toList() => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
        ),
        returnValue: _i5.Future<List<List<T>>>.value(<List<T>>[]),
        returnValueForMissingStub: _i5.Future<List<List<T>>>.value(<List<T>>[]),
      ) as _i5.Future<List<List<T>>>);

  @override
  _i5.Future<Set<List<T>>> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: _i5.Future<Set<List<T>>>.value(<List<T>>{}),
        returnValueForMissingStub: _i5.Future<Set<List<T>>>.value(<List<T>>{}),
      ) as _i5.Future<Set<List<T>>>);

  @override
  _i5.Future<E> drain<E>([E? futureValue]) => (super.noSuchMethod(
        Invocation.method(
          #drain,
          [futureValue],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<E>(
                this,
                Invocation.method(
                  #drain,
                  [futureValue],
                ),
              ),
              (E v) => _i5.Future<E>.value(v),
            ) ??
            _FakeFuture_30<E>(
              this,
              Invocation.method(
                #drain,
                [futureValue],
              ),
            ),
        returnValueForMissingStub: _i7.ifNotNull(
              _i7.dummyValueOrNull<E>(
                this,
                Invocation.method(
                  #drain,
                  [futureValue],
                ),
              ),
              (E v) => _i5.Future<E>.value(v),
            ) ??
            _FakeFuture_30<E>(
              this,
              Invocation.method(
                #drain,
                [futureValue],
              ),
            ),
      ) as _i5.Future<E>);

  @override
  _i5.Stream<List<T>> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<List<T>> takeWhile(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<List<T>> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<List<T>> skipWhile(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Stream<List<T>> distinct(
          [bool Function(
            List<T>,
            List<T>,
          )? equals]) =>
      (super.noSuchMethod(
        Invocation.method(
          #distinct,
          [equals],
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);

  @override
  _i5.Future<List<T>> firstWhere(
    bool Function(List<T>)? test, {
    List<T> Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> lastWhere(
    bool Function(List<T>)? test, {
    List<T> Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> singleWhere(
    bool Function(List<T>)? test, {
    List<T> Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Future<List<T>> elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _i5.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i5.Future<List<T>>.value(<T>[]),
      ) as _i5.Future<List<T>>);

  @override
  _i5.Stream<List<T>> timeout(
    Duration? timeLimit, {
    void Function(_i5.EventSink<List<T>>)? onTimeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeout,
          [timeLimit],
          {#onTimeout: onTimeout},
        ),
        returnValue: _i5.Stream<List<T>>.empty(),
        returnValueForMissingStub: _i5.Stream<List<T>>.empty(),
      ) as _i5.Stream<List<T>>);
}

/// A class which mocks [GQLPaginatableStreamEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockGQLPaginatableStreamEvent<T> extends _i1.Mock
    implements _i2.GQLPaginatableStreamEvent<T> {
  @override
  int get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i2.GQLPaginatableStream<T> get instance => (super.noSuchMethod(
        Invocation.getter(#instance),
        returnValue: _FakeGQLPaginatableStream_27<T>(
          this,
          Invocation.getter(#instance),
        ),
        returnValueForMissingStub: _FakeGQLPaginatableStream_27<T>(
          this,
          Invocation.getter(#instance),
        ),
      ) as _i2.GQLPaginatableStream<T>);
}

/// A class which mocks [DBVarsTransformer].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBVarsTransformer extends _i1.Mock implements _i2.DBVarsTransformer {
  @override
  Map<String, dynamic>
      transformVariablesForPagination<T extends _i2.ViewableWithID>(
    _i2.GQLPaginatableStreamEvent<T>? event, {
    List<Map<String, dynamic>>? where = const [],
    List<Map<String, dynamic>>? orderBy = const [
      {r'name': r'ASC'}
    ],
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #transformVariablesForPagination,
              [event],
              {
                #where: where,
                #orderBy: orderBy,
              },
            ),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          ) as Map<String, dynamic>);
}
