// Mocks generated by Mockito 5.4.6 from annotations
// in church_admin/test/src/features/advanced_search/application/advanced_query_parser_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:church_admin/church_admin.dart' as _i2;
import 'package:church_admin/src/core/services/database/gql_definintions/persons/persons_notifications_queries.dart'
    as _i5;
import 'package:graphql/client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDBGraphQLClient_0 extends _i1.SmartFake
    implements _i2.DBGraphQLClient {
  _FakeDBGraphQLClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGQLParser_1 extends _i1.SmartFake implements _i2.GQLParser {
  _FakeGQLParser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDBVarsTransformer_2 extends _i1.SmartFake
    implements _i2.DBVarsTransformer {
  _FakeDBVarsTransformer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdvancedQueryParser_3 extends _i1.SmartFake
    implements _i2.AdvancedQueryParser {
  _FakeAdvancedQueryParser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeDAO_4 extends _i1.SmartFake implements _i2.HomeDAO {
  _FakeHomeDAO_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAreasDAO_5 extends _i1.SmartFake implements _i2.AreasDAO {
  _FakeAreasDAO_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreetsDAO_6 extends _i1.SmartFake implements _i2.StreetsDAO {
  _FakeStreetsDAO_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFamiliesDAO_7 extends _i1.SmartFake implements _i2.FamiliesDAO {
  _FakeFamiliesDAO_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoresDAO_8 extends _i1.SmartFake implements _i2.StoresDAO {
  _FakeStoresDAO_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonsDAO_9 extends _i1.SmartFake implements _i2.PersonsDAO {
  _FakePersonsDAO_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServicesDAO_10 extends _i1.SmartFake implements _i2.ServicesDAO {
  _FakeServicesDAO_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClassesDAO_11 extends _i1.SmartFake implements _i2.ClassesDAO {
  _FakeClassesDAO_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGroupsDAO_12 extends _i1.SmartFake implements _i2.GroupsDAO {
  _FakeGroupsDAO_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersDAO_13 extends _i1.SmartFake implements _i2.UsersDAO {
  _FakeUsersDAO_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPermissionsDAO_14 extends _i1.SmartFake
    implements _i2.UserPermissionsDAO {
  _FakeUserPermissionsDAO_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPreferencesDAO_15 extends _i1.SmartFake
    implements _i2.UserPreferencesDAO {
  _FakeUserPreferencesDAO_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFcmTokensDAO_16 extends _i1.SmartFake implements _i2.FcmTokensDAO {
  _FakeFcmTokensDAO_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetadataDAO_17 extends _i1.SmartFake implements _i2.MetadataDAO {
  _FakeMetadataDAO_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistoryDAO_18 extends _i1.SmartFake implements _i2.HistoryDAO {
  _FakeHistoryDAO_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMeetingsDAO_19 extends _i1.SmartFake implements _i2.MeetingsDAO {
  _FakeMeetingsDAO_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefaultPolicies_20 extends _i1.SmartFake
    implements _i3.DefaultPolicies {
  _FakeDefaultPolicies_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLink_21 extends _i1.SmartFake implements _i3.Link {
  _FakeLink_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLCache_22 extends _i1.SmartFake implements _i3.GraphQLCache {
  _FakeGraphQLCache_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryManager_23 extends _i1.SmartFake implements _i3.QueryManager {
  _FakeQueryManager_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryResult_24<TParsed1 extends Object?> extends _i1.SmartFake
    implements _i3.QueryResult<TParsed1> {
  _FakeQueryResult_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_25<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLClient_26 extends _i1.SmartFake implements _i3.GraphQLClient {
  _FakeGraphQLClient_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObservableQuery_27<TParsed1> extends _i1.SmartFake
    implements _i3.ObservableQuery<TParsed1> {
  _FakeObservableQuery_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonsNotificationsQueries_28 extends _i1.SmartFake
    implements _i5.PersonsNotificationsQueries {
  _FakePersonsNotificationsQueries_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeStreamAllConfig_29<T> extends _i1.SmartFake
    implements _i2.StreamAllConfig<T> {
  _FakeStreamAllConfig_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamCountConfig_30<T> extends _i1.SmartFake
    implements _i2.StreamCountConfig<T> {
  _FakeStreamCountConfig_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSingleByIdConfig_31<T> extends _i1.SmartFake
    implements _i2.StreamSingleByIdConfig<T> {
  _FakeStreamSingleByIdConfig_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteSingleByIdConfig_32<T> extends _i1.SmartFake
    implements _i2.DeleteSingleByIdConfig<T> {
  _FakeDeleteSingleByIdConfig_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateObjectConfig_33<T> extends _i1.SmartFake
    implements _i2.UpdateObjectConfig<T> {
  _FakeUpdateObjectConfig_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateObjectConfig_34<T> extends _i1.SmartFake
    implements _i2.CreateObjectConfig<T> {
  _FakeCreateObjectConfig_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseService_35 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePerson_36 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamableDAOProxy_37<T extends _i2.ViewableWithID>
    extends _i1.SmartFake
    implements _i2.StreamableDAOProxy<T> {
  _FakeStreamableDAOProxy_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatableDAOProxy_38<T extends _i2.ViewableWithID>
    extends _i1.SmartFake
    implements _i2.CreatableDAOProxy<T> {
  _FakeCreatableDAOProxy_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdatableDAOProxy_39<T extends _i2.ViewableWithID>
    extends _i1.SmartFake
    implements _i2.UpdatableDAOProxy<T> {
  _FakeUpdatableDAOProxy_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeletableDAOProxy_40<T extends _i2.ViewableWithID>
    extends _i1.SmartFake
    implements _i2.DeletableDAOProxy<T> {
  _FakeDeletableDAOProxy_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatableStreamBase_41<T> extends _i1.SmartFake
    implements _i2.PaginatableStreamBase<T> {
  _FakePaginatableStreamBase_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSubscription_42<T1> extends _i1.SmartFake
    implements _i4.StreamSubscription<T1> {
  _FakeStreamSubscription_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  @override
  _i2.DBGraphQLClient get graphQLClient =>
      (super.noSuchMethod(
            Invocation.getter(#graphQLClient),
            returnValue: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
            returnValueForMissingStub: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
          )
          as _i2.DBGraphQLClient);

  @override
  _i2.GQLParser get parser =>
      (super.noSuchMethod(
            Invocation.getter(#parser),
            returnValue: _FakeGQLParser_1(this, Invocation.getter(#parser)),
            returnValueForMissingStub: _FakeGQLParser_1(
              this,
              Invocation.getter(#parser),
            ),
          )
          as _i2.GQLParser);

  @override
  _i2.DBVarsTransformer get varsTransformer =>
      (super.noSuchMethod(
            Invocation.getter(#varsTransformer),
            returnValue: _FakeDBVarsTransformer_2(
              this,
              Invocation.getter(#varsTransformer),
            ),
            returnValueForMissingStub: _FakeDBVarsTransformer_2(
              this,
              Invocation.getter(#varsTransformer),
            ),
          )
          as _i2.DBVarsTransformer);

  @override
  _i2.AdvancedQueryParser get advancedQueryParser =>
      (super.noSuchMethod(
            Invocation.getter(#advancedQueryParser),
            returnValue: _FakeAdvancedQueryParser_3(
              this,
              Invocation.getter(#advancedQueryParser),
            ),
            returnValueForMissingStub: _FakeAdvancedQueryParser_3(
              this,
              Invocation.getter(#advancedQueryParser),
            ),
          )
          as _i2.AdvancedQueryParser);

  @override
  _i2.HomeDAO get home =>
      (super.noSuchMethod(
            Invocation.getter(#home),
            returnValue: _FakeHomeDAO_4(this, Invocation.getter(#home)),
            returnValueForMissingStub: _FakeHomeDAO_4(
              this,
              Invocation.getter(#home),
            ),
          )
          as _i2.HomeDAO);

  @override
  _i2.AreasDAO get areas =>
      (super.noSuchMethod(
            Invocation.getter(#areas),
            returnValue: _FakeAreasDAO_5(this, Invocation.getter(#areas)),
            returnValueForMissingStub: _FakeAreasDAO_5(
              this,
              Invocation.getter(#areas),
            ),
          )
          as _i2.AreasDAO);

  @override
  _i2.StreetsDAO get streets =>
      (super.noSuchMethod(
            Invocation.getter(#streets),
            returnValue: _FakeStreetsDAO_6(this, Invocation.getter(#streets)),
            returnValueForMissingStub: _FakeStreetsDAO_6(
              this,
              Invocation.getter(#streets),
            ),
          )
          as _i2.StreetsDAO);

  @override
  _i2.FamiliesDAO get families =>
      (super.noSuchMethod(
            Invocation.getter(#families),
            returnValue: _FakeFamiliesDAO_7(this, Invocation.getter(#families)),
            returnValueForMissingStub: _FakeFamiliesDAO_7(
              this,
              Invocation.getter(#families),
            ),
          )
          as _i2.FamiliesDAO);

  @override
  _i2.StoresDAO get stores =>
      (super.noSuchMethod(
            Invocation.getter(#stores),
            returnValue: _FakeStoresDAO_8(this, Invocation.getter(#stores)),
            returnValueForMissingStub: _FakeStoresDAO_8(
              this,
              Invocation.getter(#stores),
            ),
          )
          as _i2.StoresDAO);

  @override
  _i2.PersonsDAO get persons =>
      (super.noSuchMethod(
            Invocation.getter(#persons),
            returnValue: _FakePersonsDAO_9(this, Invocation.getter(#persons)),
            returnValueForMissingStub: _FakePersonsDAO_9(
              this,
              Invocation.getter(#persons),
            ),
          )
          as _i2.PersonsDAO);

  @override
  _i2.ServicesDAO get services =>
      (super.noSuchMethod(
            Invocation.getter(#services),
            returnValue: _FakeServicesDAO_10(
              this,
              Invocation.getter(#services),
            ),
            returnValueForMissingStub: _FakeServicesDAO_10(
              this,
              Invocation.getter(#services),
            ),
          )
          as _i2.ServicesDAO);

  @override
  _i2.ClassesDAO get classes =>
      (super.noSuchMethod(
            Invocation.getter(#classes),
            returnValue: _FakeClassesDAO_11(this, Invocation.getter(#classes)),
            returnValueForMissingStub: _FakeClassesDAO_11(
              this,
              Invocation.getter(#classes),
            ),
          )
          as _i2.ClassesDAO);

  @override
  _i2.GroupsDAO get groups =>
      (super.noSuchMethod(
            Invocation.getter(#groups),
            returnValue: _FakeGroupsDAO_12(this, Invocation.getter(#groups)),
            returnValueForMissingStub: _FakeGroupsDAO_12(
              this,
              Invocation.getter(#groups),
            ),
          )
          as _i2.GroupsDAO);

  @override
  _i2.UsersDAO get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeUsersDAO_13(this, Invocation.getter(#users)),
            returnValueForMissingStub: _FakeUsersDAO_13(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i2.UsersDAO);

  @override
  _i2.UserPermissionsDAO get userPermissions =>
      (super.noSuchMethod(
            Invocation.getter(#userPermissions),
            returnValue: _FakeUserPermissionsDAO_14(
              this,
              Invocation.getter(#userPermissions),
            ),
            returnValueForMissingStub: _FakeUserPermissionsDAO_14(
              this,
              Invocation.getter(#userPermissions),
            ),
          )
          as _i2.UserPermissionsDAO);

  @override
  _i2.UserPreferencesDAO get userPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#userPreferences),
            returnValue: _FakeUserPreferencesDAO_15(
              this,
              Invocation.getter(#userPreferences),
            ),
            returnValueForMissingStub: _FakeUserPreferencesDAO_15(
              this,
              Invocation.getter(#userPreferences),
            ),
          )
          as _i2.UserPreferencesDAO);

  @override
  _i2.FcmTokensDAO get fcmTokens =>
      (super.noSuchMethod(
            Invocation.getter(#fcmTokens),
            returnValue: _FakeFcmTokensDAO_16(
              this,
              Invocation.getter(#fcmTokens),
            ),
            returnValueForMissingStub: _FakeFcmTokensDAO_16(
              this,
              Invocation.getter(#fcmTokens),
            ),
          )
          as _i2.FcmTokensDAO);

  @override
  _i2.MetadataDAO get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeMetadataDAO_17(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeMetadataDAO_17(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.MetadataDAO);

  @override
  _i2.HistoryDAO get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: _FakeHistoryDAO_18(this, Invocation.getter(#history)),
            returnValueForMissingStub: _FakeHistoryDAO_18(
              this,
              Invocation.getter(#history),
            ),
          )
          as _i2.HistoryDAO);

  @override
  _i2.MeetingsDAO get meetings =>
      (super.noSuchMethod(
            Invocation.getter(#meetings),
            returnValue: _FakeMeetingsDAO_19(
              this,
              Invocation.getter(#meetings),
            ),
            returnValueForMissingStub: _FakeMeetingsDAO_19(
              this,
              Invocation.getter(#meetings),
            ),
          )
          as _i2.MeetingsDAO);

  @override
  Map<Type, _i2.DAOBase<_i2.ViewableWithID>> get daosByType =>
      (super.noSuchMethod(
            Invocation.getter(#daosByType),
            returnValue: <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
            returnValueForMissingStub:
                <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
          )
          as Map<Type, _i2.DAOBase<_i2.ViewableWithID>>);
}

/// A class which mocks [DBGraphQLClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBGraphQLClient extends _i1.Mock implements _i2.DBGraphQLClient {
  @override
  bool get autoChangeFetchPolicy =>
      (super.noSuchMethod(
            Invocation.getter(#autoChangeFetchPolicy),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.DefaultPolicies get defaultPolicies =>
      (super.noSuchMethod(
            Invocation.getter(#defaultPolicies),
            returnValue: _FakeDefaultPolicies_20(
              this,
              Invocation.getter(#defaultPolicies),
            ),
            returnValueForMissingStub: _FakeDefaultPolicies_20(
              this,
              Invocation.getter(#defaultPolicies),
            ),
          )
          as _i3.DefaultPolicies);

  @override
  _i3.Link get link =>
      (super.noSuchMethod(
            Invocation.getter(#link),
            returnValue: _FakeLink_21(this, Invocation.getter(#link)),
            returnValueForMissingStub: _FakeLink_21(
              this,
              Invocation.getter(#link),
            ),
          )
          as _i3.Link);

  @override
  _i3.GraphQLCache get cache =>
      (super.noSuchMethod(
            Invocation.getter(#cache),
            returnValue: _FakeGraphQLCache_22(this, Invocation.getter(#cache)),
            returnValueForMissingStub: _FakeGraphQLCache_22(
              this,
              Invocation.getter(#cache),
            ),
          )
          as _i3.GraphQLCache);

  @override
  _i3.QueryManager get queryManager =>
      (super.noSuchMethod(
            Invocation.getter(#queryManager),
            returnValue: _FakeQueryManager_23(
              this,
              Invocation.getter(#queryManager),
            ),
            returnValueForMissingStub: _FakeQueryManager_23(
              this,
              Invocation.getter(#queryManager),
            ),
          )
          as _i3.QueryManager);

  @override
  set defaultPolicies(_i3.DefaultPolicies? value) => super.noSuchMethod(
    Invocation.setter(#defaultPolicies, value),
    returnValueForMissingStub: null,
  );

  @override
  set queryManager(_i3.QueryManager? value) => super.noSuchMethod(
    Invocation.setter(#queryManager, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i3.QueryResult<TParsed>> mutate<TParsed>(
    _i3.MutationOptions<TParsed>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutate,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue: _i4.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_24<TParsed>(
                this,
                Invocation.method(
                  #mutate,
                  [options],
                  {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_24<TParsed>(
                    this,
                    Invocation.method(
                      #mutate,
                      [options],
                      {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i3.QueryResult<TParsed>>);

  @override
  _i4.Future<T?> mutateAndReturnParsedNullable<T>(
    _i3.MutationOptions<T?>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutateAndReturnParsedNullable,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue: _i4.Future<T?>.value(),
            returnValueForMissingStub: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<T> mutateAndReturnParsed<T>(
    _i3.MutationOptions<T>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutateAndReturnParsed,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #mutateAndReturnParsed,
                      [options],
                      {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(
                    #mutateAndReturnParsed,
                    [options],
                    {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                  ),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #mutateAndReturnParsed,
                      [options],
                      {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(
                    #mutateAndReturnParsed,
                    [options],
                    {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                  ),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Stream<_i3.QueryResult<TParsed>> subscribe<TParsed>(
    _i3.SubscriptionOptions<TParsed>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue: _i4.Stream<_i3.QueryResult<TParsed>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i3.QueryResult<TParsed>>.empty(),
          )
          as _i4.Stream<_i3.QueryResult<TParsed>>);

  @override
  _i4.Stream<T?> subscribeAndReturnParsedNullable<T>(
    _i3.SubscriptionOptions<T?>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeAndReturnParsedNullable,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue: _i4.Stream<T?>.empty(),
            returnValueForMissingStub: _i4.Stream<T?>.empty(),
          )
          as _i4.Stream<T?>);

  @override
  _i4.Stream<T> subscribeAndReturnParsed<T>(
    _i3.SubscriptionOptions<T>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeAndReturnParsed, [options]),
            returnValue: _i4.Stream<T>.empty(),
            returnValueForMissingStub: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<T?> watchQueryAndReturnParsedNullable<T>(
    _i3.WatchQueryOptions<T?>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchQueryAndReturnParsedNullable, [options]),
            returnValue: _i4.Stream<T?>.empty(),
            returnValueForMissingStub: _i4.Stream<T?>.empty(),
          )
          as _i4.Stream<T?>);

  @override
  _i4.Stream<T> watchQueryAndReturnParsed<T>(
    _i3.WatchQueryOptions<T>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchQueryAndReturnParsed, [options]),
            returnValue: _i4.Stream<T>.empty(),
            returnValueForMissingStub: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Future<_i3.QueryResult<TParsed>> query<TParsed>(
    _i3.QueryOptions<TParsed>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue: _i4.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_24<TParsed>(
                this,
                Invocation.method(
                  #query,
                  [options],
                  {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_24<TParsed>(
                    this,
                    Invocation.method(
                      #query,
                      [options],
                      {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i3.QueryResult<TParsed>>);

  @override
  _i4.Future<T?> queryAndReturnParsedNullable<T>(
    _i3.QueryOptions<T?>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryAndReturnParsedNullable,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue: _i4.Future<T?>.value(),
            returnValueForMissingStub: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<T> queryAndReturnParsed<T>(
    _i3.QueryOptions<T>? options, {
    bool? autoChangeFetchPolicy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryAndReturnParsed,
              [options],
              {#autoChangeFetchPolicy: autoChangeFetchPolicy},
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #queryAndReturnParsed,
                      [options],
                      {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(
                    #queryAndReturnParsed,
                    [options],
                    {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                  ),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #queryAndReturnParsed,
                      [options],
                      {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(
                    #queryAndReturnParsed,
                    [options],
                    {#autoChangeFetchPolicy: autoChangeFetchPolicy},
                  ),
                ),
          )
          as _i4.Future<T>);

  @override
  _i3.GraphQLClient copyWith({
    _i3.Link? link,
    _i3.GraphQLCache? cache,
    _i3.DefaultPolicies? defaultPolicies,
    bool? alwaysRebroadcast,
    _i3.DeepEqualsFn? deepEquals,
    _i3.AsyncDeepEqualsFn? asyncDeepEquals,
    bool? deduplicatePollers = false,
    Duration? queryRequestTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #link: link,
              #cache: cache,
              #defaultPolicies: defaultPolicies,
              #alwaysRebroadcast: alwaysRebroadcast,
              #deepEquals: deepEquals,
              #asyncDeepEquals: asyncDeepEquals,
              #deduplicatePollers: deduplicatePollers,
              #queryRequestTimeout: queryRequestTimeout,
            }),
            returnValue: _FakeGraphQLClient_26(
              this,
              Invocation.method(#copyWith, [], {
                #link: link,
                #cache: cache,
                #defaultPolicies: defaultPolicies,
                #alwaysRebroadcast: alwaysRebroadcast,
                #deepEquals: deepEquals,
                #asyncDeepEquals: asyncDeepEquals,
                #deduplicatePollers: deduplicatePollers,
                #queryRequestTimeout: queryRequestTimeout,
              }),
            ),
            returnValueForMissingStub: _FakeGraphQLClient_26(
              this,
              Invocation.method(#copyWith, [], {
                #link: link,
                #cache: cache,
                #defaultPolicies: defaultPolicies,
                #alwaysRebroadcast: alwaysRebroadcast,
                #deepEquals: deepEquals,
                #asyncDeepEquals: asyncDeepEquals,
                #deduplicatePollers: deduplicatePollers,
                #queryRequestTimeout: queryRequestTimeout,
              }),
            ),
          )
          as _i3.GraphQLClient);

  @override
  _i3.ObservableQuery<TParsed> watchQuery<TParsed>(
    _i3.WatchQueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuery, [options]),
            returnValue: _FakeObservableQuery_27<TParsed>(
              this,
              Invocation.method(#watchQuery, [options]),
            ),
            returnValueForMissingStub: _FakeObservableQuery_27<TParsed>(
              this,
              Invocation.method(#watchQuery, [options]),
            ),
          )
          as _i3.ObservableQuery<TParsed>);

  @override
  _i3.ObservableQuery<TParsed> watchMutation<TParsed>(
    _i3.WatchQueryOptions<TParsed>? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMutation, [options]),
            returnValue: _FakeObservableQuery_27<TParsed>(
              this,
              Invocation.method(#watchMutation, [options]),
            ),
            returnValueForMissingStub: _FakeObservableQuery_27<TParsed>(
              this,
              Invocation.method(#watchMutation, [options]),
            ),
          )
          as _i3.ObservableQuery<TParsed>);

  @override
  _i4.Future<_i3.QueryResult<TParsed>> fetchMore<TParsed>(
    _i3.FetchMoreOptions? fetchMoreOptions, {
    required _i3.QueryOptions<TParsed>? originalOptions,
    required _i3.QueryResult<TParsed>? previousResult,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMore,
              [fetchMoreOptions],
              {
                #originalOptions: originalOptions,
                #previousResult: previousResult,
              },
            ),
            returnValue: _i4.Future<_i3.QueryResult<TParsed>>.value(
              _FakeQueryResult_24<TParsed>(
                this,
                Invocation.method(
                  #fetchMore,
                  [fetchMoreOptions],
                  {
                    #originalOptions: originalOptions,
                    #previousResult: previousResult,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.QueryResult<TParsed>>.value(
                  _FakeQueryResult_24<TParsed>(
                    this,
                    Invocation.method(
                      #fetchMore,
                      [fetchMoreOptions],
                      {
                        #originalOptions: originalOptions,
                        #previousResult: previousResult,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i3.QueryResult<TParsed>>);

  @override
  Map<String, dynamic>? readQuery(
    _i3.Request? request, {
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readQuery, [request], {#optimistic: optimistic}),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  Map<String, dynamic>? readFragment(
    _i3.FragmentRequest? fragmentRequest, {
    bool? optimistic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readFragment,
              [fragmentRequest],
              {#optimistic: optimistic},
            ),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  void writeQuery(
    _i3.Request? request, {
    required Map<String, dynamic>? data,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeQuery,
      [request],
      {#data: data, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void writeFragment(
    _i3.FragmentRequest? fragmentRequest, {
    bool? broadcast = true,
    required Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeFragment,
      [fragmentRequest],
      {#broadcast: broadcast, #data: data},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i3.QueryResult<Object?>?>>? resetStore({
    bool? refetchQueries = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetStore, [], {
              #refetchQueries: refetchQueries,
            }),
            returnValueForMissingStub: null,
          )
          as _i4.Future<List<_i3.QueryResult<Object?>?>>?);
}

/// A class which mocks [PersonsDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonsDAO extends _i1.Mock implements _i2.PersonsDAO {
  @override
  _i5.PersonsNotificationsQueries get notificationsQueries =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsQueries),
            returnValue: _FakePersonsNotificationsQueries_28(
              this,
              Invocation.getter(#notificationsQueries),
            ),
            returnValueForMissingStub: _FakePersonsNotificationsQueries_28(
              this,
              Invocation.getter(#notificationsQueries),
            ),
          )
          as _i5.PersonsNotificationsQueries);

  @override
  _i2.StreamAllConfig<_i2.Person> get baseStreamAllConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseStreamAllConfig),
            returnValue: _FakeStreamAllConfig_29<_i2.Person>(
              this,
              Invocation.getter(#baseStreamAllConfig),
            ),
            returnValueForMissingStub: _FakeStreamAllConfig_29<_i2.Person>(
              this,
              Invocation.getter(#baseStreamAllConfig),
            ),
          )
          as _i2.StreamAllConfig<_i2.Person>);

  @override
  _i2.StreamCountConfig<_i2.Person> get baseStreamCountConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseStreamCountConfig),
            returnValue: _FakeStreamCountConfig_30<_i2.Person>(
              this,
              Invocation.getter(#baseStreamCountConfig),
            ),
            returnValueForMissingStub: _FakeStreamCountConfig_30<_i2.Person>(
              this,
              Invocation.getter(#baseStreamCountConfig),
            ),
          )
          as _i2.StreamCountConfig<_i2.Person>);

  @override
  _i2.StreamSingleByIdConfig<_i2.Person> get baseStreamSingleByIdConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseStreamSingleByIdConfig),
            returnValue: _FakeStreamSingleByIdConfig_31<_i2.Person>(
              this,
              Invocation.getter(#baseStreamSingleByIdConfig),
            ),
            returnValueForMissingStub:
                _FakeStreamSingleByIdConfig_31<_i2.Person>(
                  this,
                  Invocation.getter(#baseStreamSingleByIdConfig),
                ),
          )
          as _i2.StreamSingleByIdConfig<_i2.Person>);

  @override
  _i2.DeleteSingleByIdConfig<_i2.Person> get baseDeleteSingleByIdConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseDeleteSingleByIdConfig),
            returnValue: _FakeDeleteSingleByIdConfig_32<_i2.Person>(
              this,
              Invocation.getter(#baseDeleteSingleByIdConfig),
            ),
            returnValueForMissingStub:
                _FakeDeleteSingleByIdConfig_32<_i2.Person>(
                  this,
                  Invocation.getter(#baseDeleteSingleByIdConfig),
                ),
          )
          as _i2.DeleteSingleByIdConfig<_i2.Person>);

  @override
  _i2.UpdateObjectConfig<_i2.Person> get baseUpdateObjectConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseUpdateObjectConfig),
            returnValue: _FakeUpdateObjectConfig_33<_i2.Person>(
              this,
              Invocation.getter(#baseUpdateObjectConfig),
            ),
            returnValueForMissingStub: _FakeUpdateObjectConfig_33<_i2.Person>(
              this,
              Invocation.getter(#baseUpdateObjectConfig),
            ),
          )
          as _i2.UpdateObjectConfig<_i2.Person>);

  @override
  _i2.CreateObjectConfig<_i2.Person> get baseCreateObjectConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseCreateObjectConfig),
            returnValue: _FakeCreateObjectConfig_34<_i2.Person>(
              this,
              Invocation.getter(#baseCreateObjectConfig),
            ),
            returnValueForMissingStub: _FakeCreateObjectConfig_34<_i2.Person>(
              this,
              Invocation.getter(#baseCreateObjectConfig),
            ),
          )
          as _i2.CreateObjectConfig<_i2.Person>);

  @override
  _i2.DatabaseService get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabaseService_35(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeDatabaseService_35(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i2.Person Function(Map<String, dynamic>) get fromJson =>
      (super.noSuchMethod(
            Invocation.getter(#fromJson),
            returnValue: (Map<String, dynamic> json) =>
                _FakePerson_36(this, Invocation.getter(#fromJson)),
            returnValueForMissingStub: (Map<String, dynamic> json) =>
                _FakePerson_36(this, Invocation.getter(#fromJson)),
          )
          as _i2.Person Function(Map<String, dynamic>));

  @override
  _i2.DBGraphQLClient get graphQLClient =>
      (super.noSuchMethod(
            Invocation.getter(#graphQLClient),
            returnValue: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
            returnValueForMissingStub: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
          )
          as _i2.DBGraphQLClient);

  @override
  _i2.StreamableDAOProxy<_i2.Person> get streamingProxy =>
      (super.noSuchMethod(
            Invocation.getter(#streamingProxy),
            returnValue: _FakeStreamableDAOProxy_37<_i2.Person>(
              this,
              Invocation.getter(#streamingProxy),
            ),
            returnValueForMissingStub: _FakeStreamableDAOProxy_37<_i2.Person>(
              this,
              Invocation.getter(#streamingProxy),
            ),
          )
          as _i2.StreamableDAOProxy<_i2.Person>);

  @override
  _i2.CreatableDAOProxy<_i2.Person> get createObjectProxy =>
      (super.noSuchMethod(
            Invocation.getter(#createObjectProxy),
            returnValue: _FakeCreatableDAOProxy_38<_i2.Person>(
              this,
              Invocation.getter(#createObjectProxy),
            ),
            returnValueForMissingStub: _FakeCreatableDAOProxy_38<_i2.Person>(
              this,
              Invocation.getter(#createObjectProxy),
            ),
          )
          as _i2.CreatableDAOProxy<_i2.Person>);

  @override
  _i2.UpdatableDAOProxy<_i2.Person> get updateObjectProxy =>
      (super.noSuchMethod(
            Invocation.getter(#updateObjectProxy),
            returnValue: _FakeUpdatableDAOProxy_39<_i2.Person>(
              this,
              Invocation.getter(#updateObjectProxy),
            ),
            returnValueForMissingStub: _FakeUpdatableDAOProxy_39<_i2.Person>(
              this,
              Invocation.getter(#updateObjectProxy),
            ),
          )
          as _i2.UpdatableDAOProxy<_i2.Person>);

  @override
  _i2.DeletableDAOProxy<_i2.Person> get deleteSingleByIdProxy =>
      (super.noSuchMethod(
            Invocation.getter(#deleteSingleByIdProxy),
            returnValue: _FakeDeletableDAOProxy_40<_i2.Person>(
              this,
              Invocation.getter(#deleteSingleByIdProxy),
            ),
            returnValueForMissingStub: _FakeDeletableDAOProxy_40<_i2.Person>(
              this,
              Invocation.getter(#deleteSingleByIdProxy),
            ),
          )
          as _i2.DeletableDAOProxy<_i2.Person>);

  @override
  _i4.Stream<_i2.Person?> streamSingleById({
    required String? id,
    int? servicesLimit = 6,
    int? classesLimit = 6,
    int? groupsLimit = 6,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamSingleById, [], {
              #id: id,
              #servicesLimit: servicesLimit,
              #classesLimit: classesLimit,
              #groupsLimit: groupsLimit,
            }),
            returnValue: _i4.Stream<_i2.Person?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.Person?>.empty(),
          )
          as _i4.Stream<_i2.Person?>);

  @override
  _i4.Future<_i2.Person?> personServicesClassesGroups({
    required String? personId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#personServicesClassesGroups, [], {
              #personId: personId,
            }),
            returnValue: _i4.Future<_i2.Person?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Person?>.value(),
          )
          as _i4.Future<_i2.Person?>);

  @override
  _i4.Future<_i2.PersonsGeolocationsResponse?> personsGeolocations({
    String? personId,
    List<_i2.UuidValue>? areasIds = const [],
    List<_i2.UuidValue>? streetsIds = const [],
    List<_i2.UuidValue>? familiesIds = const [],
    List<_i2.UuidValue>? storesIds = const [],
    List<_i2.UuidValue>? servicesIds = const [],
    List<_i2.UuidValue>? classesIds = const [],
    List<_i2.UuidValue>? groupsIds = const [],
    bool? getAreas = false,
    bool? getStreets = false,
    bool? getFamilies = false,
    bool? getStores = false,
    bool? getPersons = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#personsGeolocations, [], {
              #personId: personId,
              #areasIds: areasIds,
              #streetsIds: streetsIds,
              #familiesIds: familiesIds,
              #storesIds: storesIds,
              #servicesIds: servicesIds,
              #classesIds: classesIds,
              #groupsIds: groupsIds,
              #getAreas: getAreas,
              #getStreets: getStreets,
              #getFamilies: getFamilies,
              #getStores: getStores,
              #getPersons: getPersons,
            }),
            returnValue: _i4.Future<_i2.PersonsGeolocationsResponse?>.value(),
            returnValueForMissingStub:
                _i4.Future<_i2.PersonsGeolocationsResponse?>.value(),
          )
          as _i4.Future<_i2.PersonsGeolocationsResponse?>);

  @override
  _i4.Future<_i2.Person?> getPersonAnalysis({
    required String? personId,
    required _i2.PersonAnalysisOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonAnalysis, [], {
              #personId: personId,
              #options: options,
            }),
            returnValue: _i4.Future<_i2.Person?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Person?>.value(),
          )
          as _i4.Future<_i2.Person?>);

  @override
  _i4.Future<_i2.Person?> updatePersonSpiritData({
    required String? personId,
    required DateTime? lastConfession,
    required DateTime? lastKodas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePersonSpiritData, [], {
              #personId: personId,
              #lastConfession: lastConfession,
              #lastKodas: lastKodas,
            }),
            returnValue: _i4.Future<_i2.Person?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Person?>.value(),
          )
          as _i4.Future<_i2.Person?>);

  @override
  _i2.PaginatableStreamBase<_i2.Person> streamAll({
    _i4.Stream<String?>? searchQuery,
    _i4.Stream<List<_i2.Filter<Object>>>? where,
    _i4.Stream<List<_i2.OrderBy>>? orderBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamAll, [], {
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
            }),
            returnValue: _FakePaginatableStreamBase_41<_i2.Person>(
              this,
              Invocation.method(#streamAll, [], {
                #searchQuery: searchQuery,
                #where: where,
                #orderBy: orderBy,
              }),
            ),
            returnValueForMissingStub:
                _FakePaginatableStreamBase_41<_i2.Person>(
                  this,
                  Invocation.method(#streamAll, [], {
                    #searchQuery: searchQuery,
                    #where: where,
                    #orderBy: orderBy,
                  }),
                ),
          )
          as _i2.PaginatableStreamBase<_i2.Person>);

  @override
  _i4.Future<_i2.Person> createObject({required _i2.Person? newObject}) =>
      (super.noSuchMethod(
            Invocation.method(#createObject, [], {#newObject: newObject}),
            returnValue: _i4.Future<_i2.Person>.value(
              _FakePerson_36(
                this,
                Invocation.method(#createObject, [], {#newObject: newObject}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Person>.value(
              _FakePerson_36(
                this,
                Invocation.method(#createObject, [], {#newObject: newObject}),
              ),
            ),
          )
          as _i4.Future<_i2.Person>);

  @override
  _i4.Future<_i2.Person?> updateObject({
    required _i2.Person? newObject,
    required _i2.Person? oldObject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateObject, [], {
              #newObject: newObject,
              #oldObject: oldObject,
            }),
            returnValue: _i4.Future<_i2.Person?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Person?>.value(),
          )
          as _i4.Future<_i2.Person?>);

  @override
  _i4.Future<_i2.Person?> deleteById({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {#id: id}),
            returnValue: _i4.Future<_i2.Person?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Person?>.value(),
          )
          as _i4.Future<_i2.Person?>);
}

/// A class which mocks [StreamableDAOProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamableDAOProxy<T extends _i2.ViewableWithID> extends _i1.Mock
    implements _i2.StreamableDAOProxy<T> {
  @override
  _i2.DatabaseService get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabaseService_35(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeDatabaseService_35(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.DatabaseService);

  @override
  T Function(Map<String, dynamic>) get fromJson =>
      (super.noSuchMethod(
            Invocation.getter(#fromJson),
            returnValue: (Map<String, dynamic> json) =>
                _i6.dummyValue<T>(this, Invocation.getter(#fromJson)),
            returnValueForMissingStub: (Map<String, dynamic> json) =>
                _i6.dummyValue<T>(this, Invocation.getter(#fromJson)),
          )
          as T Function(Map<String, dynamic>));

  @override
  _i2.DBGraphQLClient get graphQLClient =>
      (super.noSuchMethod(
            Invocation.getter(#graphQLClient),
            returnValue: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
            returnValueForMissingStub: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
          )
          as _i2.DBGraphQLClient);

  @override
  _i2.PaginatableStreamBase<T> streamAll({
    required _i2.StreamAllConfig<T>? streamAllConfig,
    _i2.StreamCountConfig<T>? streamCountConfig,
    _i4.Stream<String?>? searchQuery,
    _i4.Stream<List<_i2.Filter<Object>>>? where,
    _i4.Stream<List<_i2.OrderBy>>? orderBy,
    int? overrideTotalLimit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamAll, [], {
              #streamAllConfig: streamAllConfig,
              #streamCountConfig: streamCountConfig,
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
              #overrideTotalLimit: overrideTotalLimit,
            }),
            returnValue: _FakePaginatableStreamBase_41<T>(
              this,
              Invocation.method(#streamAll, [], {
                #streamAllConfig: streamAllConfig,
                #streamCountConfig: streamCountConfig,
                #searchQuery: searchQuery,
                #where: where,
                #orderBy: orderBy,
                #overrideTotalLimit: overrideTotalLimit,
              }),
            ),
            returnValueForMissingStub: _FakePaginatableStreamBase_41<T>(
              this,
              Invocation.method(#streamAll, [], {
                #streamAllConfig: streamAllConfig,
                #streamCountConfig: streamCountConfig,
                #searchQuery: searchQuery,
                #where: where,
                #orderBy: orderBy,
                #overrideTotalLimit: overrideTotalLimit,
              }),
            ),
          )
          as _i2.PaginatableStreamBase<T>);

  @override
  _i4.Stream<T?> streamSingleById({
    required String? id,
    required _i2.StreamSingleByIdConfig<T>? streamSingleByIdConfig,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamSingleById, [], {
              #id: id,
              #streamSingleByIdConfig: streamSingleByIdConfig,
            }),
            returnValue: _i4.Stream<T?>.empty(),
            returnValueForMissingStub: _i4.Stream<T?>.empty(),
          )
          as _i4.Stream<T?>);
}

/// A class which mocks [PaginatableStreamBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaginatableStreamBase<T> extends _i1.Mock
    implements _i2.PaginatableStreamBase<T> {
  @override
  int get pageSize =>
      (super.noSuchMethod(
            Invocation.getter(#pageSize),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get hasMore =>
      (super.noSuchMethod(
            Invocation.getter(#hasMore),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get currentPageIndex =>
      (super.noSuchMethod(
            Invocation.getter(#currentPageIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<T> get currentItems =>
      (super.noSuchMethod(
            Invocation.getter(#currentItems),
            returnValue: <T>[],
            returnValueForMissingStub: <T>[],
          )
          as List<T>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<bool> get onLoadingChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onLoadingChanged),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Stream<int?> get totalCountStream =>
      (super.noSuchMethod(
            Invocation.getter(#totalCountStream),
            returnValue: _i4.Stream<int?>.empty(),
            returnValueForMissingStub: _i4.Stream<int?>.empty(),
          )
          as _i4.Stream<int?>);

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(
            Invocation.getter(#isBroadcast),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<int> get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<T>> get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<void> listenToPage(int? pageIndex) =>
      (super.noSuchMethod(
            Invocation.method(#listenToPage, [pageIndex]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> listenToNextPage() =>
      (super.noSuchMethod(
            Invocation.method(#listenToNextPage, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<T>> asBroadcastStream({
    void Function(_i4.StreamSubscription<List<T>>)? onListen,
    void Function(_i4.StreamSubscription<List<T>>)? onCancel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#asBroadcastStream, [], {
              #onListen: onListen,
              #onCancel: onCancel,
            }),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.StreamSubscription<List<T>> listen(
    void Function(List<T>)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [onData],
              {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError,
              },
            ),
            returnValue: _FakeStreamSubscription_42<List<T>>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
            returnValueForMissingStub: _FakeStreamSubscription_42<List<T>>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
          )
          as _i4.StreamSubscription<List<T>>);

  @override
  _i4.Stream<List<T>> where(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Stream<S> map<S>(S Function(List<T>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#map, [convert]),
            returnValue: _i4.Stream<S>.empty(),
            returnValueForMissingStub: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Stream<E> asyncMap<E>(_i4.FutureOr<E> Function(List<T>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncMap, [convert]),
            returnValue: _i4.Stream<E>.empty(),
            returnValueForMissingStub: _i4.Stream<E>.empty(),
          )
          as _i4.Stream<E>);

  @override
  _i4.Stream<E> asyncExpand<E>(_i4.Stream<E>? Function(List<T>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncExpand, [convert]),
            returnValue: _i4.Stream<E>.empty(),
            returnValueForMissingStub: _i4.Stream<E>.empty(),
          )
          as _i4.Stream<E>);

  @override
  _i4.Stream<List<T>> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [onError], {#test: test}),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Stream<S> expand<S>(Iterable<S> Function(List<T>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [convert]),
            returnValue: _i4.Stream<S>.empty(),
            returnValueForMissingStub: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Future<dynamic> pipe(_i4.StreamConsumer<List<T>>? streamConsumer) =>
      (super.noSuchMethod(
            Invocation.method(#pipe, [streamConsumer]),
            returnValue: _i4.Future<dynamic>.value(),
            returnValueForMissingStub: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Stream<S> transform<S>(
    _i4.StreamTransformer<List<T>, S>? streamTransformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [streamTransformer]),
            returnValue: _i4.Stream<S>.empty(),
            returnValueForMissingStub: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Future<List<T>> reduce(List<T> Function(List<T>, List<T>)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#reduce, [combine]),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<S> fold<S>(S? initialValue, S Function(S, List<T>)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i4.Future<S>.value(v),
                ) ??
                _FakeFuture_25<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i4.Future<S>.value(v),
                ) ??
                _FakeFuture_25<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
          )
          as _i4.Future<S>);

  @override
  _i4.Future<String> join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [needle]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> forEach(void Function(List<T>)? action) =>
      (super.noSuchMethod(
            Invocation.method(#forEach, [action]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> every(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#every, [test]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> any(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#any, [test]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<R> cast<R>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _i4.Stream<R>.empty(),
            returnValueForMissingStub: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Future<List<List<T>>> toList() =>
      (super.noSuchMethod(
            Invocation.method(#toList, []),
            returnValue: _i4.Future<List<List<T>>>.value(<List<T>>[]),
            returnValueForMissingStub: _i4.Future<List<List<T>>>.value(
              <List<T>>[],
            ),
          )
          as _i4.Future<List<List<T>>>);

  @override
  _i4.Future<Set<List<T>>> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: _i4.Future<Set<List<T>>>.value(<List<T>>{}),
            returnValueForMissingStub: _i4.Future<Set<List<T>>>.value(
              <List<T>>{},
            ),
          )
          as _i4.Future<Set<List<T>>>);

  @override
  _i4.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(#drain, [futureValue]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i4.Future<E>.value(v),
                ) ??
                _FakeFuture_25<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
            returnValueForMissingStub:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i4.Future<E>.value(v),
                ) ??
                _FakeFuture_25<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
          )
          as _i4.Future<E>);

  @override
  _i4.Stream<List<T>> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Stream<List<T>> takeWhile(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Stream<List<T>> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Stream<List<T>> skipWhile(bool Function(List<T>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Stream<List<T>> distinct([bool Function(List<T>, List<T>)? equals]) =>
      (super.noSuchMethod(
            Invocation.method(#distinct, [equals]),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);

  @override
  _i4.Future<List<T>> firstWhere(
    bool Function(List<T>)? test, {
    List<T> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> lastWhere(
    bool Function(List<T>)? test, {
    List<T> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> singleWhere(
    bool Function(List<T>)? test, {
    List<T> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<List<T>> elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#elementAt, [index]),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Stream<List<T>> timeout(
    Duration? timeLimit, {
    void Function(_i4.EventSink<List<T>>)? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i4.Stream<List<T>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);
}

/// A class which mocks [PaginatableStreamRequest].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockPaginatableStreamRequest<T, P> extends _i1.Mock
    implements _i2.PaginatableStreamRequest<T, P> {
  @override
  int get pageIndex =>
      (super.noSuchMethod(
            Invocation.getter(#pageIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get pageSize =>
      (super.noSuchMethod(
            Invocation.getter(#pageSize),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object?>[],
            returnValueForMissingStub: <Object?>[],
          )
          as List<Object?>);
}

/// A class which mocks [DBVarsTransformer].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBVarsTransformer extends _i1.Mock implements _i2.DBVarsTransformer {
  @override
  Map<String, dynamic>
  transformrequestForPagination<T extends _i2.ViewableWithID>(
    _i2.PaginatableStreamRequest<T, _i2.StreamableDAOParameters<T>?>? request, {
    List<_i2.Filter<Object>>? overrideWhere,
    List<_i2.OrderBy>? overrideOrderBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformrequestForPagination,
              [request],
              {
                #overrideWhere: overrideWhere,
                #overrideOrderBy: overrideOrderBy,
              },
            ),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
