name: church_admin_generator
description: ""
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

dependency_overrides:
  hive:
    git:
      url: https://github.com/MarioMederos/hive/
      ref: 299decc6295258c0c1583d04ff99c6ff1283ec8a
      path: hive
  hive_flutter:
    git:
      url: https://github.com/MarioMederos/hive/
      ref: 299decc6295258c0c1583d04ff99c6ff1283ec8a
      path: hive_flutter
  js: ^0.7.1

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.1
  church_admin:
    path: ../client
  glob: ^2.1.2
  gql: ^1.0.1-alpha+1691943394579
  source_gen: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
