name: church_admin_generator
description: ""
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

dependency_overrides:
  js: ^0.7.1

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  church_admin:
    path: ../client
  glob: ^2.1.2
  gql: ^1.0.1-alpha+1691943394579
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
