name: church_admin_generator
description: ""
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

dependency_overrides:
  js: ^0.7.1

dependencies:
  analyzer: ^13.3.0
  build: ^4.0.11
  church_admin:
    path: ../client
  code_builder: ^4.10.1
  dart_style: ^3.1.13
  glob: ^2.1.2
  gql: ^1.0.1-alpha+1691943394579
  source_gen: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
