// Mocks generated by Mockito 5.4.4 from annotations
// in church_admin/test/src/features/auth/presentation/screens/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i11;

import 'package:church_admin/church_admin.dart' as _i2;
import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i12;
import 'package:go_router/src/state.dart' as _i13;
import 'package:hive/src/box/default_compaction_strategy.dart' as _i10;
import 'package:hive/src/box/default_key_comparator.dart' as _i9;
import 'package:hive_flutter/hive_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:rxdart/rxdart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMultiFactorManager_0 extends _i1.SmartFake
    implements _i2.MultiFactorManager {
  _FakeMultiFactorManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_1<T> extends _i1.SmartFake
    implements _i3.ValueStream<T> {
  _FakeValueStream_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDBGraphQLClient_2 extends _i1.SmartFake
    implements _i2.DBGraphQLClient {
  _FakeDBGraphQLClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGQLParser_3 extends _i1.SmartFake implements _i2.GQLParser {
  _FakeGQLParser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDBVarsTransformer_4 extends _i1.SmartFake
    implements _i2.DBVarsTransformer {
  _FakeDBVarsTransformer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdvancedQueryParser_5 extends _i1.SmartFake
    implements _i2.AdvancedQueryParser {
  _FakeAdvancedQueryParser_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeDAO_6 extends _i1.SmartFake implements _i2.HomeDAO {
  _FakeHomeDAO_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAreasDAO_7 extends _i1.SmartFake implements _i2.AreasDAO {
  _FakeAreasDAO_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreetsDAO_8 extends _i1.SmartFake implements _i2.StreetsDAO {
  _FakeStreetsDAO_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFamiliesDAO_9 extends _i1.SmartFake implements _i2.FamiliesDAO {
  _FakeFamiliesDAO_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoresDAO_10 extends _i1.SmartFake implements _i2.StoresDAO {
  _FakeStoresDAO_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonsDAO_11 extends _i1.SmartFake implements _i2.PersonsDAO {
  _FakePersonsDAO_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServicesDAO_12 extends _i1.SmartFake implements _i2.ServicesDAO {
  _FakeServicesDAO_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassesDAO_13 extends _i1.SmartFake implements _i2.ClassesDAO {
  _FakeClassesDAO_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupsDAO_14 extends _i1.SmartFake implements _i2.GroupsDAO {
  _FakeGroupsDAO_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsersDAO_15 extends _i1.SmartFake implements _i2.UsersDAO {
  _FakeUsersDAO_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetadataDAO_16 extends _i1.SmartFake implements _i2.MetadataDAO {
  _FakeMetadataDAO_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHistoryDAO_17 extends _i1.SmartFake implements _i2.HistoryDAO {
  _FakeHistoryDAO_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_18<E> extends _i1.SmartFake implements _i4.Box<E> {
  _FakeBox_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLazyBox_19<E1> extends _i1.SmartFake implements _i4.LazyBox<E1> {
  _FakeLazyBox_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_20 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_21 extends _i1.SmartFake
    implements _i5.InheritedWidget {
  _FakeInheritedWidget_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_22 extends _i1.SmartFake
    implements _i5.DiagnosticsNode {
  _FakeDiagnosticsNode_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i6.TextTreeConfiguration? parentConfiguration,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeUri_23 extends _i1.SmartFake implements Uri {
  _FakeUri_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueKey_24<T> extends _i1.SmartFake implements _i5.ValueKey<T> {
  _FakeValueKey_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  @override
  _i2.MultiFactorManager get multiFactorManager => (super.noSuchMethod(
        Invocation.getter(#multiFactorManager),
        returnValue: _FakeMultiFactorManager_0(
          this,
          Invocation.getter(#multiFactorManager),
        ),
        returnValueForMissingStub: _FakeMultiFactorManager_0(
          this,
          Invocation.getter(#multiFactorManager),
        ),
      ) as _i2.MultiFactorManager);

  @override
  set multiFactorManager(_i2.MultiFactorManager? _multiFactorManager) =>
      super.noSuchMethod(
        Invocation.setter(
          #multiFactorManager,
          _multiFactorManager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.ValueStream<_i2.User?> get userStream => (super.noSuchMethod(
        Invocation.getter(#userStream),
        returnValue: _FakeValueStream_1<_i2.User?>(
          this,
          Invocation.getter(#userStream),
        ),
        returnValueForMissingStub: _FakeValueStream_1<_i2.User?>(
          this,
          Invocation.getter(#userStream),
        ),
      ) as _i3.ValueStream<_i2.User?>);

  @override
  _i3.ValueStream<String?> get idTokenStream => (super.noSuchMethod(
        Invocation.getter(#idTokenStream),
        returnValue: _FakeValueStream_1<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
        returnValueForMissingStub: _FakeValueStream_1<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
      ) as _i3.ValueStream<String?>);

  @override
  _i7.Future<bool> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> reauthWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> signUpWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getStoredPasswordHash() => (super.noSuchMethod(
        Invocation.method(
          #getStoredPasswordHash,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [AuthStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorage extends _i1.Mock implements _i2.AuthStorage {
  @override
  _i7.Future<_i2.User?> getUserFromCache() => (super.noSuchMethod(
        Invocation.method(
          #getUserFromCache,
          [],
        ),
        returnValue: _i7.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i7.Future<_i2.User?>.value(),
      ) as _i7.Future<_i2.User?>);

  @override
  _i7.Future<void> writeUserToCache(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #writeUserToCache,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getPasswordHash() => (super.noSuchMethod(
        Invocation.method(
          #getPasswordHash,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> saveUserPasswordHash(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserPasswordHash,
          [
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearPasswordHash() => (super.noSuchMethod(
        Invocation.method(
          #clearPasswordHash,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i2.ConnectivityService {
  @override
  String get urlToPing => (super.noSuchMethod(
        Invocation.getter(#urlToPing),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#urlToPing),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#urlToPing),
        ),
      ) as String);

  @override
  _i3.ValueStream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _FakeValueStream_1<bool>(
          this,
          Invocation.getter(#connectivityStream),
        ),
        returnValueForMissingStub: _FakeValueStream_1<bool>(
          this,
          Invocation.getter(#connectivityStream),
        ),
      ) as _i3.ValueStream<bool>);

  @override
  _i7.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  @override
  _i2.DBGraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeDBGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeDBGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i2.DBGraphQLClient);

  @override
  _i2.GQLParser get parser => (super.noSuchMethod(
        Invocation.getter(#parser),
        returnValue: _FakeGQLParser_3(
          this,
          Invocation.getter(#parser),
        ),
        returnValueForMissingStub: _FakeGQLParser_3(
          this,
          Invocation.getter(#parser),
        ),
      ) as _i2.GQLParser);

  @override
  _i2.DBVarsTransformer get varsTransformer => (super.noSuchMethod(
        Invocation.getter(#varsTransformer),
        returnValue: _FakeDBVarsTransformer_4(
          this,
          Invocation.getter(#varsTransformer),
        ),
        returnValueForMissingStub: _FakeDBVarsTransformer_4(
          this,
          Invocation.getter(#varsTransformer),
        ),
      ) as _i2.DBVarsTransformer);

  @override
  _i2.AdvancedQueryParser get advancedQueryParser => (super.noSuchMethod(
        Invocation.getter(#advancedQueryParser),
        returnValue: _FakeAdvancedQueryParser_5(
          this,
          Invocation.getter(#advancedQueryParser),
        ),
        returnValueForMissingStub: _FakeAdvancedQueryParser_5(
          this,
          Invocation.getter(#advancedQueryParser),
        ),
      ) as _i2.AdvancedQueryParser);

  @override
  _i2.HomeDAO get home => (super.noSuchMethod(
        Invocation.getter(#home),
        returnValue: _FakeHomeDAO_6(
          this,
          Invocation.getter(#home),
        ),
        returnValueForMissingStub: _FakeHomeDAO_6(
          this,
          Invocation.getter(#home),
        ),
      ) as _i2.HomeDAO);

  @override
  _i2.AreasDAO get areas => (super.noSuchMethod(
        Invocation.getter(#areas),
        returnValue: _FakeAreasDAO_7(
          this,
          Invocation.getter(#areas),
        ),
        returnValueForMissingStub: _FakeAreasDAO_7(
          this,
          Invocation.getter(#areas),
        ),
      ) as _i2.AreasDAO);

  @override
  _i2.StreetsDAO get streets => (super.noSuchMethod(
        Invocation.getter(#streets),
        returnValue: _FakeStreetsDAO_8(
          this,
          Invocation.getter(#streets),
        ),
        returnValueForMissingStub: _FakeStreetsDAO_8(
          this,
          Invocation.getter(#streets),
        ),
      ) as _i2.StreetsDAO);

  @override
  _i2.FamiliesDAO get families => (super.noSuchMethod(
        Invocation.getter(#families),
        returnValue: _FakeFamiliesDAO_9(
          this,
          Invocation.getter(#families),
        ),
        returnValueForMissingStub: _FakeFamiliesDAO_9(
          this,
          Invocation.getter(#families),
        ),
      ) as _i2.FamiliesDAO);

  @override
  _i2.StoresDAO get stores => (super.noSuchMethod(
        Invocation.getter(#stores),
        returnValue: _FakeStoresDAO_10(
          this,
          Invocation.getter(#stores),
        ),
        returnValueForMissingStub: _FakeStoresDAO_10(
          this,
          Invocation.getter(#stores),
        ),
      ) as _i2.StoresDAO);

  @override
  _i2.PersonsDAO get persons => (super.noSuchMethod(
        Invocation.getter(#persons),
        returnValue: _FakePersonsDAO_11(
          this,
          Invocation.getter(#persons),
        ),
        returnValueForMissingStub: _FakePersonsDAO_11(
          this,
          Invocation.getter(#persons),
        ),
      ) as _i2.PersonsDAO);

  @override
  _i2.ServicesDAO get services => (super.noSuchMethod(
        Invocation.getter(#services),
        returnValue: _FakeServicesDAO_12(
          this,
          Invocation.getter(#services),
        ),
        returnValueForMissingStub: _FakeServicesDAO_12(
          this,
          Invocation.getter(#services),
        ),
      ) as _i2.ServicesDAO);

  @override
  _i2.ClassesDAO get classes => (super.noSuchMethod(
        Invocation.getter(#classes),
        returnValue: _FakeClassesDAO_13(
          this,
          Invocation.getter(#classes),
        ),
        returnValueForMissingStub: _FakeClassesDAO_13(
          this,
          Invocation.getter(#classes),
        ),
      ) as _i2.ClassesDAO);

  @override
  _i2.GroupsDAO get groups => (super.noSuchMethod(
        Invocation.getter(#groups),
        returnValue: _FakeGroupsDAO_14(
          this,
          Invocation.getter(#groups),
        ),
        returnValueForMissingStub: _FakeGroupsDAO_14(
          this,
          Invocation.getter(#groups),
        ),
      ) as _i2.GroupsDAO);

  @override
  _i2.UsersDAO get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: _FakeUsersDAO_15(
          this,
          Invocation.getter(#users),
        ),
        returnValueForMissingStub: _FakeUsersDAO_15(
          this,
          Invocation.getter(#users),
        ),
      ) as _i2.UsersDAO);

  @override
  _i2.MetadataDAO get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeMetadataDAO_16(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakeMetadataDAO_16(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.MetadataDAO);

  @override
  _i2.HistoryDAO get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: _FakeHistoryDAO_17(
          this,
          Invocation.getter(#history),
        ),
        returnValueForMissingStub: _FakeHistoryDAO_17(
          this,
          Invocation.getter(#history),
        ),
      ) as _i2.HistoryDAO);

  @override
  Map<Type, _i2.DAOBase<_i2.ViewableWithID>> get daosByType =>
      (super.noSuchMethod(
        Invocation.getter(#daosByType),
        returnValue: <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
        returnValueForMissingStub: <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
      ) as Map<Type, _i2.DAOBase<_i2.ViewableWithID>>);
}

/// A class which mocks [UserSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsService extends _i1.Mock
    implements _i2.UserSettingsService {
  @override
  _i4.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_18<dynamic>(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeBox_18<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i4.Box<dynamic>);

  @override
  bool get greatFeastTheme => (super.noSuchMethod(
        Invocation.getter(#greatFeastTheme),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<void> setDarkTheme(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDarkTheme,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setRegisteredFCMToken(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setRegisteredFCMToken,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setGreatFeastTheme(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setGreatFeastTheme,
          [value],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSecondLineFor<T>({
    required String? value,
    Type? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSecondLineFor,
          [],
          {
            #value: value,
            #type: type,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setupDefaults() => (super.noSuchMethod(
        Invocation.method(
          #setupDefaults,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [HiveInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveInterface extends _i1.Mock implements _i4.HiveInterface {
  @override
  void init(
    String? path, {
    _i4.HiveStorageBackendPreference? backendPreference =
        _i4.HiveStorageBackendPreference.native,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #init,
          [path],
          {#backendPreference: backendPreference},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.Box<E>> openBox<E>(
    String? name, {
    _i4.HiveCipher? encryptionCipher,
    _i4.KeyComparator? keyComparator = _i9.defaultKeyComparator,
    _i4.CompactionStrategy? compactionStrategy = _i10.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    _i11.Uint8List? bytes,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #bytes: bytes,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i7.Future<_i4.Box<E>>.value(_FakeBox_18<E>(
          this,
          Invocation.method(
            #openBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #bytes: bytes,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.Box<E>>.value(_FakeBox_18<E>(
          this,
          Invocation.method(
            #openBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #bytes: bytes,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i7.Future<_i4.Box<E>>);

  @override
  _i7.Future<_i4.LazyBox<E>> openLazyBox<E>(
    String? name, {
    _i4.HiveCipher? encryptionCipher,
    _i4.KeyComparator? keyComparator = _i9.defaultKeyComparator,
    _i4.CompactionStrategy? compactionStrategy = _i10.defaultCompactionStrategy,
    bool? crashRecovery = true,
    String? path,
    String? collection,
    List<int>? encryptionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openLazyBox,
          [name],
          {
            #encryptionCipher: encryptionCipher,
            #keyComparator: keyComparator,
            #compactionStrategy: compactionStrategy,
            #crashRecovery: crashRecovery,
            #path: path,
            #collection: collection,
            #encryptionKey: encryptionKey,
          },
        ),
        returnValue: _i7.Future<_i4.LazyBox<E>>.value(_FakeLazyBox_19<E>(
          this,
          Invocation.method(
            #openLazyBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i4.LazyBox<E>>.value(_FakeLazyBox_19<E>(
          this,
          Invocation.method(
            #openLazyBox,
            [name],
            {
              #encryptionCipher: encryptionCipher,
              #keyComparator: keyComparator,
              #compactionStrategy: compactionStrategy,
              #crashRecovery: crashRecovery,
              #path: path,
              #collection: collection,
              #encryptionKey: encryptionKey,
            },
          ),
        )),
      ) as _i7.Future<_i4.LazyBox<E>>);

  @override
  _i4.Box<E> box<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #box,
          [name],
        ),
        returnValue: _FakeBox_18<E>(
          this,
          Invocation.method(
            #box,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeBox_18<E>(
          this,
          Invocation.method(
            #box,
            [name],
          ),
        ),
      ) as _i4.Box<E>);

  @override
  _i4.LazyBox<E> lazyBox<E>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #lazyBox,
          [name],
        ),
        returnValue: _FakeLazyBox_19<E>(
          this,
          Invocation.method(
            #lazyBox,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeLazyBox_19<E>(
          this,
          Invocation.method(
            #lazyBox,
            [name],
          ),
        ),
      ) as _i4.LazyBox<E>);

  @override
  bool isBoxOpen(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isBoxOpen,
          [name],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteBoxFromDisk(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBoxFromDisk,
          [name],
          {#path: path},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<int> generateSecureKey() => (super.noSuchMethod(
        Invocation.method(
          #generateSecureKey,
          [],
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i7.Future<bool> boxExists(
    String? name, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #boxExists,
          [name],
          {#path: path},
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void resetAdapters() => super.noSuchMethod(
        Invocation.method(
          #resetAdapters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerAdapter<T>(
    _i4.TypeAdapter<T>? adapter, {
    bool? internal = false,
    bool? override = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerAdapter,
          [adapter],
          {
            #internal: internal,
            #override: override,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAdapterRegistered(int? typeId) => (super.noSuchMethod(
        Invocation.method(
          #isAdapterRegistered,
          [typeId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void ignoreTypeId<T>(int? typeId) => super.noSuchMethod(
        Invocation.method(
          #ignoreTypeId,
          [typeId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsService extends _i1.Mock
    implements _i2.NotificationsService {
  @override
  _i7.Stream<_i2.Notification> get onNotificationTapStream =>
      (super.noSuchMethod(
        Invocation.getter(#onNotificationTapStream),
        returnValue: _i7.Stream<_i2.Notification>.empty(),
        returnValueForMissingStub: _i7.Stream<_i2.Notification>.empty(),
      ) as _i7.Stream<_i2.Notification>);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addForegroundNotificationTap(_i2.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #addForegroundNotificationTap,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseListeners() => super.noSuchMethod(
        Invocation.method(
          #pauseListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeListeners() => super.noSuchMethod(
        Invocation.method(
          #resumeListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.Notification?> getInitialNotification() => (super.noSuchMethod(
        Invocation.method(
          #getInitialNotification,
          [],
        ),
        returnValue: _i7.Future<_i2.Notification?>.value(),
        returnValueForMissingStub: _i7.Future<_i2.Notification?>.value(),
      ) as _i7.Future<_i2.Notification?>);

  @override
  _i7.Future<void> scheduleBirthDayNotification(
          [_i2.NotificationSetting? notificationSetting =
              const _i2.NotificationSetting(
            11,
            0,
            1,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleBirthDayNotification,
          [notificationSetting],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> scheduleMeetingNotification(
          [_i2.NotificationSetting? notificationSetting =
              const _i2.NotificationSetting(
            11,
            0,
            7,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleMeetingNotification,
          [notificationSetting],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> scheduleKodasNotification(
          [_i2.NotificationSetting? notificationSetting =
              const _i2.NotificationSetting(
            11,
            0,
            7,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleKodasNotification,
          [notificationSetting],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> scheduleConfessionNotification(
          [_i2.NotificationSetting? notificationSetting =
              const _i2.NotificationSetting(
            11,
            0,
            7,
          )]) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleConfessionNotification,
          [notificationSetting],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> scheduleDefaultNotifications() => (super.noSuchMethod(
        Invocation.method(
          #scheduleDefaultNotifications,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> notify(
    _i2.Notification? notification, {
    int? id,
    _i12.NotificationDetails? notificationDetails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notify,
          [notification],
          {
            #id: id,
            #notificationDetails: notificationDetails,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> registerFCMTokenAndListenForChanges({String? cachedToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerFCMTokenAndListenForChanges,
          [],
          {#cachedToken: cachedToken},
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> requestNotificationsPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestNotificationsPermission,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i5.BuildContext {
  @override
  _i5.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_20(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeWidget_20(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i5.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.InheritedWidget dependOnInheritedElement(
    _i5.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_21(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
        returnValueForMissingStub: _FakeInheritedWidget_21(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i5.InheritedWidget);

  @override
  void visitAncestorElements(_i5.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i5.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i5.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.DiagnosticsNode describeElement(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_22(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_22(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  _i5.DiagnosticsNode describeWidget(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_22(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_22(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  List<_i5.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i5.DiagnosticsNode>[],
        returnValueForMissingStub: <_i5.DiagnosticsNode>[],
      ) as List<_i5.DiagnosticsNode>);

  @override
  _i5.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_22(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_22(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i5.DiagnosticsNode);
}

/// A class which mocks [GoRouterState].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoRouterState extends _i1.Mock implements _i13.GoRouterState {
  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_23(
          this,
          Invocation.getter(#uri),
        ),
        returnValueForMissingStub: _FakeUri_23(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);

  @override
  String get matchedLocation => (super.noSuchMethod(
        Invocation.getter(#matchedLocation),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#matchedLocation),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#matchedLocation),
        ),
      ) as String);

  @override
  Map<String, String> get pathParameters => (super.noSuchMethod(
        Invocation.getter(#pathParameters),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  _i5.ValueKey<String> get pageKey => (super.noSuchMethod(
        Invocation.getter(#pageKey),
        returnValue: _FakeValueKey_24<String>(
          this,
          Invocation.getter(#pageKey),
        ),
        returnValueForMissingStub: _FakeValueKey_24<String>(
          this,
          Invocation.getter(#pageKey),
        ),
      ) as _i5.ValueKey<String>);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, String>? queryParameters = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedLocation,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #namedLocation,
            [name],
            {
              #pathParameters: pathParameters,
              #queryParameters: queryParameters,
            },
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #namedLocation,
            [name],
            {
              #pathParameters: pathParameters,
              #queryParameters: queryParameters,
            },
          ),
        ),
      ) as String);
}
