include: package:solid_lints/analysis_options.yaml

plugins:
  solid_lints: ^1.0.0

solid_lints:
  diagnostics:
    member_ordering:
      order:
        - static_getters_setters
        - static_fields
        - static_methods
        - fields
        - getters_setters
        - constructors
        - methods
    named_parameters_ordering:
      order:
        - required
        - required_super
        - default
        - nullable
        - super

linter:
  rules:
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    omit_local_variable_types: false
    public_member_api_docs: false
    sort_constructors_first: false
    specify_nonobvious_property_types: false
