name: church_admin_annotations
description: Annotations that mark church_admin models for church_admin_generator.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  solid_lints: ^1.0.0
