subscription watchAllSchools(
  $where: [SchoolsBoolExp!] = {}
  $orderBy: [SchoolsOrderBy!] = {}
  $limit: Int
) {
  schools(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
  }
}
