subscription watchAllQualifications(
  $where: [QualificationsBoolExp!] = {}
  $orderBy: [QualificationsOrderBy!] = { name: ASC }
  $limit: Int = 25
) {
  qualifications(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
  }
}
