// Mocks generated by Mockito 5.4.2 from annotations
// in church_admin/test/src/services/auth/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:church_admin/church_admin.dart' as _i2;
import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/rxdart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactorSession_1 extends _i1.SmartFake
    implements _i2.MultiFactorSession {
  _FakeMultiFactorSession_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactorInfo_2 extends _i1.SmartFake
    implements _i2.MultiFactorInfo {
  _FakeMultiFactorInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_4<T> extends _i1.SmartFake
    implements _i3.ValueStream<T> {
  _FakeValueStream_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorage extends _i1.Mock implements _i2.AuthStorage {
  @override
  _i4.Future<_i2.User?> getUserFromCache() => (super.noSuchMethod(
        Invocation.method(
          #getUserFromCache,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);
  @override
  _i4.Future<void> writeUserToCache(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #writeUserToCache,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<String?> getPasswordHash() => (super.noSuchMethod(
        Invocation.method(
          #getPasswordHash,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
  @override
  _i4.Future<void> saveUserPasswordHash(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserPasswordHash,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> clearPasswordHash() => (super.noSuchMethod(
        Invocation.method(
          #clearPasswordHash,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthAdapter extends _i1.Mock implements _i2.AuthAdapter {
  @override
  _i4.Stream<_i2.User?> get userStream => (super.noSuchMethod(
        Invocation.getter(#userStream),
        returnValue: _i4.Stream<_i2.User?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.User?>.empty(),
      ) as _i4.Stream<_i2.User?>);
  @override
  _i4.Stream<String?> get idTokenStream => (super.noSuchMethod(
        Invocation.getter(#idTokenStream),
        returnValue: _i4.Stream<String?>.empty(),
        returnValueForMissingStub: _i4.Stream<String?>.empty(),
      ) as _i4.Stream<String?>);
  @override
  _i4.Future<bool> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> reauthWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> signUpWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  bool isTokenUpToDate(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #isTokenUpToDate,
          [user],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  DateTime tokenExpiry(String? idToken) => (super.noSuchMethod(
        Invocation.method(
          #tokenExpiry,
          [idToken],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #tokenExpiry,
            [idToken],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.method(
            #tokenExpiry,
            [idToken],
          ),
        ),
      ) as DateTime);
  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [MultiFactorManagerAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiFactorManagerAdapter extends _i1.Mock
    implements _i2.MultiFactorManagerAdapter {
  @override
  bool get hasPendingMultifactorSession => (super.noSuchMethod(
        Invocation.getter(#hasPendingMultifactorSession),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i4.Future<_i2.MultiFactorSession> startMultiFactorSession(
          {required String? password}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startMultiFactorSession,
          [],
          {#password: password},
        ),
        returnValue:
            _i4.Future<_i2.MultiFactorSession>.value(_FakeMultiFactorSession_1(
          this,
          Invocation.method(
            #startMultiFactorSession,
            [],
            {#password: password},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MultiFactorSession>.value(_FakeMultiFactorSession_1(
          this,
          Invocation.method(
            #startMultiFactorSession,
            [],
            {#password: password},
          ),
        )),
      ) as _i4.Future<_i2.MultiFactorSession>);
  @override
  _i2.MultiFactorInfo getMultiFactorInfoFor(_i2.MultiFactorSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMultiFactorInfoFor,
          [session],
        ),
        returnValue: _FakeMultiFactorInfo_2(
          this,
          Invocation.method(
            #getMultiFactorInfoFor,
            [session],
          ),
        ),
        returnValueForMissingStub: _FakeMultiFactorInfo_2(
          this,
          Invocation.method(
            #getMultiFactorInfoFor,
            [session],
          ),
        ),
      ) as _i2.MultiFactorInfo);
  @override
  _i4.Future<(String, int?)> initiateMultifactorLogin(
    _i2.MultiFactorSession? session, {
    _i2.MultiFactorInfo? factor,
    String? phoneNumber,
    int? forceResendingToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateMultifactorLogin,
          [session],
          {
            #factor: factor,
            #phoneNumber: phoneNumber,
            #forceResendingToken: forceResendingToken,
          },
        ),
        returnValue: _i4.Future<(String, int?)>.value(('', null)),
        returnValueForMissingStub: _i4.Future<(String, int?)>.value(('', null)),
      ) as _i4.Future<(String, int?)>);
  @override
  _i4.Future<void> finishMultiFactorLogin(
    String? verificationId,
    String? smsCode,
    _i2.MultiFactorSession? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #finishMultiFactorLogin,
          [
            verificationId,
            smsCode,
            session,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> clearPendingMultiFactorSession() => (super.noSuchMethod(
        Invocation.method(
          #clearPendingMultiFactorSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LocalAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthService extends _i1.Mock implements _i2.LocalAuthService {
  @override
  Duration get timeToReauth => (super.noSuchMethod(
        Invocation.getter(#timeToReauth),
        returnValue: _FakeDuration_3(
          this,
          Invocation.getter(#timeToReauth),
        ),
        returnValueForMissingStub: _FakeDuration_3(
          this,
          Invocation.getter(#timeToReauth),
        ),
      ) as Duration);
  @override
  bool get shouldAuthenticate => (super.noSuchMethod(
        Invocation.getter(#shouldAuthenticate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i4.Stream<void> get refreshUIStream => (super.noSuchMethod(
        Invocation.getter(#refreshUIStream),
        returnValue: _i4.Stream<void>.empty(),
        returnValueForMissingStub: _i4.Stream<void>.empty(),
      ) as _i4.Stream<void>);
  @override
  bool requestOneTimeAuthForPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #requestOneTimeAuthForPath,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool shouldAuthenticateForPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #shouldAuthenticateForPath,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void didChangeAppLifecycleState(_i5.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void scheduleReauth() => super.noSuchMethod(
        Invocation.method(
          #scheduleReauth,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void resetAuthState({String? path}) => super.noSuchMethod(
        Invocation.method(
          #resetAuthState,
          [],
          {#path: path},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<bool> canCheckBiometrics() => (super.noSuchMethod(
        Invocation.method(
          #canCheckBiometrics,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> authenticate() => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> verifyPassword({
    required String? email,
    required String? password,
    String? storedPasswordHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPassword,
          [],
          {
            #email: email,
            #password: password,
            #storedPasswordHash: storedPasswordHash,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> didPushRouteInformation(
          _i6.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeLocales(List<_i5.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i5.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i4.Future<_i5.AppExitResponse>.value(_i5.AppExitResponse.exit),
        returnValueForMissingStub:
            _i4.Future<_i5.AppExitResponse>.value(_i5.AppExitResponse.exit),
      ) as _i4.Future<_i5.AppExitResponse>);
  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i2.ConnectivityService {
  @override
  String get urlToPing => (super.noSuchMethod(
        Invocation.getter(#urlToPing),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.ValueStream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _FakeValueStream_4<bool>(
          this,
          Invocation.getter(#connectivityStream),
        ),
        returnValueForMissingStub: _FakeValueStream_4<bool>(
          this,
          Invocation.getter(#connectivityStream),
        ),
      ) as _i3.ValueStream<bool>);
  @override
  _i4.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
