subscription watchAllClasses(
  $limit: Int = 200
  $orderBy: [ClassesOrderBy!] = { name: ASC }
  $where: [ClassesBoolExp!] = {}
) {
  classes(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Class
  }
}

subscription watchClass($id: uuid!) {
  classesByPk(id: $id) {
    ...Class
    service {
      ...ServiceWithStudyYears
    }
    lastEdit
    serviceGender
    studyYear {
      order
      name
    }
    adminUsers(distinctOn: uid) {
      user {
        ...User
      }
    }
  }
}
