subscription watchAllFathers(
  $where: [FathersBoolExp!] = {}
  $orderBy: [FathersOrderBy!] = { name: ASC }
  $limit: Int = 25
) {
  fathers(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
  }
}
