// Mocks generated by Mockito 5.3.2 from annotations
// in church_admin/test/src/widgets/church_admin_app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:ui' as _i22;

import 'package:church_admin/church_admin.dart' as _i14;
import 'package:church_admin/graphql/__generated__/schema.graphql.dart' as _i20;
import 'package:church_admin/graphql/scalars.dart' as _i19;
import 'package:church_admin/src/services/database/areas.dart' as _i5;
import 'package:church_admin/src/services/database/classes.dart' as _i10;
import 'package:church_admin/src/services/database/families.dart' as _i7;
import 'package:church_admin/src/services/database/groups.dart' as _i11;
import 'package:church_admin/src/services/database/metadata.dart' as _i13;
import 'package:church_admin/src/services/database/persons.dart' as _i8;
import 'package:church_admin/src/services/database/persons/__generated__/subscriptions.graphql.dart'
    as _i21;
import 'package:church_admin/src/services/database/services.dart' as _i9;
import 'package:church_admin/src/services/database/streets.dart' as _i6;
import 'package:church_admin/src/services/database/users.dart' as _i12;
import 'package:churchdata_core/churchdata_core.dart' as _i15;
import 'package:flutter/foundation.dart' as _i18;
import 'package:flutter/material.dart' as _i2;
import 'package:graphql/client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart_ext/rxdart_ext.dart' as _i3;
import 'package:sentry_flutter/sentry_flutter.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNavigatorObserver_0 extends _i1.SmartFake
    implements _i2.NavigatorObserver {
  _FakeNavigatorObserver_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_1<T> extends _i1.SmartFake
    implements _i3.ValueStream<T> {
  _FakeValueStream_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGraphQLClient_2 extends _i1.SmartFake implements _i4.GraphQLClient {
  _FakeGraphQLClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAreasDAO_3 extends _i1.SmartFake implements _i5.AreasDAO {
  _FakeAreasDAO_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreetsDAO_4 extends _i1.SmartFake implements _i6.StreetsDAO {
  _FakeStreetsDAO_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFamiliesDAO_5 extends _i1.SmartFake implements _i7.FamiliesDAO {
  _FakeFamiliesDAO_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonsDAO_6 extends _i1.SmartFake implements _i8.PersonsDAO {
  _FakePersonsDAO_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServicesDAO_7 extends _i1.SmartFake implements _i9.ServicesDAO {
  _FakeServicesDAO_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassesDAO_8 extends _i1.SmartFake implements _i10.ClassesDAO {
  _FakeClassesDAO_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupsDAO_9 extends _i1.SmartFake implements _i11.GroupsDAO {
  _FakeGroupsDAO_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsersDAO_10 extends _i1.SmartFake implements _i12.UsersDAO {
  _FakeUsersDAO_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetadataDAO_11 extends _i1.SmartFake implements _i13.MetadataDAO {
  _FakeMetadataDAO_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseService_12 extends _i1.SmartFake
    implements _i14.DatabaseService {
  _FakeDatabaseService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGQLPaginatableStream_13<T> extends _i1.SmartFake
    implements _i14.GQLPaginatableStream<T> {
  _FakeGQLPaginatableStream_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerson_14 extends _i1.SmartFake implements _i14.Person {
  _FakePerson_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_15 extends _i1.SmartFake implements Duration {
  _FakeDuration_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i15.LoggingService {
  @override
  _i2.NavigatorObserver get navigatorObserver => (super.noSuchMethod(
        Invocation.getter(#navigatorObserver),
        returnValue: _FakeNavigatorObserver_0(
          this,
          Invocation.getter(#navigatorObserver),
        ),
        returnValueForMissingStub: _FakeNavigatorObserver_0(
          this,
          Invocation.getter(#navigatorObserver),
        ),
      ) as _i2.NavigatorObserver);
  @override
  _i16.FutureOr<void> Function(_i16.FutureOr<void> Function(_i17.Scope))
      get configureScope => (super.noSuchMethod(
            Invocation.getter(#configureScope),
            returnValue: (_i16.FutureOr<void> Function(_i17.Scope) __p0) =>
                null,
            returnValueForMissingStub:
                (_i16.FutureOr<void> Function(_i17.Scope) __p0) => null,
          ) as _i16.FutureOr<void> Function(
              _i16.FutureOr<void> Function(_i17.Scope)));
  @override
  _i16.Future<void> log(String? msg) => (super.noSuchMethod(
        Invocation.method(
          #log,
          [msg],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> reportError(
    Exception? error, {
    Map<String, dynamic>? data,
    Map<String, dynamic>? extras,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportError,
          [error],
          {
            #data: data,
            #extras: extras,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> reportFlutterError(
    _i18.FlutterErrorDetails? flutterError, {
    Map<String, dynamic>? data,
    Map<String, dynamic>? extras,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportFlutterError,
          [flutterError],
          {
            #data: data,
            #extras: extras,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i14.AuthService {
  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i3.ValueStream<_i14.User?> get userStream => (super.noSuchMethod(
        Invocation.getter(#userStream),
        returnValue: _FakeValueStream_1<_i14.User?>(
          this,
          Invocation.getter(#userStream),
        ),
        returnValueForMissingStub: _FakeValueStream_1<_i14.User?>(
          this,
          Invocation.getter(#userStream),
        ),
      ) as _i3.ValueStream<_i14.User?>);
  @override
  _i3.ValueStream<String?> get idTokenStream => (super.noSuchMethod(
        Invocation.getter(#idTokenStream),
        returnValue: _FakeValueStream_1<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
        returnValueForMissingStub: _FakeValueStream_1<String?>(
          this,
          Invocation.getter(#idTokenStream),
        ),
      ) as _i3.ValueStream<String?>);
  @override
  _i16.Future<_i14.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i16.Future<_i14.User?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.User?>.value(),
      ) as _i16.Future<_i14.User?>);
  @override
  _i16.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i14.DatabaseService {
  @override
  _i4.GraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i4.GraphQLClient);
  @override
  _i5.AreasDAO get areas => (super.noSuchMethod(
        Invocation.getter(#areas),
        returnValue: _FakeAreasDAO_3(
          this,
          Invocation.getter(#areas),
        ),
        returnValueForMissingStub: _FakeAreasDAO_3(
          this,
          Invocation.getter(#areas),
        ),
      ) as _i5.AreasDAO);
  @override
  _i6.StreetsDAO get streets => (super.noSuchMethod(
        Invocation.getter(#streets),
        returnValue: _FakeStreetsDAO_4(
          this,
          Invocation.getter(#streets),
        ),
        returnValueForMissingStub: _FakeStreetsDAO_4(
          this,
          Invocation.getter(#streets),
        ),
      ) as _i6.StreetsDAO);
  @override
  _i7.FamiliesDAO get families => (super.noSuchMethod(
        Invocation.getter(#families),
        returnValue: _FakeFamiliesDAO_5(
          this,
          Invocation.getter(#families),
        ),
        returnValueForMissingStub: _FakeFamiliesDAO_5(
          this,
          Invocation.getter(#families),
        ),
      ) as _i7.FamiliesDAO);
  @override
  _i8.PersonsDAO get persons => (super.noSuchMethod(
        Invocation.getter(#persons),
        returnValue: _FakePersonsDAO_6(
          this,
          Invocation.getter(#persons),
        ),
        returnValueForMissingStub: _FakePersonsDAO_6(
          this,
          Invocation.getter(#persons),
        ),
      ) as _i8.PersonsDAO);
  @override
  _i9.ServicesDAO get services => (super.noSuchMethod(
        Invocation.getter(#services),
        returnValue: _FakeServicesDAO_7(
          this,
          Invocation.getter(#services),
        ),
        returnValueForMissingStub: _FakeServicesDAO_7(
          this,
          Invocation.getter(#services),
        ),
      ) as _i9.ServicesDAO);
  @override
  _i10.ClassesDAO get classes => (super.noSuchMethod(
        Invocation.getter(#classes),
        returnValue: _FakeClassesDAO_8(
          this,
          Invocation.getter(#classes),
        ),
        returnValueForMissingStub: _FakeClassesDAO_8(
          this,
          Invocation.getter(#classes),
        ),
      ) as _i10.ClassesDAO);
  @override
  _i11.GroupsDAO get groups => (super.noSuchMethod(
        Invocation.getter(#groups),
        returnValue: _FakeGroupsDAO_9(
          this,
          Invocation.getter(#groups),
        ),
        returnValueForMissingStub: _FakeGroupsDAO_9(
          this,
          Invocation.getter(#groups),
        ),
      ) as _i11.GroupsDAO);
  @override
  _i12.UsersDAO get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: _FakeUsersDAO_10(
          this,
          Invocation.getter(#users),
        ),
        returnValueForMissingStub: _FakeUsersDAO_10(
          this,
          Invocation.getter(#users),
        ),
      ) as _i12.UsersDAO);
  @override
  _i13.MetadataDAO get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeMetadataDAO_11(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakeMetadataDAO_11(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i13.MetadataDAO);
  @override
  Iterable<T> parseListOfT<T>(
    Map<String, dynamic>? d,
    T Function(Map<String, dynamic>)? mapper,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseListOfT,
          [
            d,
            mapper,
          ],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);
}

/// A class which mocks [UsersDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersDAO extends _i1.Mock implements _i12.UsersDAO {
  @override
  _i14.DatabaseService get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
      ) as _i14.DatabaseService);
  @override
  _i4.GraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i4.GraphQLClient);
  @override
  _i16.Stream<_i14.User> getUserInfoStream({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfoStream,
          [],
          {#uid: uid},
        ),
        returnValue: _i16.Stream<_i14.User>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.User>.empty(),
      ) as _i16.Stream<_i14.User>);
  @override
  _i16.Stream<_i14.User?> watchUser({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUser,
          [],
          {#userId: userId},
        ),
        returnValue: _i16.Stream<_i14.User?>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.User?>.empty(),
      ) as _i16.Stream<_i14.User?>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo> userEditHistory(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #userEditHistory,
          [],
          {#userId: userId},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #userEditHistory,
            [],
            {#userId: userId},
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #userEditHistory,
            [],
            {#userId: userId},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i16.Stream<_i14.User?> analyzeUserAttendance({
    required String? personId,
    required String? userId,
    required DateTime? dateFrom,
    required DateTime? dateTo,
    required Iterable<String>? groupsIds,
    required Iterable<String>? classesIds,
    required Iterable<String>? servicesIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeUserAttendance,
          [],
          {
            #personId: personId,
            #userId: userId,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
            #groupsIds: groupsIds,
            #classesIds: classesIds,
            #servicesIds: servicesIds,
          },
        ),
        returnValue: _i16.Stream<_i14.User?>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.User?>.empty(),
      ) as _i16.Stream<_i14.User?>);
}

/// A class which mocks [PersonsDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonsDAO extends _i1.Mock implements _i8.PersonsDAO {
  @override
  _i14.DatabaseService get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
      ) as _i14.DatabaseService);
  @override
  _i4.GraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i4.GraphQLClient);
  @override
  _i16.Future<_i4.FetchPolicy> getFetchPolicy() => (super.noSuchMethod(
        Invocation.method(
          #getFetchPolicy,
          [],
        ),
        returnValue:
            _i16.Future<_i4.FetchPolicy>.value(_i4.FetchPolicy.cacheFirst),
        returnValueForMissingStub:
            _i16.Future<_i4.FetchPolicy>.value(_i4.FetchPolicy.cacheFirst),
      ) as _i16.Future<_i4.FetchPolicy>);
  @override
  _i16.Future<_i14.Person?> deletePerson({required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePerson,
          [],
          {#personId: personId},
        ),
        returnValue: _i16.Future<_i14.Person?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.Person?>.value(),
      ) as _i16.Future<_i14.Person?>);
  @override
  _i16.Future<_i14.Person> getFullPersonData({required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFullPersonData,
          [],
          {#personId: personId},
        ),
        returnValue: _i16.Future<_i14.Person>.value(_FakePerson_14(
          this,
          Invocation.method(
            #getFullPersonData,
            [],
            {#personId: personId},
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i14.Person>.value(_FakePerson_14(
          this,
          Invocation.method(
            #getFullPersonData,
            [],
            {#personId: personId},
          ),
        )),
      ) as _i16.Future<_i14.Person>);
  @override
  _i16.Stream<_i14.Person?> getMorePersonData({
    required String? personId,
    String? areasAfter,
    String? classesAfter,
    String? groupsAfter,
    String? servicesAfter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMorePersonData,
          [],
          {
            #personId: personId,
            #areasAfter: areasAfter,
            #classesAfter: classesAfter,
            #groupsAfter: groupsAfter,
            #servicesAfter: servicesAfter,
          },
        ),
        returnValue: _i16.Stream<_i14.Person?>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.Person?>.empty(),
      ) as _i16.Stream<_i14.Person?>);
  @override
  _i16.Stream<_i14.Person?> getPersonClassesAndGroups(
          {required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonClassesAndGroups,
          [],
          {#personId: personId},
        ),
        returnValue: _i16.Stream<_i14.Person?>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.Person?>.empty(),
      ) as _i16.Stream<_i14.Person?>);
  @override
  _i16.Future<Iterable<_i14.Person>> getPersonsConfessionWarning(
          {required DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsConfessionWarning,
          [],
          {#date: date},
        ),
        returnValue: _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
        returnValueForMissingStub:
            _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
      ) as _i16.Future<Iterable<_i14.Person>>);
  @override
  _i16.Future<Iterable<_i14.Person>> getPersonsKodasWarning(
          {required DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsKodasWarning,
          [],
          {#date: date},
        ),
        returnValue: _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
        returnValueForMissingStub:
            _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
      ) as _i16.Future<Iterable<_i14.Person>>);
  @override
  _i16.Future<Iterable<_i14.Person>> getPersonsMeetingWarning(
          {required DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsMeetingWarning,
          [],
          {#date: date},
        ),
        returnValue: _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
        returnValueForMissingStub:
            _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
      ) as _i16.Future<Iterable<_i14.Person>>);
  @override
  _i16.Future<Iterable<_i14.Person>> getBirthdayPersons(
          {required DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBirthdayPersons,
          [],
          {#date: date},
        ),
        returnValue: _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
        returnValueForMissingStub:
            _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
      ) as _i16.Future<Iterable<_i14.Person>>);
  @override
  _i16.Future<Iterable<_i14.Person>> getPersonsVisitWarning(
          {required DateTime? date}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsVisitWarning,
          [],
          {#date: date},
        ),
        returnValue: _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
        returnValueForMissingStub:
            _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
      ) as _i16.Future<Iterable<_i14.Person>>);
  @override
  _i16.Future<_i14.Person> insertPerson({required _i14.Person? newPerson}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPerson,
          [],
          {#newPerson: newPerson},
        ),
        returnValue: _i16.Future<_i14.Person>.value(_FakePerson_14(
          this,
          Invocation.method(
            #insertPerson,
            [],
            {#newPerson: newPerson},
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i14.Person>.value(_FakePerson_14(
          this,
          Invocation.method(
            #insertPerson,
            [],
            {#newPerson: newPerson},
          ),
        )),
      ) as _i16.Future<_i14.Person>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo> paginatePersonCallHistory(
          {required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersonCallHistory,
          [],
          {#personId: personId},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonCallHistory,
            [],
            {#personId: personId},
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonCallHistory,
            [],
            {#personId: personId},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>
      paginatePersonClassAttendance({
    required String? personId,
    required String? classId,
    bool? asAdmin = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonClassAttendance,
              [],
              {
                #personId: personId,
                #classId: classId,
                #asAdmin: asAdmin,
              },
            ),
            returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonClassAttendance,
                [],
                {
                  #personId: personId,
                  #classId: classId,
                  #asAdmin: asAdmin,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonClassAttendance,
                [],
                {
                  #personId: personId,
                  #classId: classId,
                  #asAdmin: asAdmin,
                },
              ),
            ),
          ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>
      paginatePersonConfessionHistory({required String? personId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonConfessionHistory,
              [],
              {#personId: personId},
            ),
            returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonConfessionHistory,
                [],
                {#personId: personId},
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonConfessionHistory,
                [],
                {#personId: personId},
              ),
            ),
          ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo> paginatePersonEditHistory(
          {required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersonEditHistory,
          [],
          {#personId: personId},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonEditHistory,
            [],
            {#personId: personId},
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonEditHistory,
            [],
            {#personId: personId},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>
      paginatePersonGroupAttendance({
    required String? personId,
    required String? groupId,
    bool? asAdmin = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonGroupAttendance,
              [],
              {
                #personId: personId,
                #groupId: groupId,
                #asAdmin: asAdmin,
              },
            ),
            returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonGroupAttendance,
                [],
                {
                  #personId: personId,
                  #groupId: groupId,
                  #asAdmin: asAdmin,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonGroupAttendance,
                [],
                {
                  #personId: personId,
                  #groupId: groupId,
                  #asAdmin: asAdmin,
                },
              ),
            ),
          ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo> paginatePersonKodasHistory(
          {required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersonKodasHistory,
          [],
          {#personId: personId},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonKodasHistory,
            [],
            {#personId: personId},
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonKodasHistory,
            [],
            {#personId: personId},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>
      paginatePersonServiceAttendance({
    required String? personId,
    required String? serviceId,
    bool? asAdmin = false,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #paginatePersonServiceAttendance,
              [],
              {
                #personId: personId,
                #serviceId: serviceId,
                #asAdmin: asAdmin,
              },
            ),
            returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonServiceAttendance,
                [],
                {
                  #personId: personId,
                  #serviceId: serviceId,
                  #asAdmin: asAdmin,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
              this,
              Invocation.method(
                #paginatePersonServiceAttendance,
                [],
                {
                  #personId: personId,
                  #serviceId: serviceId,
                  #asAdmin: asAdmin,
                },
              ),
            ),
          ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo> paginatePersonVisitHistory(
          {required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersonVisitHistory,
          [],
          {#personId: personId},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonVisitHistory,
            [],
            {#personId: personId},
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonVisitHistory,
            [],
            {#personId: personId},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
  @override
  _i16.Stream<_i14.Person?> streamPerson({required String? personId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamPerson,
          [],
          {#personId: personId},
        ),
        returnValue: _i16.Stream<_i14.Person?>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.Person?>.empty(),
      ) as _i16.Stream<_i14.Person?>);
  @override
  _i16.Stream<_i14.Person?> getPersonAnalysis({
    required String? personId,
    required _i14.PersonAnalysisOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonAnalysis,
          [],
          {
            #personId: personId,
            #options: options,
          },
        ),
        returnValue: _i16.Stream<_i14.Person?>.empty(),
        returnValueForMissingStub: _i16.Stream<_i14.Person?>.empty(),
      ) as _i16.Stream<_i14.Person?>);
  @override
  _i14.GQLPaginatableStream<_i14.Person> paginatePersons({
    _i16.Stream<String?>? searchQuery,
    String? secondLineFieldName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersons,
          [],
          {
            #searchQuery: searchQuery,
            #secondLineFieldName: secondLineFieldName,
          },
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.Person>(
          this,
          Invocation.method(
            #paginatePersons,
            [],
            {
              #searchQuery: searchQuery,
              #secondLineFieldName: secondLineFieldName,
            },
          ),
        ),
        returnValueForMissingStub: _FakeGQLPaginatableStream_13<_i14.Person>(
          this,
          Invocation.method(
            #paginatePersons,
            [],
            {
              #searchQuery: searchQuery,
              #secondLineFieldName: secondLineFieldName,
            },
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.Person>);
  @override
  _i16.Stream<Map<Type, Set<Object>>?> getPersonsGeolocations({
    String? personId,
    List<_i19.UuidValue>? areasIds = const [],
    List<_i19.UuidValue>? streetsIds = const [],
    List<_i19.UuidValue>? familiesIds = const [],
    List<_i19.UuidValue>? servicesIds = const [],
    List<_i19.UuidValue>? classesIds = const [],
    List<_i19.UuidValue>? groupsIds = const [],
    bool? getAreas = false,
    bool? getStreets = false,
    bool? getFamilies = false,
    bool? getPersons = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsGeolocations,
          [],
          {
            #personId: personId,
            #areasIds: areasIds,
            #streetsIds: streetsIds,
            #familiesIds: familiesIds,
            #servicesIds: servicesIds,
            #classesIds: classesIds,
            #groupsIds: groupsIds,
            #getAreas: getAreas,
            #getStreets: getStreets,
            #getFamilies: getFamilies,
            #getPersons: getPersons,
          },
        ),
        returnValue: _i16.Stream<Map<Type, Set<Object>>?>.empty(),
        returnValueForMissingStub: _i16.Stream<Map<Type, Set<Object>>?>.empty(),
      ) as _i16.Stream<Map<Type, Set<Object>>?>);
  @override
  _i16.Future<void> updatePerson({
    required _i14.Person? oldPerson,
    required _i14.Person? newPerson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePerson,
          [],
          {
            #oldPerson: oldPerson,
            #newPerson: newPerson,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<_i14.Person?> updatePersonLastCall({
    required String? personId,
    required DateTime? lastCall,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonLastCall,
          [],
          {
            #personId: personId,
            #lastCall: lastCall,
          },
        ),
        returnValue: _i16.Future<_i14.Person?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.Person?>.value(),
      ) as _i16.Future<_i14.Person?>);
  @override
  _i16.Future<_i14.Person?> updatePersonLastConfession({
    required String? personId,
    required DateTime? lastConfession,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonLastConfession,
          [],
          {
            #personId: personId,
            #lastConfession: lastConfession,
          },
        ),
        returnValue: _i16.Future<_i14.Person?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.Person?>.value(),
      ) as _i16.Future<_i14.Person?>);
  @override
  _i16.Future<_i14.Person?> updatePersonLastKodas({
    required String? personId,
    required DateTime? lastKodas,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonLastKodas,
          [],
          {
            #personId: personId,
            #lastKodas: lastKodas,
          },
        ),
        returnValue: _i16.Future<_i14.Person?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.Person?>.value(),
      ) as _i16.Future<_i14.Person?>);
  @override
  _i16.Future<_i14.Person?> updatePersonLastVisit({
    required String? personId,
    required DateTime? lastVisit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonLastVisit,
          [],
          {
            #personId: personId,
            #lastVisit: lastVisit,
          },
        ),
        returnValue: _i16.Future<_i14.Person?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.Person?>.value(),
      ) as _i16.Future<_i14.Person?>);
  @override
  _i16.Future<_i14.Person?> updatePersonSpiritData({
    required String? personId,
    required DateTime? lastConfession,
    required DateTime? lastKodas,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonSpiritData,
          [],
          {
            #personId: personId,
            #lastConfession: lastConfession,
            #lastKodas: lastKodas,
          },
        ),
        returnValue: _i16.Future<_i14.Person?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.Person?>.value(),
      ) as _i16.Future<_i14.Person?>);
  @override
  _i16.Future<Iterable<_i14.Person>> getPersonsNames({
    List<_i20.Input$PersonsBoolExp>? where,
    int? limit,
    List<_i20.Input$PersonsOrderBy>? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonsNames,
          [],
          {
            #where: where,
            #limit: limit,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
        returnValueForMissingStub:
            _i16.Future<Iterable<_i14.Person>>.value(<_i14.Person>[]),
      ) as _i16.Future<Iterable<_i14.Person>>);
  @override
  _i14.GQLPaginatableStream<_i14.LastRecordedByInfo> paginatePersonAttendance({
    required _i21.Variables$Subscription$personAttendance Function(
      int,
      _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>,
    )?
        vars,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginatePersonAttendance,
          [],
          {
            #vars: vars,
            #limit: limit,
          },
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonAttendance,
            [],
            {
              #vars: vars,
              #limit: limit,
            },
          ),
        ),
        returnValueForMissingStub:
            _FakeGQLPaginatableStream_13<_i14.LastRecordedByInfo>(
          this,
          Invocation.method(
            #paginatePersonAttendance,
            [],
            {
              #vars: vars,
              #limit: limit,
            },
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.LastRecordedByInfo>);
}

/// A class which mocks [AreasDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockAreasDAO extends _i1.Mock implements _i5.AreasDAO {
  @override
  _i14.DatabaseService get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
      ) as _i14.DatabaseService);
  @override
  _i4.GraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i4.GraphQLClient);
  @override
  _i14.GQLPaginatableStream<_i14.Area> paginateAreas(
          {_i16.Stream<String?>? searchQuery}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginateAreas,
          [],
          {#searchQuery: searchQuery},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.Area>(
          this,
          Invocation.method(
            #paginateAreas,
            [],
            {#searchQuery: searchQuery},
          ),
        ),
        returnValueForMissingStub: _FakeGQLPaginatableStream_13<_i14.Area>(
          this,
          Invocation.method(
            #paginateAreas,
            [],
            {#searchQuery: searchQuery},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.Area>);
}

/// A class which mocks [ServicesDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicesDAO extends _i1.Mock implements _i9.ServicesDAO {
  @override
  _i14.DatabaseService get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabaseService_12(
          this,
          Invocation.getter(#db),
        ),
      ) as _i14.DatabaseService);
  @override
  _i4.GraphQLClient get graphQLClient => (super.noSuchMethod(
        Invocation.getter(#graphQLClient),
        returnValue: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
        returnValueForMissingStub: _FakeGraphQLClient_2(
          this,
          Invocation.getter(#graphQLClient),
        ),
      ) as _i4.GraphQLClient);
  @override
  _i14.GQLPaginatableStream<_i14.Service> paginateServices(
          {_i16.Stream<String?>? searchQuery}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginateServices,
          [],
          {#searchQuery: searchQuery},
        ),
        returnValue: _FakeGQLPaginatableStream_13<_i14.Service>(
          this,
          Invocation.method(
            #paginateServices,
            [],
            {#searchQuery: searchQuery},
          ),
        ),
        returnValueForMissingStub: _FakeGQLPaginatableStream_13<_i14.Service>(
          this,
          Invocation.method(
            #paginateServices,
            [],
            {#searchQuery: searchQuery},
          ),
        ),
      ) as _i14.GQLPaginatableStream<_i14.Service>);
}

/// A class which mocks [LocalAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthService extends _i1.Mock implements _i14.LocalAuthService {
  @override
  Duration get timeToReauth => (super.noSuchMethod(
        Invocation.getter(#timeToReauth),
        returnValue: _FakeDuration_15(
          this,
          Invocation.getter(#timeToReauth),
        ),
        returnValueForMissingStub: _FakeDuration_15(
          this,
          Invocation.getter(#timeToReauth),
        ),
      ) as Duration);
  @override
  bool get shouldAuthenticate => (super.noSuchMethod(
        Invocation.getter(#shouldAuthenticate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i16.Stream<void> get refreshUIStream => (super.noSuchMethod(
        Invocation.getter(#refreshUIStream),
        returnValue: _i16.Stream<void>.empty(),
        returnValueForMissingStub: _i16.Stream<void>.empty(),
      ) as _i16.Stream<void>);
  @override
  void didChangeAppLifecycleState(_i22.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void scheduleReauth() => super.noSuchMethod(
        Invocation.method(
          #scheduleReauth,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void resetAuthState() => super.noSuchMethod(
        Invocation.method(
          #resetAuthState,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<bool> canCheckBiometrics() => (super.noSuchMethod(
        Invocation.method(
          #canCheckBiometrics,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<bool> authenticate() => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<bool> didPushRouteInformation(
          _i2.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeLocales(List<_i22.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i14.ConnectivityService {
  @override
  String get urlToPing => (super.noSuchMethod(
        Invocation.getter(#urlToPing),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.ValueStream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _FakeValueStream_1<bool>(
          this,
          Invocation.getter(#connectivityStream),
        ),
        returnValueForMissingStub: _FakeValueStream_1<bool>(
          this,
          Invocation.getter(#connectivityStream),
        ),
      ) as _i3.ValueStream<bool>);
  @override
  _i16.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}
