// Mocks generated by Mockito 5.3.2 from annotations
// in church_admin/test/src/widgets/history_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:church_admin/church_admin.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueStream_0<T> extends _i1.SmartFake
    implements _i2.ValueStream<T> {
  _FakeValueStream_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DelegatingPaginatableStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockDelegatingPaginatableStream extends _i1.Mock
    implements _i3.DelegatingPaginatableStream<_i3.LastRecordedByInfo> {
  @override
  _i3.OnQuery<_i3.LastRecordedByInfo> get streamDelegate => (super.noSuchMethod(
        Invocation.getter(#streamDelegate),
        returnValue: (
          _i3.DelegatingPaginatableStream<_i3.LastRecordedByInfo> instance,
          _i4.Stream<int> offset,
        ) =>
            _i4.Stream<
                _i3.DelegatingStreamResult<_i3.LastRecordedByInfo>>.empty(),
        returnValueForMissingStub: (
          _i3.DelegatingPaginatableStream<_i3.LastRecordedByInfo> instance,
          _i4.Stream<int> offset,
        ) =>
            _i4.Stream<
                _i3.DelegatingStreamResult<_i3.LastRecordedByInfo>>.empty(),
      ) as _i3.OnQuery<_i3.LastRecordedByInfo>);
  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get canPaginateBackward => (super.noSuchMethod(
        Invocation.getter(#canPaginateBackward),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get canPaginateForward => (super.noSuchMethod(
        Invocation.getter(#canPaginateForward),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  int get currentOffset => (super.noSuchMethod(
        Invocation.getter(#currentOffset),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i2.ValueStream<List<_i3.LastRecordedByInfo>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _FakeValueStream_0<List<_i3.LastRecordedByInfo>>(
          this,
          Invocation.getter(#stream),
        ),
        returnValueForMissingStub:
            _FakeValueStream_0<List<_i3.LastRecordedByInfo>>(
          this,
          Invocation.getter(#stream),
        ),
      ) as _i2.ValueStream<List<_i3.LastRecordedByInfo>>);
  @override
  List<_i3.LastRecordedByInfo> get currentValue => (super.noSuchMethod(
        Invocation.getter(#currentValue),
        returnValue: <_i3.LastRecordedByInfo>[],
        returnValueForMissingStub: <_i3.LastRecordedByInfo>[],
      ) as List<_i3.LastRecordedByInfo>);
  @override
  int get limit => (super.noSuchMethod(
        Invocation.getter(#limit),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i4.Future<void> loadPage(int? offset) => (super.noSuchMethod(
        Invocation.method(
          #loadPage,
          [offset],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> loadNextPage() => (super.noSuchMethod(
        Invocation.method(
          #loadNextPage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> loadPreviousPage() => (super.noSuchMethod(
        Invocation.method(
          #loadPreviousPage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
