// Mocks generated by Mockito 5.4.6 from annotations
// in church_admin/test/src/features/data_entry/domain/models/functions_object_image_info_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:church_admin/church_admin.dart' as _i4;
import 'package:cloud_functions/cloud_functions.dart' as _i2;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpsCallable_0 extends _i1.SmartFake implements _i2.HttpsCallable {
  _FakeHttpsCallable_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FunctionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctionsService extends _i1.Mock implements _i4.FunctionsService {
  @override
  _i2.HttpsCallable httpsCallable(
    String? functionName, {
    _i2.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #httpsCallable,
              [functionName],
              {#options: options},
            ),
            returnValue: _FakeHttpsCallable_0(
              this,
              Invocation.method(
                #httpsCallable,
                [functionName],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeHttpsCallable_0(
              this,
              Invocation.method(
                #httpsCallable,
                [functionName],
                {#options: options},
              ),
            ),
          )
          as _i2.HttpsCallable);

  @override
  _i5.Future<String> getDownloadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDownloadUrl,
              [table, id],
              {#contentType: contentType},
            ),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getDownloadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getDownloadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getUploadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUploadUrl,
              [table, id],
              {#contentType: contentType},
            ),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getUploadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getUploadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deletePhoto(String? table, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhoto, [table, id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> tryClaimAccount() =>
      (super.noSuchMethod(
            Invocation.method(#tryClaimAccount, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i4.Address?> getAddressFromLocation(_i4.Point? location) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressFromLocation, [location]),
            returnValue: _i5.Future<_i4.Address?>.value(),
            returnValueForMissingStub: _i5.Future<_i4.Address?>.value(),
          )
          as _i5.Future<_i4.Address?>);

  @override
  _i5.Future<_i3.Response<dynamic>> uploadPhoto({
    required String? url,
    required _i5.Stream<List<int>>? fileStream,
    String? contentType,
    int? fileLength,
    void Function(int, int)? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [], {
              #url: url,
              #fileStream: fileStream,
              #contentType: contentType,
              #fileLength: fileLength,
              #onSendProgress: onSendProgress,
            }),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#uploadPhoto, [], {
                  #url: url,
                  #fileStream: fileStream,
                  #contentType: contentType,
                  #fileLength: fileLength,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#uploadPhoto, [], {
                  #url: url,
                  #fileStream: fileStream,
                  #contentType: contentType,
                  #fileLength: fileLength,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<bool> checkHasuraHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkHasuraHealth, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> applyInvitationCode(String? invitationCode) =>
      (super.noSuchMethod(
            Invocation.method(#applyInvitationCode, [invitationCode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getAppDownloadLink(String? platform) =>
      (super.noSuchMethod(
            Invocation.method(#getAppDownloadLink, [platform]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAppDownloadLink, [platform]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAppDownloadLink, [platform]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteMyAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMyAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> exportData({
    List<String>? areasIds = const [],
    List<String>? servicesIds = const [],
    List<String>? classesIds = const [],
    List<String>? groupsIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportData, [], {
              #areasIds: areasIds,
              #servicesIds: servicesIds,
              #classesIds: classesIds,
              #groupsIds: groupsIds,
            }),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#exportData, [], {
                  #areasIds: areasIds,
                  #servicesIds: servicesIds,
                  #classesIds: classesIds,
                  #groupsIds: groupsIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#exportData, [], {
                  #areasIds: areasIds,
                  #servicesIds: servicesIds,
                  #classesIds: classesIds,
                  #groupsIds: groupsIds,
                }),
              ),
            ),
          )
          as _i5.Future<String>);
}
