fragment Service on Services {
  ...ServiceNoPhoto
  photoUpdatedAt
}

fragment ServiceWithStudyYears on Services {
  ...ServiceNoPhoto
  studyYearFrom {
    order
    name
  }
  studyYearTo {
    order
    name
  }
  photoUpdatedAt
}

fragment ServiceNoPhoto on Services {
  id
  name
  color
}
