subscription watchAllServices(
  $where: [ServicesBoolExp!] = {}
  $groupsWhere: [GroupsBoolExp!] = {}
  $classesWhere: [ClassesBoolExp!] = {}
  $orderBy: [ServicesOrderBy!] = { studyYearFrom: ASC, studyYearTo: ASC }
  $classesOrderBy: [ClassesOrderBy!] = {
    studyYear: { order: ASC }
    serviceGender: DESC_NULLS_LAST
  }
  $groupsOrderBy: [GroupsOrderBy!] = {
    service: { studyYearFrom: ASC, studyYearTo: ASC }
  }
  $limit: Int = 200
) {
  services(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    ...Service
    fromStudyYear {
      name
      order
    }
    toStudyYear {
      name
      order
    }
    classes(where: { _and: $classesWhere }, orderBy: $classesOrderBy) {
      ...Class

      studyYear {
        name
        order
      }
    }
    groups(where: { _and: $groupsWhere }, orderBy: $groupsOrderBy) {
      ...Group
    }
  }
}
subscription watchService($id: uuid!) {
  servicesByPk(id: $id) {
    ...Service
    lastEdit
    adminUsers(distinctOn: uid) {
      user {
        ...User
      }
    }
    fromStudyYear {
      order
      name
    }
    nextServiceObject {
      ...Service
    }
    toStudyYear {
      order
      name
    }
  }
}
