fragment Address on Addresses {
  id
  countryIsoCode
  area {
    ...Area
  }
  district {
    id
    name
  }
  street {
    ...Street
  }
  substreetName
  fullAddressText
  geolocation
  houseNumber
  storeyNumber
  apartmentNumber
  specialLandmark
}
fragment EditHistory on HistoryEditHistory {
  time
  user {
    ...User
  }
}

fragment AttendanceHistory on HistoryAttendanceHistory {
  id
  time: datetime
  user: recordedByUser {
    ...User
  }
}

fragment CallHistory on HistoryCallHistory {
  time
  user {
    ...User
  }
}

fragment VisitHistory on HistoryVisitHistory {
  time
  user {
    ...User
  }
}

fragment KodasHistory on HistoryKodasHistory {
  id
  time
  user {
    ...User
  }
}

fragment KodasDayRecord on HistoryKodasHistory {
  id
  personId
  dayId
}

fragment ConfessionHistory on HistoryConfessionHistory {
  id
  time
  user {
    ...User
  }
}

fragment LatestEditHistory on HistoryLatestEdits {
  time
  user {
    ...User
  }
}
fragment LatestCallHistory on HistoryLatestCalls {
  time
  user {
    ...User
  }
}

fragment LatestVisitHistory on HistoryLatestVisits {
  time
  user {
    ...User
  }
}

fragment LatestFatherVisitHistory on HistoryLatestFatherVisits {
  time
  user {
    ...User
  }
}

fragment LatestKodasHistory on HistoryLatestKodases {
  time
  user {
    ...User
  }
}

fragment LatestConfessionHistory on HistoryLatestConfessions {
  time
  user {
    ...User
  }
}
