mutation deleteFamily($familyId: uuid!) {
  deleteFamiliesByPk(id: $familyId) {
    ...Family
  }
}

mutation insertFamily($newFamily: FamiliesInsertInput!) {
  insertFamiliesOne(object: $newFamily) {
    ...Family
  }
}

mutation updateFamily(
  $familyId: uuid!
  $newFamily: FamiliesSetInput!
  $addressId: uuid!
  $newAddress: AddressesSetInput
  $deleteParents: [uuid!]!
  $deleteChildren: [uuid!]!
  $addRelatedFamilies: [FamiliesFamiliesInsertInput!]!
  $updateFamily: Boolean!
  $updateAddress: Boolean!
  $deleteRelatedFamilies: Boolean!
  $insertRelatedFamilies: Boolean!
  $lastVisit: timestamptz
  $lastFatherVisit: timestamptz
  $insertVisitHistory: Boolean!
  $insertFatherVisitHistory: Boolean!
) {
  updateFamiliesByPk(pkColumns: { id: $familyId }, _set: $newFamily)
    @include(if: $updateFamily) {
    ...Family
  }

  updateAddressesByPk(pkColumns: { id: $addressId }, _set: $newAddress)
    @include(if: $updateAddress) {
    ...Address
  }

  deleteFamiliesFamilies(
    where: {
      _or: [
        {
          childFamilyId: { _eq: $familyId }
          parentFamilyId: { _in: $deleteParents }
        }
        {
          parentFamilyId: { _eq: $familyId }
          childFamilyId: { _in: $deleteChildren }
        }
      ]
    }
  ) @include(if: $deleteRelatedFamilies) {
    affectedRows
  }
  insertFamiliesFamilies(objects: $addRelatedFamilies)
    @include(if: $insertRelatedFamilies) {
    affectedRows
  }
  insertHistoryVisitHistoryOne(
    object: {
      table: "families"
      recordId: $familyId
      time: $lastVisit
      isFatherVisit: false
    }
  ) @include(if: $insertVisitHistory) {
    visitId
  }
  _fatherVisitHistory: insertHistoryVisitHistoryOne(
    object: {
      table: "families"
      recordId: $familyId
      time: $lastFatherVisit
      isFatherVisit: true
    }
  ) @include(if: $insertFatherVisitHistory) {
    visitId
  }
}
