subscription watchAllFamilies(
  $limit: Int = 200
  $orderBy: [FamiliesOrderBy!] = { name: ASC }
  $where: [FamiliesBoolExp!] = {}
) {
  families(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Family
  }
}

subscription watchFamiliesCount($where: [FamiliesBoolExp!] = {}) {
  familiesAggregate(where: { _and: $where }) {
    aggregate {
      count
    }
  }
}

subscription watchAllFamiliesWithAddresses(
  $limit: Int = 200
  $orderBy: [FamiliesOrderBy!] = { name: ASC }
  $where: [FamiliesBoolExp!] = {}
) {
  families(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Family
    address {
      ...Address
    }
  }
}

subscription watchFamily($id: uuid!) {
  familiesByPk(id: $id) {
    ...Family
    address {
      ...Address
    }
    notes
    lastEdit {
      ...LatestEditHistory
    }
  }
}
