subscription getUserInfoStream($uid: uuid!) {
  users_by_pk(uid: $uid) {
    uid
    name
    photoUpdatedAt
    user_data {
      firebaseAuthUid
      email
      permissions
    }
    person {
      id
      name
      address
      geolocation
      mainPhone
      otherPhones
      birthdate
      gender
      isShammas
      shammasLevel {
        id
        name
        order
      }
      schoolId
      collegeId
      churchId
      fatherId
      isStudent
      jobId
      jobDescription
      qualificationId
      personTypeId
      stateId
      isServant
      notes
      familyId
      storeId
      studyYearId
      color
      photoUpdatedAt
      lastKodas
      lastConfession
    }
  }
}
