mutation deleteStreet($streetId: Uuid!) {
  deleteStreetsByPk(id: $streetId) {
    ...Street
  }
}

mutation insertStreet($newStreet: StreetsInsertInput!) {
  insertStreetsOne(object: $newStreet) {
    ...Street
  }
}

mutation updateStreet($streetId: Uuid!, $newStreet: StreetsSetInput!) {
  updateStreetsByPk(pkColumns: { id: $streetId }, _set: $newStreet) {
    ...Street
  }
}
