subscription watchAllGroups(
  $limit: Int = 200
  $orderBy: [GroupsOrderBy!] = { name: ASC }
  $where: [GroupsBoolExp!] = {}
) {
  groups(limit: $limit, orderBy: $orderBy, where: { _and: $where }) {
    ...Group
  }
}

subscription watchGroupsCount($where: [GroupsBoolExp!] = {}, $limit: Int) {
  groupsAggregate(where: { _and: $where }, limit: $limit) {
    aggregate {
      count
    }
  }
}

subscription watchGroup($id: uuid!) {
  groupsByPk(id: $id) {
    ...Group
    userCanEdit
    service {
      ...ServiceWithStudyYears
    }
    lastEdit {
      ...LatestEditHistory
    }
    validity
    adminUsers(distinctOn: uid) {
      user {
        ...User
      }
    }
  }
}
