// Mocks generated by Mockito 5.4.6 from annotations
// in church_admin/test/src/features/auth/application/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:church_admin/church_admin.dart' as _i2;
import 'package:cloud_functions/cloud_functions.dart' as _i4;
import 'package:dio/dio.dart' as _i5;
import 'package:flutter/material.dart' as _i9;
import 'package:flutter/services.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:rxdart/rxdart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDBGraphQLClient_0 extends _i1.SmartFake
    implements _i2.DBGraphQLClient {
  _FakeDBGraphQLClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGQLParser_1 extends _i1.SmartFake implements _i2.GQLParser {
  _FakeGQLParser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDBVarsTransformer_2 extends _i1.SmartFake
    implements _i2.DBVarsTransformer {
  _FakeDBVarsTransformer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdvancedQueryParser_3 extends _i1.SmartFake
    implements _i2.AdvancedQueryParser {
  _FakeAdvancedQueryParser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeDAO_4 extends _i1.SmartFake implements _i2.HomeDAO {
  _FakeHomeDAO_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAreasDAO_5 extends _i1.SmartFake implements _i2.AreasDAO {
  _FakeAreasDAO_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreetsDAO_6 extends _i1.SmartFake implements _i2.StreetsDAO {
  _FakeStreetsDAO_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFamiliesDAO_7 extends _i1.SmartFake implements _i2.FamiliesDAO {
  _FakeFamiliesDAO_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoresDAO_8 extends _i1.SmartFake implements _i2.StoresDAO {
  _FakeStoresDAO_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonsDAO_9 extends _i1.SmartFake implements _i2.PersonsDAO {
  _FakePersonsDAO_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServicesDAO_10 extends _i1.SmartFake implements _i2.ServicesDAO {
  _FakeServicesDAO_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClassesDAO_11 extends _i1.SmartFake implements _i2.ClassesDAO {
  _FakeClassesDAO_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGroupsDAO_12 extends _i1.SmartFake implements _i2.GroupsDAO {
  _FakeGroupsDAO_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersDAO_13 extends _i1.SmartFake implements _i2.UsersDAO {
  _FakeUsersDAO_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPermissionsDAO_14 extends _i1.SmartFake
    implements _i2.UserPermissionsDAO {
  _FakeUserPermissionsDAO_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvitationsDAO_15 extends _i1.SmartFake
    implements _i2.InvitationsDAO {
  _FakeInvitationsDAO_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPreferencesDAO_16 extends _i1.SmartFake
    implements _i2.UserPreferencesDAO {
  _FakeUserPreferencesDAO_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFcmTokensDAO_17 extends _i1.SmartFake implements _i2.FcmTokensDAO {
  _FakeFcmTokensDAO_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetadataDAO_18 extends _i1.SmartFake implements _i2.MetadataDAO {
  _FakeMetadataDAO_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistoryDAO_19 extends _i1.SmartFake implements _i2.HistoryDAO {
  _FakeHistoryDAO_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMeetingsDAO_20 extends _i1.SmartFake implements _i2.MeetingsDAO {
  _FakeMeetingsDAO_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_21 extends _i1.SmartFake implements Duration {
  _FakeDuration_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_22<T> extends _i1.SmartFake
    implements _i3.ValueStream<T> {
  _FakeValueStream_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamAllConfig_23<T> extends _i1.SmartFake
    implements _i2.StreamAllConfig<T> {
  _FakeStreamAllConfig_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamCountConfig_24<T> extends _i1.SmartFake
    implements _i2.StreamCountConfig<T> {
  _FakeStreamCountConfig_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSingleByIdConfig_25<T> extends _i1.SmartFake
    implements _i2.StreamSingleByIdConfig<T> {
  _FakeStreamSingleByIdConfig_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseService_26 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_27 extends _i1.SmartFake implements _i2.User {
  _FakeUser_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamableDAOProxy_28<T extends _i2.ViewableWithID>
    extends _i1.SmartFake
    implements _i2.StreamableDAOProxy<T> {
  _FakeStreamableDAOProxy_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatableStreamBase_29<T> extends _i1.SmartFake
    implements _i2.PaginatableStreamBase<T> {
  _FakePaginatableStreamBase_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallable_30 extends _i1.SmartFake implements _i4.HttpsCallable {
  _FakeHttpsCallable_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_31<T> extends _i1.SmartFake implements _i5.Response<T> {
  _FakeResponse_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorage extends _i1.Mock implements _i2.AuthStorage {
  @override
  _i6.Future<_i2.AuthUser?> getAuthDataFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthDataFromCache, []),
            returnValue: _i6.Future<_i2.AuthUser?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.AuthUser?>.value(),
          )
          as _i6.Future<_i2.AuthUser?>);

  @override
  _i6.Future<void> writeAuthDataToCache(_i2.AuthUser? authData) =>
      (super.noSuchMethod(
            Invocation.method(#writeAuthDataToCache, [authData]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> writeSessionToCache(
    _i2.AuthUser? authUser,
    _i2.User? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeSessionToCache, [authUser, user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.User?> getUserFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#getUserFromCache, []),
            returnValue: _i6.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.User?>.value(),
          )
          as _i6.Future<_i2.User?>);

  @override
  _i6.Future<void> writeUserToCache(_i2.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#writeUserToCache, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getPasswordHash() =>
      (super.noSuchMethod(
            Invocation.method(#getPasswordHash, []),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> saveUserPasswordHash(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserPasswordHash, [email, password]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearPasswordHash() =>
      (super.noSuchMethod(
            Invocation.method(#clearPasswordHash, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [FirebaseAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthRepository extends _i1.Mock
    implements _i2.FirebaseAuthRepository {
  @override
  _i6.Stream<_i2.AuthUser?> get userChanges =>
      (super.noSuchMethod(
            Invocation.getter(#userChanges),
            returnValue: _i6.Stream<_i2.AuthUser?>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.AuthUser?>.empty(),
          )
          as _i6.Stream<_i2.AuthUser?>);

  @override
  _i6.Future<void> signUpWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendPasswordResetEmail({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {#email: email}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> reauthWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reauthWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  @override
  _i2.DBGraphQLClient get graphQLClient =>
      (super.noSuchMethod(
            Invocation.getter(#graphQLClient),
            returnValue: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
            returnValueForMissingStub: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
          )
          as _i2.DBGraphQLClient);

  @override
  _i2.GQLParser get parser =>
      (super.noSuchMethod(
            Invocation.getter(#parser),
            returnValue: _FakeGQLParser_1(this, Invocation.getter(#parser)),
            returnValueForMissingStub: _FakeGQLParser_1(
              this,
              Invocation.getter(#parser),
            ),
          )
          as _i2.GQLParser);

  @override
  _i2.DBVarsTransformer get varsTransformer =>
      (super.noSuchMethod(
            Invocation.getter(#varsTransformer),
            returnValue: _FakeDBVarsTransformer_2(
              this,
              Invocation.getter(#varsTransformer),
            ),
            returnValueForMissingStub: _FakeDBVarsTransformer_2(
              this,
              Invocation.getter(#varsTransformer),
            ),
          )
          as _i2.DBVarsTransformer);

  @override
  _i2.AdvancedQueryParser get advancedQueryParser =>
      (super.noSuchMethod(
            Invocation.getter(#advancedQueryParser),
            returnValue: _FakeAdvancedQueryParser_3(
              this,
              Invocation.getter(#advancedQueryParser),
            ),
            returnValueForMissingStub: _FakeAdvancedQueryParser_3(
              this,
              Invocation.getter(#advancedQueryParser),
            ),
          )
          as _i2.AdvancedQueryParser);

  @override
  _i2.HomeDAO get home =>
      (super.noSuchMethod(
            Invocation.getter(#home),
            returnValue: _FakeHomeDAO_4(this, Invocation.getter(#home)),
            returnValueForMissingStub: _FakeHomeDAO_4(
              this,
              Invocation.getter(#home),
            ),
          )
          as _i2.HomeDAO);

  @override
  _i2.AreasDAO get areas =>
      (super.noSuchMethod(
            Invocation.getter(#areas),
            returnValue: _FakeAreasDAO_5(this, Invocation.getter(#areas)),
            returnValueForMissingStub: _FakeAreasDAO_5(
              this,
              Invocation.getter(#areas),
            ),
          )
          as _i2.AreasDAO);

  @override
  _i2.StreetsDAO get streets =>
      (super.noSuchMethod(
            Invocation.getter(#streets),
            returnValue: _FakeStreetsDAO_6(this, Invocation.getter(#streets)),
            returnValueForMissingStub: _FakeStreetsDAO_6(
              this,
              Invocation.getter(#streets),
            ),
          )
          as _i2.StreetsDAO);

  @override
  _i2.FamiliesDAO get families =>
      (super.noSuchMethod(
            Invocation.getter(#families),
            returnValue: _FakeFamiliesDAO_7(this, Invocation.getter(#families)),
            returnValueForMissingStub: _FakeFamiliesDAO_7(
              this,
              Invocation.getter(#families),
            ),
          )
          as _i2.FamiliesDAO);

  @override
  _i2.StoresDAO get stores =>
      (super.noSuchMethod(
            Invocation.getter(#stores),
            returnValue: _FakeStoresDAO_8(this, Invocation.getter(#stores)),
            returnValueForMissingStub: _FakeStoresDAO_8(
              this,
              Invocation.getter(#stores),
            ),
          )
          as _i2.StoresDAO);

  @override
  _i2.PersonsDAO get persons =>
      (super.noSuchMethod(
            Invocation.getter(#persons),
            returnValue: _FakePersonsDAO_9(this, Invocation.getter(#persons)),
            returnValueForMissingStub: _FakePersonsDAO_9(
              this,
              Invocation.getter(#persons),
            ),
          )
          as _i2.PersonsDAO);

  @override
  _i2.ServicesDAO get services =>
      (super.noSuchMethod(
            Invocation.getter(#services),
            returnValue: _FakeServicesDAO_10(
              this,
              Invocation.getter(#services),
            ),
            returnValueForMissingStub: _FakeServicesDAO_10(
              this,
              Invocation.getter(#services),
            ),
          )
          as _i2.ServicesDAO);

  @override
  _i2.ClassesDAO get classes =>
      (super.noSuchMethod(
            Invocation.getter(#classes),
            returnValue: _FakeClassesDAO_11(this, Invocation.getter(#classes)),
            returnValueForMissingStub: _FakeClassesDAO_11(
              this,
              Invocation.getter(#classes),
            ),
          )
          as _i2.ClassesDAO);

  @override
  _i2.GroupsDAO get groups =>
      (super.noSuchMethod(
            Invocation.getter(#groups),
            returnValue: _FakeGroupsDAO_12(this, Invocation.getter(#groups)),
            returnValueForMissingStub: _FakeGroupsDAO_12(
              this,
              Invocation.getter(#groups),
            ),
          )
          as _i2.GroupsDAO);

  @override
  _i2.UsersDAO get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeUsersDAO_13(this, Invocation.getter(#users)),
            returnValueForMissingStub: _FakeUsersDAO_13(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i2.UsersDAO);

  @override
  _i2.UserPermissionsDAO get userPermissions =>
      (super.noSuchMethod(
            Invocation.getter(#userPermissions),
            returnValue: _FakeUserPermissionsDAO_14(
              this,
              Invocation.getter(#userPermissions),
            ),
            returnValueForMissingStub: _FakeUserPermissionsDAO_14(
              this,
              Invocation.getter(#userPermissions),
            ),
          )
          as _i2.UserPermissionsDAO);

  @override
  _i2.InvitationsDAO get invitations =>
      (super.noSuchMethod(
            Invocation.getter(#invitations),
            returnValue: _FakeInvitationsDAO_15(
              this,
              Invocation.getter(#invitations),
            ),
            returnValueForMissingStub: _FakeInvitationsDAO_15(
              this,
              Invocation.getter(#invitations),
            ),
          )
          as _i2.InvitationsDAO);

  @override
  _i2.UserPreferencesDAO get userPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#userPreferences),
            returnValue: _FakeUserPreferencesDAO_16(
              this,
              Invocation.getter(#userPreferences),
            ),
            returnValueForMissingStub: _FakeUserPreferencesDAO_16(
              this,
              Invocation.getter(#userPreferences),
            ),
          )
          as _i2.UserPreferencesDAO);

  @override
  _i2.FcmTokensDAO get fcmTokens =>
      (super.noSuchMethod(
            Invocation.getter(#fcmTokens),
            returnValue: _FakeFcmTokensDAO_17(
              this,
              Invocation.getter(#fcmTokens),
            ),
            returnValueForMissingStub: _FakeFcmTokensDAO_17(
              this,
              Invocation.getter(#fcmTokens),
            ),
          )
          as _i2.FcmTokensDAO);

  @override
  _i2.MetadataDAO get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeMetadataDAO_18(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeMetadataDAO_18(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.MetadataDAO);

  @override
  _i2.HistoryDAO get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: _FakeHistoryDAO_19(this, Invocation.getter(#history)),
            returnValueForMissingStub: _FakeHistoryDAO_19(
              this,
              Invocation.getter(#history),
            ),
          )
          as _i2.HistoryDAO);

  @override
  _i2.MeetingsDAO get meetings =>
      (super.noSuchMethod(
            Invocation.getter(#meetings),
            returnValue: _FakeMeetingsDAO_20(
              this,
              Invocation.getter(#meetings),
            ),
            returnValueForMissingStub: _FakeMeetingsDAO_20(
              this,
              Invocation.getter(#meetings),
            ),
          )
          as _i2.MeetingsDAO);

  @override
  Map<Type, _i2.DAOBase<_i2.ViewableWithID>> get daosByType =>
      (super.noSuchMethod(
            Invocation.getter(#daosByType),
            returnValue: <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
            returnValueForMissingStub:
                <Type, _i2.DAOBase<_i2.ViewableWithID>>{},
          )
          as Map<Type, _i2.DAOBase<_i2.ViewableWithID>>);
}

/// A class which mocks [LocalAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthService extends _i1.Mock implements _i2.LocalAuthService {
  @override
  Duration get timeToReauth =>
      (super.noSuchMethod(
            Invocation.getter(#timeToReauth),
            returnValue: _FakeDuration_21(
              this,
              Invocation.getter(#timeToReauth),
            ),
            returnValueForMissingStub: _FakeDuration_21(
              this,
              Invocation.getter(#timeToReauth),
            ),
          )
          as Duration);

  @override
  bool get shouldAuthenticate =>
      (super.noSuchMethod(
            Invocation.getter(#shouldAuthenticate),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Stream<void> get refreshUIStream =>
      (super.noSuchMethod(
            Invocation.getter(#refreshUIStream),
            returnValue: _i6.Stream<void>.empty(),
            returnValueForMissingStub: _i6.Stream<void>.empty(),
          )
          as _i6.Stream<void>);

  @override
  bool shouldAuthenticateForPath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#shouldAuthenticateForPath, [path]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void revokeAuthForPath(String? path) => super.noSuchMethod(
    Invocation.method(#revokeAuthForPath, [path]),
    returnValueForMissingStub: null,
  );

  @override
  void revokeAuthForAllPaths() => super.noSuchMethod(
    Invocation.method(#revokeAuthForAllPaths, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i7.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleReauth() => super.noSuchMethod(
    Invocation.method(#scheduleReauth, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetAuthState({String? path}) => super.noSuchMethod(
    Invocation.method(#resetAuthState, [], {#path: path}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> canCheckBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#canCheckBiometrics, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> verifyPassword({
    required String? email,
    required String? password,
    String? storedPasswordHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPassword, [], {
              #email: email,
              #password: password,
              #storedPasswordHash: storedPasswordHash,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  bool handleStartBackGesture(_i8.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i8.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> didPushRouteInformation(
    _i9.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i7.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i7.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i6.Future<_i7.AppExitResponse>.value(
              _i7.AppExitResponse.exit,
            ),
            returnValueForMissingStub: _i6.Future<_i7.AppExitResponse>.value(
              _i7.AppExitResponse.exit,
            ),
          )
          as _i6.Future<_i7.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i2.ConnectivityService {
  @override
  String get urlToPing =>
      (super.noSuchMethod(
            Invocation.getter(#urlToPing),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#urlToPing),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#urlToPing),
            ),
          )
          as String);

  @override
  _i3.ValueStream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _FakeValueStream_22<bool>(
              this,
              Invocation.getter(#connectivityStream),
            ),
            returnValueForMissingStub: _FakeValueStream_22<bool>(
              this,
              Invocation.getter(#connectivityStream),
            ),
          )
          as _i3.ValueStream<bool>);

  @override
  _i6.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UsersDAO].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersDAO extends _i1.Mock implements _i2.UsersDAO {
  @override
  _i2.StreamAllConfig<_i2.User> get baseStreamAllConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseStreamAllConfig),
            returnValue: _FakeStreamAllConfig_23<_i2.User>(
              this,
              Invocation.getter(#baseStreamAllConfig),
            ),
            returnValueForMissingStub: _FakeStreamAllConfig_23<_i2.User>(
              this,
              Invocation.getter(#baseStreamAllConfig),
            ),
          )
          as _i2.StreamAllConfig<_i2.User>);

  @override
  _i2.StreamCountConfig<_i2.User> get baseStreamCountConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseStreamCountConfig),
            returnValue: _FakeStreamCountConfig_24<_i2.User>(
              this,
              Invocation.getter(#baseStreamCountConfig),
            ),
            returnValueForMissingStub: _FakeStreamCountConfig_24<_i2.User>(
              this,
              Invocation.getter(#baseStreamCountConfig),
            ),
          )
          as _i2.StreamCountConfig<_i2.User>);

  @override
  _i2.StreamSingleByIdConfig<_i2.User> get baseStreamSingleByIdConfig =>
      (super.noSuchMethod(
            Invocation.getter(#baseStreamSingleByIdConfig),
            returnValue: _FakeStreamSingleByIdConfig_25<_i2.User>(
              this,
              Invocation.getter(#baseStreamSingleByIdConfig),
            ),
            returnValueForMissingStub: _FakeStreamSingleByIdConfig_25<_i2.User>(
              this,
              Invocation.getter(#baseStreamSingleByIdConfig),
            ),
          )
          as _i2.StreamSingleByIdConfig<_i2.User>);

  @override
  _i2.DatabaseService get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabaseService_26(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeDatabaseService_26(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i2.User Function(Map<String, dynamic>) get fromJson =>
      (super.noSuchMethod(
            Invocation.getter(#fromJson),
            returnValue: (Map<String, dynamic> json) =>
                _FakeUser_27(this, Invocation.getter(#fromJson)),
            returnValueForMissingStub: (Map<String, dynamic> json) =>
                _FakeUser_27(this, Invocation.getter(#fromJson)),
          )
          as _i2.User Function(Map<String, dynamic>));

  @override
  _i2.DBGraphQLClient get graphQLClient =>
      (super.noSuchMethod(
            Invocation.getter(#graphQLClient),
            returnValue: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
            returnValueForMissingStub: _FakeDBGraphQLClient_0(
              this,
              Invocation.getter(#graphQLClient),
            ),
          )
          as _i2.DBGraphQLClient);

  @override
  _i2.StreamableDAOProxy<_i2.User> get streamingProxy =>
      (super.noSuchMethod(
            Invocation.getter(#streamingProxy),
            returnValue: _FakeStreamableDAOProxy_28<_i2.User>(
              this,
              Invocation.getter(#streamingProxy),
            ),
            returnValueForMissingStub: _FakeStreamableDAOProxy_28<_i2.User>(
              this,
              Invocation.getter(#streamingProxy),
            ),
          )
          as _i2.StreamableDAOProxy<_i2.User>);

  @override
  _i6.Stream<_i2.User?> streamSingleById({
    required String? id,
    bool? fullData = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamSingleById, [], {
              #id: id,
              #fullData: fullData,
            }),
            returnValue: _i6.Stream<_i2.User?>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.User?>.empty(),
          )
          as _i6.Stream<_i2.User?>);

  @override
  _i6.Future<void> updateUser(_i2.UserUpdate? update) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [update]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i2.PaginatableStreamBase<_i2.User> streamAll({
    _i6.Stream<String?>? searchQuery,
    _i6.Stream<List<_i2.Filter<Object>>>? where,
    _i6.Stream<List<_i2.OrderBy>>? orderBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamAll, [], {
              #searchQuery: searchQuery,
              #where: where,
              #orderBy: orderBy,
            }),
            returnValue: _FakePaginatableStreamBase_29<_i2.User>(
              this,
              Invocation.method(#streamAll, [], {
                #searchQuery: searchQuery,
                #where: where,
                #orderBy: orderBy,
              }),
            ),
            returnValueForMissingStub: _FakePaginatableStreamBase_29<_i2.User>(
              this,
              Invocation.method(#streamAll, [], {
                #searchQuery: searchQuery,
                #where: where,
                #orderBy: orderBy,
              }),
            ),
          )
          as _i2.PaginatableStreamBase<_i2.User>);
}

/// A class which mocks [FunctionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctionsService extends _i1.Mock implements _i2.FunctionsService {
  @override
  _i4.HttpsCallable httpsCallable(
    String? functionName, {
    _i4.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #httpsCallable,
              [functionName],
              {#options: options},
            ),
            returnValue: _FakeHttpsCallable_30(
              this,
              Invocation.method(
                #httpsCallable,
                [functionName],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeHttpsCallable_30(
              this,
              Invocation.method(
                #httpsCallable,
                [functionName],
                {#options: options},
              ),
            ),
          )
          as _i4.HttpsCallable);

  @override
  _i6.Future<String> getDownloadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDownloadUrl,
              [table, id],
              {#contentType: contentType},
            ),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #getDownloadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #getDownloadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> getUploadUrl(
    String? table,
    String? id, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUploadUrl,
              [table, id],
              {#contentType: contentType},
            ),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #getUploadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #getUploadUrl,
                  [table, id],
                  {#contentType: contentType},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> deletePhoto(String? table, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePhoto, [table, id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> tryClaimAccount() =>
      (super.noSuchMethod(
            Invocation.method(#tryClaimAccount, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.Address?> getAddressFromLocation(_i2.Point? location) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressFromLocation, [location]),
            returnValue: _i6.Future<_i2.Address?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.Address?>.value(),
          )
          as _i6.Future<_i2.Address?>);

  @override
  _i6.Future<_i5.Response<dynamic>> uploadPhoto({
    required String? url,
    required _i6.Stream<List<int>>? fileStream,
    String? contentType,
    int? fileLength,
    void Function(int, int)? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [], {
              #url: url,
              #fileStream: fileStream,
              #contentType: contentType,
              #fileLength: fileLength,
              #onSendProgress: onSendProgress,
            }),
            returnValue: _i6.Future<_i5.Response<dynamic>>.value(
              _FakeResponse_31<dynamic>(
                this,
                Invocation.method(#uploadPhoto, [], {
                  #url: url,
                  #fileStream: fileStream,
                  #contentType: contentType,
                  #fileLength: fileLength,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.Response<dynamic>>.value(
              _FakeResponse_31<dynamic>(
                this,
                Invocation.method(#uploadPhoto, [], {
                  #url: url,
                  #fileStream: fileStream,
                  #contentType: contentType,
                  #fileLength: fileLength,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.Response<dynamic>>);

  @override
  _i6.Future<bool> checkHasuraHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkHasuraHealth, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> applyInvitationCode(String? invitationCode) =>
      (super.noSuchMethod(
            Invocation.method(#applyInvitationCode, [invitationCode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> getAppDownloadLink(String? platform) =>
      (super.noSuchMethod(
            Invocation.method(#getAppDownloadLink, [platform]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getAppDownloadLink, [platform]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getAppDownloadLink, [platform]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> deleteMyAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMyAccount, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> createUser(_i2.CreateUserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [request]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createUser, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createUser, [request]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> exportData({
    List<String>? areasIds = const [],
    List<String>? servicesIds = const [],
    List<String>? classesIds = const [],
    List<String>? groupsIds = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportData, [], {
              #areasIds: areasIds,
              #servicesIds: servicesIds,
              #classesIds: classesIds,
              #groupsIds: groupsIds,
            }),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#exportData, [], {
                  #areasIds: areasIds,
                  #servicesIds: servicesIds,
                  #classesIds: classesIds,
                  #groupsIds: groupsIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#exportData, [], {
                  #areasIds: areasIds,
                  #servicesIds: servicesIds,
                  #classesIds: classesIds,
                  #groupsIds: groupsIds,
                }),
              ),
            ),
          )
          as _i6.Future<String>);
}
