subscription watchAllJobs(
  $where: [JobsBoolExp!] = {}
  $orderBy: [JobsOrderBy!] = { name: ASC }
  $limit: Int = 25
) {
  jobs(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
  }
}
