fragment Service on Services {
  ...ServiceNoPhoto
  photoUpdatedAt
  blurhash
}

fragment ServiceWithStudyYears on Services {
  ...ServiceNoPhoto
  studyYearFrom {
    ...StudyYear
  }
  studyYearTo {
    ...StudyYear
  }
  photoUpdatedAt
  blurhash
}

fragment ServiceNoPhoto on Services {
  id
  name
  color
  userCanEdit
}
