subscription watchAllServices(
  $where: [ServicesBoolExp!] = {}
  $groupsWhere: [GroupsBoolExp!] = {}
  $classesWhere: [ClassesBoolExp!] = {}
  $orderBy: [ServicesOrderBy!] = { studyYearFromId: ASC, studyYearToId: ASC }
  $classesOrderBy: [ClassesOrderBy!] = {
    studyYear: { order: ASC }
    serviceGender: DESC_NULLS_LAST
  }
  $groupsOrderBy: [GroupsOrderBy!] = {
    service: { studyYearFromId: ASC, studyYearToId: ASC }
  }
  $limit: Int = 200
) {
  services(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    ...ServiceWithStudyYears
    classes(where: { _and: $classesWhere }, orderBy: $classesOrderBy) {
      ...Class

      studyYear {
        name
        order
      }
    }
    groups(where: { _and: $groupsWhere }, orderBy: $groupsOrderBy) {
      ...Group
    }
  }
}
subscription watchServicesCount($where: [ServicesBoolExp!] = {}) {
  servicesAggregate(where: { _and: $where }) {
    aggregate {
      count
    }
  }
}

subscription watchService($id: uuid!) {
  servicesByPk(id: $id) {
    ...ServiceWithStudyYears
    lastEdit {
      ...LatestEditHistory
    }
    adminUsers(distinctOn: uid) {
      user {
        ...User
      }
    }
    nextService {
      ...Service
    }
  }
}
