subscription watchAllPersonStates(
  $where: [PersonStatesBoolExp!] = {}
  $orderBy: [PersonStatesOrderBy!] = { name: ASC }
  $limit: Int
) {
  personStates(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    id
    name
    color
  }
}
