mutation deleteStreet($streetId: uuid!) {
  deleteStreetsByPk(id: $streetId) {
    ...Street
  }
}

mutation insertStreet($newStreet: StreetsInsertInput!) {
  insertStreetsOne(object: $newStreet) {
    ...Street
  }
}

mutation updateStreet(
  $streetId: uuid!
  $newStreet: StreetsSetInput!
  $lastVisit: timestamptz
  $addAreas: [AreasStreetsInsertInput!]!
  $removeAreas: [uuid!]!
  $updateLastVisit: Boolean!
  $insertAreasStreets: Boolean!
  $deleteAreasStreets: Boolean!
) {
  updateStreetsByPk(pkColumns: { id: $streetId }, _set: $newStreet) {
    ...Street
  }

  insertHistoryVisitHistoryOne(
    object: { table: "streets", recordId: $streetId, time: $lastVisit }
  ) @include(if: $updateLastVisit) {
    ...VisitHistory
  }

  insertAreasStreets(objects: $addAreas) @include(if: $insertAreasStreets) {
    affectedRows
  }

  deleteAreasStreets(
    where: { streetId: { _eq: $streetId }, areaId: { _in: $removeAreas } }
  ) @include(if: $deleteAreasStreets) {
    affectedRows
  }
}
