mutation deleteStreet($streetId: uuid!) {
  deleteStreetsByPk(id: $streetId) {
    ...Street
  }
}

mutation insertStreet($newStreet: StreetsInsertInput!) {
  insertStreetsOne(object: $newStreet) {
    ...Street
  }
}

mutation updateStreet(
  $streetId: uuid!
  $newStreet: StreetsSetInput!
  $lastVisit: timestamptz
  $updateLastVisit: Boolean!
) {
  updateStreetsByPk(pkColumns: { id: $streetId }, _set: $newStreet) {
    ...Street
  }

  insertHistoryVisitHistoryOne(
    object: { table: "streets", recordId: $streetId, time: $lastVisit }
  ) @include(if: $updateLastVisit) {
    ...VisitHistory
  }
}
