subscription watchAllStreets(
  $where: [StreetsBoolExp!] = {}
  $orderBy: [StreetsOrderBy!] = { name: ASC }
  $limit: Int = 200
) {
  streets(where: { _and: $where }, orderBy: $orderBy, limit: $limit) {
    ...Street
    line
  }
}

subscription watchStreetsCount($where: [StreetsBoolExp!] = {}, $limit: Int) {
  streetsAggregate(where: { _and: $where }, limit: $limit) {
    aggregate {
      count
    }
  }
}

subscription watchStreet($id: uuid!) {
  streetsByPk(id: $id) {
    ...Street
    areas(orderBy: { area: { name: ASC } }) {
      area {
        ...Area
      }
    }
    line
    lastEdit {
      ...LatestEditHistory
    }
    lastVisit {
      ...LatestVisitHistory
    }
  }
}
