FROM node:24-trixie-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-21-jre-headless ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools@15.29.0

WORKDIR /srv/firebase
