name: Test and upload coverage

on: [push, pull_request]

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get specific changed files
        id: source-changed
        uses: tj-actions/changed-files@v13
        with:
          files: |
            **.dart
            **/*.dart
            assets
            pubspec.yaml
            build.yaml
            analysis_options.yaml
            codecov.yaml

      - name: Get Cached Flutter installation
        uses: actions/cache@v3
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: flutter-3.10.6-stable

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        with:
          cache: true
          cache-key: "flutter-:channel:-:version:"
          channel: "stable"

      - name: Get Cached dependencies
        uses: actions/cache@v3
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        id: flutter_cache
        with:
          path: ${{ env.PUB_CACHE }}
          key: flutter-dependencies-v1-${{hashFiles('pubspec.yaml', 'pubspec.lock')}}
          restore-keys: |
            flutter-dependencies-v1-

      - name: Populate the Flutter tool's cache of binary artifacts
        if: ${{ steps.source-changed.outputs.any_changed == 'true' && steps.flutter_cache.outputs.cache-hit != 'true' }}
        run: |
          flutter config --no-analytics
          flutter precache

      - name: Get Cached .dart_tool
        uses: actions/cache@v3
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        id: dart_tool_cache
        with:
          path: .dart_tool
          key: dart-tool-v1-${{hashFiles('pubspec.yaml', 'build.yaml')}}
          restore-keys: |
            dart-tool-v1-

      - name: Override git ignored files
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        run: |
          cp --force lib/firebase_options_ci.dart lib/firebase_options.dart
          cp --force lib/src/services/encryption/encryption_service_ci_impl.dart lib/src/services/encryption/encryption_service_impl.dart
          cp --force lib/src/services/secrets/secrets_service_ci_impl.dart lib/src/services/secrets/secrets_service_impl.dart
          cp pubspec_overrides_ci.yaml pubspec_overrides.yaml

      - name: Install dependencies
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        run: flutter pub get

      - name: Run new builder
        if: ${{ steps.source-changed.outputs.any_changed == 'true' && steps.dart_tool_cache.outputs.cache-hit != 'true' }}
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run cached builder
        if: ${{ steps.source-changed.outputs.any_changed == 'true' && steps.dart_tool_cache.outputs.cache-hit == 'true' }}
        run: dart run build_runner build

      - name: Analyze project source
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        uses: ValentinVignal/action-dart-analyze@v0.15
        with:
          fail-on: "warning"

      - name: Run Tests
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        run: flutter test --coverage --machine > test-results.json --dart-define CI=true

      - name: Upload test-results.json to artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() || success() }}
        with:
          name: test-results
          path: test-results.json

      - name: Upload Test Report
        uses: dorny/test-reporter@v1
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        with:
          name: Unit and Widget Tests
          path: test-results.json
          reporter: flutter-json

      - uses: codecov/codecov-action@v3
        if: ${{ steps.source-changed.outputs.any_changed == 'true' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
