name: Patch

on:
  push:
    tags:
      - "v*.*.*\\+*"
  workflow_dispatch:
    inputs:
      base_version:
        description: "Version to be patched (e.g., latest, 1.0.0+1)"
        required: true
        type: string
      android:
        description: "Patch for Android"
        required: false
        default: true
        type: boolean
      ios:
        description: "Patch for iOS"
        required: false
        default: true
        type: boolean

defaults:
  run:
    working-directory: client

jobs:
  patch-mobile:
    permissions:
      contents: write

    if: ${{ github.event_name == 'push' || (github.event.inputs.android == 'true' || github.event.inputs.ios == 'true') }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        exclude:
          # Skip Ubuntu (Android) if only iOS is requested
          - os: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.android == 'false' && 'ubuntu-latest' }}
          # Skip macOS (iOS) if only Android is requested
          - os: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ios == 'false' && 'macos-latest' }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Free up disk space
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          # Space usage before cleanup
          df -h /

          # Remove unused tool caches
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          # Verify gains
          df -h /

      - name: Get Flutter
        id: flutter-action
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          cache: true
          flutter-version-file: client/.fvmrc
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:"
          cache-key: "flutter:os:-:channel:-:version:-:arch:"

      - name: Install dependencies
        run: flutter pub get

      - name: Run new builder
        run: rm -r lib/src/core/graphql/__generated__/; dart run build_runner build && ./scripts/split_schema_graphql_dart.sh

      - name: Install Codemagic CLI tools
        if: ${{ matrix.os == 'macos-latest' }}
        run: pip install codemagic-cli-tools

      - name: Set up keychain
        if: ${{ matrix.os == 'macos-latest' }}
        run: keychain initialize

      - name: Fetch signing files
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
          APP_STORE_APPLE_ID: ${{ secrets.APP_STORE_APPLE_ID }}
        run: |
          cd ios
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
          --type IOS_APP_STORE \
          --create
      - name: Set up signing certificate
        if: ${{ matrix.os == 'macos-latest' }}
        run: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        if: ${{ matrix.os == 'macos-latest' }}
        run: xcode-project use-profiles

      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@1866dd9f55da8f25608b70bdde6e095c06f1dc01 # main
        with:
          cache: true

      - name: Set Up Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          cache: "gradle"
          distribution: "temurin"
          java-version: "17"

      - name: Set Up latest stable Xcode version
        if: ${{ matrix.os == 'macos-latest' }}
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: latest-stable

      - name: Populate the Flutter tool's cache of binary artifacts
        run: flutter precache

      - name: Decode and save android secrets
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}
        run: |
          echo $ANDROID_SIGNING_KEY | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/app/key.keystore
          echo $GOOGLE_SERVICES_JSON | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/app/google-services.json
          echo $ANDROID_KEYSTORE_PROPERTIES | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/releaseKey.properties

      - name: Decode app production environment
        env:
          APP_PROD_ENV_FILE: ${{ secrets.APP_PROD_ENV_FILE }}
        run: echo "$APP_PROD_ENV_FILE" | base64 -d > .env

      - name: 🚀 Shorebird Patch Android
        uses: shorebirdtech/shorebird-patch@deb179c67708c6b0caf7582eac41361c8d51948a # main
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        with:
          platform: android
          working-directory: client
          release-version: ${{ inputs.base_version }}
          args: --allow-asset-diffs
            --dart-define-from-file=.env

      - name: Run pod repo update
        if: ${{ matrix.os == 'macos-latest' }}
        run: pod repo update

      - name: Update podfile.lock
        if: ${{ matrix.os == 'macos-latest' }}
        run: cd ios && pod install --repo-update

      - name: 🚀 Shorebird Patch iOS
        uses: shorebirdtech/shorebird-patch@deb179c67708c6b0caf7582eac41361c8d51948a # main
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        with:
          platform: ios
          working-directory: client
          release-version: ${{ inputs.base_version }}
          args: --export-options-plist="$HOME/export_options.plist"
            --allow-asset-diffs
            --dart-define-from-file=.env

      - name: Delete app production environment
        if: ${{ always() }}
        run: rm -f .env
