name: Test Coverage Report and Release

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get specific changed files
        id: source-changed
        uses: step-security/changed-files@v45
        with:
          files: |
            **.dart
            **/*.dart
            client/assets
            client/pubspec.yaml
            client/build.yaml
            client/analysis_options.yaml
            codecov.yaml

      - name: Check if testing is required
        id: run-tests
        env:
          run_tests: ${{ steps.source-changed.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[ci release]') || contains(github.event.head_commit.message, '[ci release apk]') || contains(github.event.head_commit.message, '[ci release ios]') || contains(github.event.head_commit.message, '[ci test]') }}
        run: |
          echo "run-tests=$run_tests" >> $GITHUB_OUTPUT

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        if: ${{ steps.run-tests.outputs.run-tests == 'true' }}
        with:
          cache: true
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:"
          cache-key: "flutter:os:-:channel:-:version:-:arch:"
          channel: "stable"

      - name: Populate the Flutter tool's cache of binary artifacts
        if: ${{ steps.run-tests.outputs.run-tests == 'true'}}
        run: flutter precache

      - name: Override git ignored files for testing
        if: ${{ steps.run-tests.outputs.run-tests == 'true' }}
        working-directory: client
        run: |
          cp --force lib/firebase_options_ci.dart lib/firebase_options.dart
          cp --force lib/src/core/services/secrets/secrets_service_ci_impl.dart lib/src/core/services/secrets/secrets_service_impl.dart

      - name: Install dependencies
        if: ${{ steps.run-tests.outputs.run-tests == 'true' }}
        working-directory: client
        run: flutter pub get

      - name: Run new builder
        if: ${{ steps.run-tests.outputs.run-tests == 'true' }}
        working-directory: client
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Tests
        if: ${{ steps.run-tests.outputs.run-tests == 'true' }}
        working-directory: client
        run: flutter test --coverage -r expanded --file-reporter "json:test-results.json" --dart-define CI=true

      - name: Upload test-results.json to artifacts
        uses: actions/upload-artifact@v4
        if: ${{ (success() || failure()) && steps.run-tests.outputs.run-tests == 'true'}}
        with:
          name: test-results
          path: client/test-results.json

  upload-coverage:
    permissions:
      contents: read
      actions: read
      checks: write

    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Download test-results.json from artifacts
        id: check-test-results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: test-results
          path: /tmp/

      - name: Checkout repository
        if: ${{ steps.check-test-results.outcome == 'success' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Copy test-results.json from artifacts
        if: ${{ steps.check-test-results.outcome == 'success' }}
        run: |
          cp /tmp/test-results.json client/test-results.json

      - name: Report test results to run checks
        if: ${{ steps.check-test-results.outcome == 'success' }}
        uses: dorny/test-reporter@v1
        with:
          name: "Unit and Widget Tests"
          path: client/test-results.json
          reporter: flutter-json

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        if: ${{ steps.check-test-results.outcome == 'success' }}
        with:
          directory: client
          token: ${{ secrets.CODECOV_TOKEN }}

  release-mobile:
    permissions:
      contents: write

    needs: run-tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Excludes ubuntu when building ipa only and macos when building apk only
        exclude:
          - os: ${{ contains(github.event.head_commit.message, '[ci release ios]') && 'ubuntu-latest' }}
          - os: ${{ contains(github.event.head_commit.message, '[ci release apk]') && 'macos-latest' }}
    runs-on: ${{ matrix.os }}
    if: github.actor == github.repository_owner && (github.event_name == 'workflow_dispatch' || github.event_name != 'pull_request' && (contains(github.event.head_commit.message, '[ci release]') || contains(github.event.head_commit.message, '[ci release apk]') || contains(github.event.head_commit.message, '[ci release ios]')))

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:"
          cache-key: "flutter:os:-:channel:-:version:-:arch:"
          channel: "stable"

      - name: Set Up Java
        uses: actions/setup-java@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          cache: "gradle"
          distribution: "corretto"
          java-version: "17"

      - name: Populate the Flutter tool's cache of binary artifacts
        run: flutter precache

      - name: Decode and save secrets to files
        working-directory: client
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
          SECRETS_SERVICE_DART: ${{ secrets.SECRETS_SERVICE_DART }}
        run: |
          echo $FIREBASE_OPTIONS_DART | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./lib/firebase_options.dart
          echo $SECRETS_SERVICE_DART | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./lib/src/core/services/secrets/secrets_service_impl.dart

      - name: Decode and save android secrets
        working-directory: client
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          ANDROID_STRINGS: ${{ secrets.ANDROID_STRINGS }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}
        run: |
          echo $ANDROID_SIGNING_KEY | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/app/key.keystore
          echo $ANDROID_STRINGS | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/app/src/main/res/values/strings.xml
          echo $GOOGLE_SERVICES_JSON | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/app/google-services.json
          echo $ANDROID_KEYSTORE_PROPERTIES | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./android/releaseKey.properties

      - name: Decode and save ios secrets
        working-directory: client
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}
        run: |
          echo $GOOGLE_SERVICES_PLIST | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./ios/Runner/GoogleService-Info.plist

      - name: Install dependencies
        working-directory: client
        run: flutter pub get

      - name: Run new builder
        working-directory: client
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build apk
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: client
        run: flutter build apk

      - name: Run pod repo update
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: client
        run: pod repo update

      - name: Update podfile.lock
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: client/ios
        run: pod install --repo-update

      - name: Build ios
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: client
        run: flutter build ios --release --no-codesign

      - name: Get version from pubspec.yaml
        working-directory: client
        id: version
        run: |
          version=$(grep 'version:' pubspec.yaml | awk '{print $2}' | awk -F "+" '{print $1}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Compress ios src
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: client
        run: tar -czf ios_dir-v${{ steps.version.outputs.version }}.tar.gz ios

      - name: Create an ipa
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: client
        run: |
          cd build/ios
          mv iphoneos Payload
          zip -r app-release-v${{steps.version.outputs.version}}.ipa Payload

      - name: Add version to APK filename
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: client
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.version }}.apk

      - name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.APP_RELEASE_UPLOADER_KEY }}"

      - name: Upload APK to Google Cloud Storage
        uses: "google-github-actions/upload-cloud-storage@v2"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          path: "client/build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.version }}.apk"
          destination: "${{ secrets.APP_RELEASE_GCS_BUCKET }}"

      - name: Upload iOS src to Google Cloud Storage
        uses: "google-github-actions/upload-cloud-storage@v2"
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: "client/ios_dir-v${{ steps.version.outputs.version }}.tar.gz"
          destination: "${{ secrets.APP_RELEASE_GCS_BUCKET }}"

      - name: Upload unsigned ipa to Google Cloud Storage
        uses: "google-github-actions/upload-cloud-storage@v2"
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: "client/build/ios/app-release-v${{ steps.version.outputs.version }}.ipa"
          destination: "${{ secrets.APP_RELEASE_GCS_BUCKET }}"

      - name: Create release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.version }}
          generateReleaseNotes: true

  release-web:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner && (github.event_name == 'workflow_dispatch' || github.event_name != 'pull_request' && (contains(github.event.head_commit.message, '[ci release]') || contains(github.event.head_commit.message, '[ci release web]')))

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:"
          cache-key: "flutter:os:-:channel:-:version:-:arch:"
          channel: "stable"

      - name: Populate the Flutter tool's cache of binary artifacts
        run: flutter precache

      - name: Decode and save secrets to files
        working-directory: client
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
          SECRETS_SERVICE_DART: ${{ secrets.SECRETS_SERVICE_DART }}
        run: |
          echo $FIREBASE_OPTIONS_DART | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./lib/firebase_options.dart
          echo $SECRETS_SERVICE_DART | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./lib/src/core/services/secrets/secrets_service_impl.dart

      - name: Install dependencies
        working-directory: client
        run: flutter pub get

      - name: Run new builder
        working-directory: client
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build web
        working-directory: client
        run: flutter build web

      - name: Copy web build to public folder
        run: cp -r ./client/build/web ./server/public

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_HOSTING_DEPLOYER_KEY }}
          entryPoint: ./server/
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
 
  update-app-version:
    runs-on: ubuntu-latest
    needs: [release-mobile, release-web]
    if: github.actor == github.repository_owner && (github.event_name == 'workflow_dispatch' || github.event_name != 'pull_request' && (contains(github.event.head_commit.message, '[ci release]') || contains(github.event.head_commit.message, '[ci release web]') || contains(github.event.head_commit.message, '[ci release apk]') || contains(github.event.head_commit.message, '[ci release ios]')))
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get current version
        id: get-version
        run: |
          version=$(grep 'version:' client/pubspec.yaml | awk '{print $2}' | awk -F "+" '{print $1}')
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Write service account key to file
        working-directory: server/functions
        env:
          FIREBASE_REMOTE_CONFIG_UPDATER_KEY: ${{ secrets.FIREBASE_REMOTE_CONFIG_UPDATER_KEY }}
        run: |
          echo $FIREBASE_REMOTE_CONFIG_UPDATER_KEY | sed 's/[^A-Za-z0-9+/=]//g' | base64 -d > ./firebase-service-account.json

      - name: Install npm dependencies
        working-directory: server/functions
        run: npm install

      - name: Build server
        working-directory: server/functions
        run: npm run build

      - name: Update remote config app version
        working-directory: server/functions
        env:
          LATEST_VERSION: ${{ steps.get-version.outputs.current_version }}
          GOOGLE_APPLICATION_CREDENTIALS: ./firebase-service-account.json
        run: node ./lib/update_remote_config_app_version.js

      - name: Remove service account key file
        working-directory: server/functions
        if: ${{ always() }}
        run: rm -f ./firebase-service-account.json
